AstarNetwork/astar-apps

- src/components/store/Dapp.vue
- src/components/store/StakePanel.vue
- src/components/store/modals/ClaimRewardModal.vue
Currently store is unable to get stake info on Shibuya, because of large number of stakers, which caused an issue with stake function.
Closes #143 
**Check list**
**Adds**
- stakeInfo validation
- disable stakeinfo loading on shibuya
- enabled claim when stakeinfo is not present
> Fix for stake when info is not present

- src/components/store/DiscoverDappsTab.vue
- src/components/store/statistics/DappsCount.vue
- src/components/store/statistics/TVL.vue
* Added comma in the value of 'Stakers Per Contract'
* Removed USD value of TVL for testnet
* Capitalized 'DAPPS COUNT' 
=Before=
=After=
**Check list**
> fix: modified styling for testnet in the store section

- src/components/balance/modals/MetamaskOption.vue
- src/components/balance/modals/ModalSelectAccount.vue
- src/components/balance/modals/ModalSelectAccountOption.vue
- src/hooks/helper/plasmUtils.ts
* Show Astar's format of SS58 address format for Ethereum Extension
* Fixed the bug when choosing the 'Send to' address when Etereum Extension is selected
**Check list**
**Adds**
**Fixes**
=Before=
https://gyazo.com/53e410eaf25994945774780e2b72a299
=After=
https://gyazo.com/67f081cd6c685cd8f51b0a952279f3fc
> shiden format for ecdsa imported account

- package.json
- src/@types/index.d.ts
- src/components/store/DiscoverDappsTab.vue
- src/components/store/statistics/DappsCount.vue
- src/components/store/statistics/Era.vue
- src/components/store/statistics/Requirement.vue
- src/components/store/statistics/TVL.vue
- src/components/store/statistics/era.scss
- src/hooks/index.ts
- src/hooks/useCurrentEra.ts
- src/i18n/en-US/index.ts
- src/pages/Store.vue
- yarn.lock
* Added "CURRENT ERA" field in the dApps Store section
* Display the requirement information besides the tabs depending on the screen size
[Updated: 22-Nov]
* Added counter animation
https://gyazo.com/317327b2e392790ae5e52d07c3d79112
**Check list**
**Adds**
Width: 
1014px
1288px:
> feat: Added CURRENT ERA field

- src/components/store/DiscoverDappsTab.vue
* Show missing information panels (when the progress% of era is less than [0.5%](https://github.com/PlasmNetwork/astar-apps/blob/2270ce85680127928acb9853d8eacbee3a6b7fbc/src/hooks/useCurrentEra.ts#L30))
**Check list**
**Fixes**
=Before=
Block until new era: 7,199
> fix: avoid missing information panels

- src/components/balance/modals/ModalAccount.vue
- src/components/balance/modals/ModalFaucet.vue
- src/components/balance/modals/ModalNetwork.vue
- src/components/balance/modals/ModalTransferAmount.vue
- src/components/balance/modals/ModalWithdrawalEvmDeposit.vue
- src/components/common/Modal.vue
- src/components/contracts/modals/ModalCodeHash.vue
- src/components/contracts/modals/ModalCreateDapps.vue
- src/components/dapp-staking/modals/ClaimRewardModal.vue
- src/components/dapp-staking/modals/ModalRegisterDapp.vue
- src/components/dapp-staking/modals/StakeModal.vue
* Fixed unable to close "Register a new dApp" modal bug
* Auto close modal when user clicks outside of it
Describe the bug:
Unable to close "Register a new dApp" modal 
(perhaps because of duplicated emits in [Modal.vue](https://github.com/AstarNetwork/astar-apps/blob/main/src/components/common/Modal.vue#L65) and [ModalRegisterDapp.vue](https://github.com/AstarNetwork/astar-apps/blob/main/src/components/dapp-staking/modals/ModalRegisterDapp.vue#L89))
To Reproduce:
1. Click "Registed dApp" button
2. Click "Close" button
Gif:
Before:
https://gyazo.com/8c192bfd9a85cfbb49146752cae68c3f
After: 
https://gyazo.com/b1775cb42962864caf63659c6d4c5344
https://gyazo.com/47a17553e334b9a3bd905489781fd307
**Check list**
> fix: Unable to close 'register dApp' modal bug

- src/components/dapp-staking/StakePanel.vue
- src/components/dapp-staking/modals/ClaimRewardModal.vue
- src/i18n/en-US/index.ts
This PR modifies behaviour of claim reward feature to claim rewards in chunks of 15 eras.
I tried to keep it simple.
The feature needs to be tested on Shibuya (when available) prior to merge to main.
**Check list**
**Adds**
- Claim rewards era chunks
**To-dos**
> Test ons Shibuya.
> Claim reward steps

- src/components/balance/BalancePlasm.vue
- src/components/balance/PlmBalance.vue
- src/hooks/useFaucet.ts
* Disable faucet button when the data is loading. (Avoid displaying the initial state information on faucet modal)
**Check list**
**Changes**
> fix: disable faucet button when the data is loading

- src/store/dapp-staking/actions.ts
> closes #203 
DIA contract was registered in era 60, but because of bug we were trying to claim older eras. 
**Check list**
**Fixes**
- invalid eras to claim calculation.
> Unclaimed eras calculation fix

- src/components/balance/modals/ModalAccount.vue
* Display messages whenever the user connects Mathwallet(browser extension) on networks other than Shiden network
=Before=
Gif:
https://gyazo.com/64b2a6dd62d1151526bb28ce0807721a
=After=
Gif:
https://gyazo.com/d37a5bd95c9acebd7c56214b232771e6
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
> fix: display messages whenever the user connects mathwallet on networks other than Shiden network

- src/components/balance/BalancePlasm.vue
- src/components/balance/PlmBalance.vue
- src/components/balance/modals/ModalFaucet.vue
- src/hooks/useFaucet.ts
Invoke the faucet GET request once user has clicked faucet button (call the request from modal).  It will reduce the GET request to Heroku server.
**Check list**
**Changes**
=Before=
=After=
> fix: call the faucet HTTP request from faucet modal

- quasar.conf.js
- src/index.template.html
> This PR adds Google Analytics to the portal
Two GA profiles are created, one for development and another one for production
**Check list**
**Adds**
- Google analytice
> Add Google analytics

- src/components/dapp-staking/modals/RegisterDappMedia.vue
Sometimes it happens that video is not displayed in dapp details dialog. I believe the main reason for that is we are accessing the portal over https and then trying to access video over http. 
**Check list**
**Fixes**
- dapp info video url
**To-dos**
> update firebase videos url to use ssl
> Dapp video url fix

- src/components/balance/modals/ModalVestingInfo.vue
* fixed styling in vesting info modal for mobile screen size
(FYI @bobo-k2 )
**Check list**
**Fixes**
Before:
After:
> fix: styling in vesting info modal for mobile screen size

- src/store/dapp-staking/actions.ts
Fix for invalid eras to claim calculation
Test env: https://deploy-preview-pr-265.herokuapp.com/#/dapp-staking/discover
Ticket: https://www.notion.so/staketechnologies/Error-with-Unbonding-Claim-unclaimed-era-display-083e42aa36e84571b69d860f6fba2f57
**Check list**
**Fixes**
- eras to claim calculation
> Eras to claim fix

- src/components/header/modals/ModalAccount.vue
- src/components/header/modals/ModalConnectWallet.vue
- src/components/header/modals/ModalNetwork.vue
- src/components/header/modals/SelectWallet.vue
- src/components/sidenav/SidebarDesktop.vue
- src/components/sidenav/SidebarMobile.vue
- src/css/app.scss
- src/css/astar-ui.scss
- src/css/modal.scss
- src/css/utils.scss
* Padding of the "Select a wallet" and "Wallet" modal 
* ref: https://github.com/AstarNetwork/astar-apps/pull/297#issuecomment-1081887070
* Size of the wallet logo
* Padding-left of the wallet row 
* Adjusted modal title (y direction) 
* Converted px to rem by scss function
**Check list**
=Before=
=After=
> fix: modal padding

- src/components/header/modals/ModalAccount.vue
- src/components/header/modals/ModalConnectWallet.vue
- src/components/header/modals/SelectWallet.vue
* Fixed hovering and not hovering effect
* Ref: https://github.com/AstarNetwork/astar-apps/pull/297#issuecomment-1081796506
* Adjusted max-height in `list--account` class
=Before=
The elements in the box moved whenever users have hovered on the element.
https://user-images.githubusercontent.com/92044428/160758292-92de089d-da7c-46db-8e82-196b3b154acc.mov
=After=
https://user-images.githubusercontent.com/92044428/160758399-51f03709-a9fc-4e74-b2b7-f6b19f071a7c.mov
=Before=
=After=
**Check list**
> fix: hovering effect

- src/components/header/Header.vue
- src/components/header/modals/ModalAccount.vue
- src/components/header/modals/SelectWallet.vue
- src/components/header/modals/SelectWalletOption.vue
- src/hooks/useAccount.ts
- src/hooks/useBalance.ts
- src/hooks/useConnectWallet.ts
* Change the account rather than disconnect the wallet
* Ref: https://github.com/AstarNetwork/astar-apps/pull/297#issuecomment-1081390410
> The current behaviour on the staging is - when you want to switch the wallet and click the header button you'll get disconnected but I would like to fix. The whole idea is to be able to feel to switch without disconnecting. To be able to this so, we need the wallet select area in the design (1) Can we do this?
* Enable `Connect` button whenever users have selected account
* Remember selected wallet account via local storage
=Before=
https://gyazo.com/6c0481ea04826de4f62aa089bff54317
=After=
https://gyazo.com/f58cceb4fca2cda94d692115aed884a8
**Check list**
> fix: change account

- src/components/header/MetaUpdateButton.vue
- src/hooks/useBalance.ts
- src/hooks/useMetaExtensions.ts
Display the `Upgrade Metadata` button for wallets that are upgradable only. Ignore wallets (such as talisman and mathwallet) that don't have version data. Otherwise the portal displays the `Upgrade Metadata` button whenever the app is launched.
=Before=
https://www.loom.com/share/77f04c7232bf482291da4889949ca5fb
**Check list**
> fix: updata metadata

- src/components/assets/modals/ModalSelectAccount.vue
- src/components/assets/modals/ModalTransfer.vue
- src/components/assets/styles/modal-transfer.scss
- src/config/web3/index.ts
- src/hooks/index.ts
- src/hooks/useAccount.ts
- src/hooks/useConnectWallet.ts
- src/hooks/wallet/useEvmWallet.ts
- src/i18n/en-US/index.ts
* added placeholder to the destination address input
* disabled transfer button whenever EVM wallet connects to the wrong network
* refactored the function names for `watchEffect` in `useConnectWallet.ts`
* changed the connected account whenever users changed account in the EVM wallet
* issue: https://github.com/AstarNetwork/astar-apps/issues/268
* @bobo-k2 @hoonsubin I've fixed this issue in [this](https://github.com/AstarNetwork/astar-apps/pull/321/commits/62955afa29137082fac86403a7dc6448911d2e0b) commit while refactoring `useConnectWallet.ts`
* Gif: https://gyazo.com/f639bcf4f70c57b72beafc0efeeb892e
**Check list**
**Changes**
Gif: https://gyazo.com/865f7dc905b9a652dbea83249b5a4753
> fix: disable transfer button whenever EVM wallet connects to the wrong network

- src/components/sidenav/SidebarDesktop.vue
- src/components/sidenav/SidebarMobile.vue
- src/components/sidenav/styles/sidebar-desktop.scss
- src/components/sidenav/styles/sidebar-mobile.scss
* added sidebar animation
* added missing `bridge`tab in the navigation tabs
**Check list**
**Changes**
=Sidebar=
Before: https://gyazo.com/64126bce30617d14aaa33511dab10d72
After: https://gyazo.com/54a5efe2675c49cd61438adef162a6e7
**Fix**
=Navigation tabs=
Before
After
> feat: added sidebar animation

- src/components/sidenav/SidebarDesktop.vue
- src/components/sidenav/styles/sidebar-desktop.scss
* Modified `z-index` in the sidebar (the sidebar class used `z-index` and `postion: absolute` to control the animated indicator, but it conflicted with the modal background)
**Check list**
**Fixes**
Before:
After:
> fix: z-index bug in sidebar

- src/components/dapp-staking/modals/ModalDappDetails.vue
- src/components/dapp-staking/modals/RegisterDappMedia.vue
Made videoUrl optional in dapp registration
**Check list**
**Changes**
- updated dapp registration form to allow empty video url
- updated dapp info dialog to hide video carousel slide if the url is empty
> Video url optional in dapp registration

- src/components/dapp-staking/DiscoverDappsTab.vue
- src/store/dapp-staking/actions.ts
After runtime upgrade Astar (and all other networks) has palletDisabled storage item, so maintenance mode will be automatically tracked based on the item value.
**Check list**
> Use palletDisabled storage item

- src/components/dapp-staking/StakePanel.vue
As @fiexer asked removed number of stakers progress bar for dapp
BEFORE
AFTER
**Check list**
> Removed number of stakers progress bar

- src/components/dapp-staking/Dapp.vue
- src/components/dapp-staking/modals/ModalDappDetails.vue
Change the way how images are displayed in dapp info dialog
BEFORE
AFTER
Removed Markup characters (*, #) from dapp panel.
I think we should have a separate database filed for short description
BEFORE
AFTER
**Check list**
> Image size fix, clean markup

- src/components/dashboard/ChartPanel.vue
- src/components/dashboard/Dashboard.vue
- src/components/dashboard/TvlChart.vue
- src/components/dashboard/styles/chart-panel.scss
- src/hooks/useTvlHistorical.ts
- src/i18n/en-US/index.ts
- src/modules/dapp-staking/index.ts
- src/modules/dapp-staking/utils/index.ts
* added the total number of dapp staking stakers on the dashboard page
**Check list**
**Adds**
**To-dos**
It takes a while to return the promise (10 ~ 15 secs) in [this](https://github.com/AstarNetwork/astar-apps/blob/b13cb55c7c69b9fae741544c07d914fad2a70244/src/modules/dapp-staking/utils/index.ts#L7) function. We can cache the result and query via Token-API in the future.
> feat: added stakers number on the dashboard page

- src/components/dapp-staking/StakePanel.vue
- src/components/dapp-staking/statistics/Withdraw.vue
- src/store/dapp-staking/actions.ts
The following error happened to all users trying to withdraw unbondend tokens with their lockdrop account
I was able to reproduce error on Shibuya. Also I tested fix on Shibuya and worked for me. Test env Mac/Chrome/Metamask
**Check list**
**Fixes**
- unbonding for lockdrop participants
> Withdraw feature fix

- src/components/dapp-staking/ClaimAll.vue
- src/hooks/custom-signature/message.ts
- src/i18n/en-US/index.ts
Claim reward button is visible no matter of compounding status.
If user claim rewards when compounding is on, rewards are added to balance and restaked.
If user claim rewards when compounding is off, rewards are only added to balance.
@Dinonard  please check the above statement
**Check list**
**Changes**
- claim button visibility doesn't depend on compounding status.
> Enable claim reward when compounding is on.

- src/components/dapp-staking/styles/user-rewards-widget.scss
- src/hooks/helper/claim.ts
- src/i18n/en-US/index.ts
This bug was caused because era number was converted to string and handled as such in getNumberOfUnclaimedEra.
When era was above 1000 it was formatted like '1,000' which caused math operations to return NaN.
**Check list**
> Claim all disabled when claimable awards available

- src/config/api/polkadot/connectApi.ts
- src/hooks/helper/common.ts
- src/hooks/helper/wallet.ts
* fix: connecting wallet using Firefox 
**Check list**
**Fixes**
Firefox takes some time to load the wallet extensions at the boot time.
=Before=
=After=
> fix: connecting wallet using firefox

- src/components/assets/Assets.vue
- src/components/assets/styles/assets.scss
- src/hooks/c-bridge/useCbridgeV2.ts
* fix: make the XCM section higher than the assets section
* styling: modified the gap (height) between panels on the assets page
fix: prevents an endless loop while calculating the ERC20 token amount (for the users who haven't held any ERC20 token)
**Check list**
**Fixes**
* fix: prevents an endless loop while calculating the ERC20 token amount (for the users who haven't held any ERC20 token)
> fix: make the XCM section higher than the assets section

- src/modules/gas-api/index.ts
- src/modules/gas-api/utils/index.spec.ts
- src/modules/gas-api/utils/index.ts
* refactor: fetch the native tip data from the `tip` property rather than calculating by the portal
**Check list**
**Fixes**
* refactor: fetch the native tip data from the tip property rather than calculating by the portal
> refactor: fetch the native tip data from the 'tip' property rather than calculating by the portal

- src/components/assets/modals/ModalXcmBridge.vue
- src/hooks/xcm/useXcmBridge.ts
* reverse the position of XCM destination tab
* make `Deposit to EVM` the default option
**Check list**
**Changes**
=Before=
=After=
> fix: reverse the position of XCM destination tab

- src/hooks/xcm/useXcmBridge.ts
- src/modules/xcm/index.ts
- src/modules/xcm/utils/index.ts
* feat: leaving safe amount (existential deposit * 1.1) in relaychain after XCM transfer
* ticket: https://www.notion.so/astarnetwork/a5eb9f984d7747a8bad9589fa557dad3?v=d3fc363160a94f66af95f07fc86d6b04&p=06f73d0ab0294e3d84fe5111ad86c264   
**Check list**
Relaychain Balance - amount (1.401 - 0.3) > ED * 1.1 (1.1 for DOT)
> feat: leaving safe amount (existential deposit * 1.1) in relaychain after XCM transfer

- src/boot/api.ts
* fix: displaying duplicated account when the account has been imported to more than 2 wallets
*  issue: https://github.com/AstarNetwork/astar-apps/issues/360 
*  CC: @fiexer  
**Check list**
**Fix**
=Before=
`keyring.accounts.subject.subscribe` overwrites duplicated wallet addresses by default.
> fix: displaying duplicated account when the account has been imported to more than 2 wallets

- src/hooks/custom-signature/useEvmAccount.ts
* fix: avoid calling the EVM wallet's `eventListener`(removeListener) in development mode
* fix: avoid falling into infinite loop after hot reloading 
* ref: `removeListener` was added in this PR. https://github.com/AstarNetwork/astar-apps/pull/450 CC:  @pedroapfilho  @0xKheops 
**Check list**
**Changes**
=Before=
It causes a lot of errors such as `Invalid JSON RPC response` after hot reloading because watchers keep connecting to the RPC server like an infinite loop.
> fix: avoid calling unnecessary `watchers` way too much after `hot reloading`

- src/components/assets/Assets.vue
* fix: get `XCM assets` in H160 mode
**Check list**
**Fixes**
=Before=
This value returns an empty array in H160 mode.
=After=
> fix: get XCM assets in H160 mode

- src/components/assets/modals/ModalVesting.vue
- src/hooks/useConnectWallet.ts
- src/i18n/en-US/index.ts
* fix: typo in ModalVesting
* fix: displays accounts menu for users who visit the portal first time 
**Check list**
**Fixes**
=Before=
=After=
* fix: displays accounts menu for users who visit the portal first time (after approving portal to access substrate wallets extension)
> fix: typo in ModalVesting

- src/components/dapp-staking/StakePanel.vue
- src/components/dapp-staking/modals/StakeModal.vue
- src/hooks/store/index.ts
- src/i18n/en-US/index.ts
Fix for issue #284 
Changed un-bonding dialog to show warning if all funds will be un-bonded
Display actually un-bonded amount in popup
Although user entered 4 SBY, 6 SBY are actually un-bonded 
**Check list**
**Fixes**
- Fixed un-bonded amount display 
Closes #284
> Incorrect unbonding amount displayed fix

- src/components/assets/Erc20Currency.vue
- src/components/assets/modals/ModalXcmBridge.vue
- src/i18n/en-US/index.ts
* feat: enabled EVM withdrawal for Acala tokens.  [Ref](https://stakesg.slack.com/archives/C03BN19LBQ8/p1658136783723779?thread_ts=1656938315.093039&cid=C03BN19LBQ8)
* Memo: EVM withdrawal for MOVR will be enabled after 11th Aug. [Ref](https://stakesg.slack.com/archives/C03BN19LBQ8/p1659955657211789?thread_ts=1656938315.093039&cid=C03BN19LBQ8) 
* fix: added a warning message on the XCM modal [Ref](https://stakesg.slack.com/archives/C028H2ZSGRK/p1659890530632729)
**Check list**
**Adds**
* fix: added a warning message on the XCM modal
> feat: enabled EVM withdrawal for Acala tokens

- src/components/assets/modals/ModalXcmBridge.vue
- src/hooks/xcm/SubstrateApi.ts
- src/hooks/xcm/useXcmBridge.ts
- src/modules/xcm/index.ts
- src/modules/xcm/tokens/index.ts
* fix: modified ED check (native token balance in origin chain) for EVM withdrawal for XCM assets
* fix: updated `minBridgeAmount` for AUSD and KAR token because the amount should be more than ED (Acala tokens have ED in each XCM assets )
*  ref: https://wiki.acala.network/get-started/acala-network/acala-account 
* fix: removed `MOONBEAM` option from XCM transfer UI in ASTR
**Check list**
**Fixes**
* fix: modified ED check (native token balance in origin chain) for EVM withdrawal for XCM assets
Account's native token balance: [0.2ACA](https://acala.subscan.io/account/24Y913oKBCBpPP3q8RLbDCBoZMxneU5VSnWHHkYVRH2cEnvq) 
=Before=
=After=
* fix: removed `MOONBEAM` option from XCM transfer UI in ASTR
=Before=
=After=
> fix: modified ED check in EVM withdrawal for XCM assets

- rpc-tests/config.js
This fixes rpc tests. parachain-id is not default anymore with new release of astar. Needs to be added manually.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
> Added parachain id as it is not default anymore

- src/components/common/Modal.vue
- src/components/dapp-staking/StakePanel.vue
- src/components/dapp-staking/modals/StakeModal.vue
- src/hooks/helper/plasmUtils.ts
- src/hooks/store/index.ts
- src/hooks/transfer/useTransfer.ts
* fix: modified parsing the amount logic (to 18 decimals)  for native currencies
* background: some users raised an issue that the inputted amount cannot be parsed in the previous logic (an error occurred in [this line](https://github.com/AstarNetwork/astar-apps/pull/484/files#diff-7d03b3d5759663bb88b973c203ac29c7fbd54d7ed2c54da3e148304f4d999e41L90)), since I cannot reproduce the error, I've used the standard parsing function that is exported from the library to resolve the issue. Also, I reduced the "Decimals" parameter since the function is used only for the native currencies (decimals: 18).
* ref: 
* https://stakesg.slack.com/archives/C028H2ZSGRK/p1660521841022289
* https://stakesg.slack.com/archives/C028H2ZSGRK/p1660274418396239 
* fix: modified an z-index …
> fix: modified parsing amount logic for the native currencies

- src/components/dapp-staking/StakePanel.vue
- src/hooks/dapps-staking/useStakerInfo.ts
- src/modules/dapp-staking/index.ts
- src/modules/dapp-staking/utils/index.ts
* fix: slow down the fetching data on Staking page (only for Onfinality)
Since Onfinality has set the limit (100requests / sec) for sending requests from the browser, I've changed the way of querying API  in sequence instead of parallel if users selected Onfinality.
* feat: added skeleton on the StakePanel
* gif: https://gyazo.com/659cf9e4f26b5b9db3020d401395b3a1  
**Check list**
> fix: slow down the fetching staking data for onfinality

- src/components/common/Modal.vue
* fix: avoid closing the 'dapp register modal' whenever users click inside of modal
**Check list**
=Before=
https://gyazo.com/e50e2c4a392ac7615197d502dd0ae253
=After=
https://gyazo.com/8fb54745b61c5b64027c0e51211b7bd4
> fix: display the 'dapp register modal' properly

- src/components/common/CookiePolicy.vue
* fix: modified `z-index` in CookiePolicy.vue, so that the side drawer won't be removed after users click on the Cookie Policy panel
Before: https://gyazo.com/ed428db65c58340e39bd804c65f64538
After: https://gyazo.com/1347ac7459749d030b947b69bda44f16
**Check list**
> fix: modified `z-index` in CooKiePolicy.vue

- src/components/dapp-staking/dapp/Dapp.vue
- src/components/dapp-staking/dapp/DappAvatar.vue
- src/components/dapp-staking/dapp/DappImages.vue
- src/hooks/useClaimAll.ts
- src/store/dapp-staking/getters.ts
- src/v2/components/dapp-staking/DappCard.vue
- src/v2/components/dapp-staking/DappsList.vue
- src/v2/repositories/implementations/DappStakingRepository.ts
* fix: Enables 'Edit' button to developer account only
* fix: Display dApps whenever users use EVM wallets to connect to the portal
* fix: Display dApps whenever users select Shiden or Shibuya networks 
**Check list**
**Changes**
fix: Display dApps whenever users select Shiden or Shibuya networks
* Shiden
=Before=
=After=
* When users connect to EVM wallets
=Before=
=After=
* Enables 'Edit' button to developer account only
> feat: Display dApps whenever users select Shiden or Shibuya networks

- src/components/dapp-staking-v2/StakingTop.vue
- src/components/dapp-staking-v2/my-staking/DappList.vue
- src/store/dapp-staking/getters.ts
Implemented filtering dapps by mainCategory property. Since this is the v2 property current dapps are categorized as Others since they don't have the property set yet. After projects update their dapps with category info dapps will be categorized properly.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
> Filter dapps by mainCategory

- src/components/dapp-staking-v2/my-staking/MyStaking.vue
- src/components/dapp-staking-v2/my-staking/styles/my-staking.scss
* fix: modified tabs styling on the `MyStaking` panel for mobile devices
**Check list**
**Fixes**
* fix: modified tabs styling on the `MyStaking` panel for mobile devices
=Before=
=After=
> fix: modified tabs styling on the `MyStaking` panel for mobile devices

- src/components/dapp-staking-v2/my-staking/MyDapps.vue
- src/components/dapp-staking-v2/my-staking/UnbondingList.vue
I found that there's z-index problem between modal and loading indicator. we need resolve it later.
but for now, while transaction on the modal, loading indicator is not visible. because z-index of modal  is more higher than loading indicator one. so to visible loading indicator, opened hot fix for this.
> Hotfix - loading indicator not visible when modal opens up

- src/components/dapp-staking/dapp/Dapp.vue
- src/components/dapp-staking/stake-manage/StakeManage.vue
- src/hooks/dapps-staking/useDappRedirect.ts
- src/hooks/dapps-staking/useStake.ts
- src/hooks/dapps-staking/useUnbonding.ts
- src/hooks/index.ts
- src/hooks/useClaimAll.ts
- src/v2/repositories/implementations/DappStakingRepository.ts
- src/v2/services/implementations/PolkadotWalletService.ts
* fix: navigate the URL to the 'dApp staking page' after staking transaction has been completed 
*  avoid navigating to the 'dApp staking page' if users have go to other pages before staking transaction has been completed 
* fix: modified an error at DappStakingService.ts
* fix: removed unused console.log
* fix: added redirect logic on the staking and dApp page
**Check list**
**Fixes**
* fix: navigate the URL to the 'dApp staking page' after staking transaction has been completed 
*  avoid navigating to the 'dApp staking page' if users have go to other pages before staking transaction has been completed 
=Before=
https://www.loom.com/share/6e274c60f24746b6a856f51fc94d2e62
=After= …
> fix: navigate the URL to the 'dApp staking page' after staking transaction has been completed

- src/components/assets/transfer/Transfer.vue
* fix: added Acala into the selecting chain list
**Check list**
**Fixes**
=Before=
=After=
> feat: added Acala into the selecting chain list

- src/components/dapp-staking/register/Builders.vue
- src/components/dapp-staking/register/ModalAddDeveloper.vue
- src/i18n/en-US/index.ts
Fix for a bug in registration page when user was able to give the same name to multiple developers. Since name is the key for search when updating developers, this caused issue with overriding data of other developer and some other problems.
I believe this caused yesterday's issue with XY finance registration.
**Check list**
> Developer unique name check

- src/components/assets/styles/asset-list-xcm.scss
- src/components/assets/styles/asset-list.scss
- src/modules/xcm/utils/index.ts
* fix: modified row styling for 'Crust Shadow Native Token'
* fix: cast the network name from 'Crust-shadow' to 'Crust Shadow' (for UI)
**Check list**
**Fixes**
* fix: modified row styling for 'Crust Shadow Native Token'
=Before=
=After=
* fix: cast the network name from 'Crust-shadow' to 'Crust Shadow' (for UI)
=Before=
=After=
> fix: modified stylings for Crust integration

- src/hooks/useClaimAll.ts
- src/v2/models/DappsStaking.ts
- src/v2/repositories/implementations/DappStakingRepository.ts
In a situation when staked array size reach `maxEraStakeValues` (currently set to 5) users are unable to clam their reward if auto restaking is on.
Changed logic to turn off auto restaking before claim and turn it on after rewards are claimed.
**Check list**
**Fixes**
- Claim error
> Temporary disable auto restaking on claim all

- src/components/dapp-staking-v2/stake-manage/StakeManage.vue
* fix: temporary hide the Recent History UI (dApp staking V2.1)
**Check list**
**Fixes**
=Before=
=After=
> fix: temporary disabled staking-historic-UI

- src/hooks/dapps-staking/useCompoundRewards.ts
Something re-stake after claiming was displayed wrong. Although re-stake was enabled on chain, portal was showing off status.
**Check list**
> Re-stake status display fix

- src/components/dapp-staking-v2/my-staking/TopMetric.vue
- src/hooks/index.ts
- src/hooks/useAprFromApi.ts
- src/v2/repositories/IDappStakingRepository.ts
- src/v2/repositories/implementations/DappStakingRepository.ts
- src/v2/test/mocks/repositories/DappStakingRepositoryMock.ts
Because of an [issue](https://github.com/paritytech/smoldot/issues/1925) we are facing while calculating APR/APY over light client I changed code to switch those values from Token API. 
**Check list**
> Fetch APR/APY from Token API

- src/components/header/modals/ModalNetwork.vue
- src/config/api/polkadot/connectApi.ts
* fix: enables `light client` endpoint option (for Astar and Shiden) for localhost or staging url only ([ref](https://github.com/AstarNetwork/astar-apps/blob/238668c36ad7550efea67074ecad45ecb1529910/src/components/header/modals/ModalNetwork.vue#L260))
* Shibuya: enabled in any URLs  
**Check list**
**Fixes**
* fix: enables `light client` endpoint option for localhost or staging url only ([ref](https://github.com/AstarNetwork/astar-apps/blob/238668c36ad7550efea67074ecad45ecb1529910/src/components/header/modals/ModalNetwork.vue#L260))
```
// Memo: Displays Light client option if:
// A: users select Shibuya
// B: the portal is opened on 'localhost' or 'staging URL'
```
=Staging URL / localhost=
=Production (assume …
> fix: enables `light client` endpoint option for localhost or staging url

- src/hooks/dapps-staking/useStakerInfo.ts
* fix: modified fetching 'My staking information' logic when users change their account
**Check list**
**Fixes**
* fix: modified fetching 'My staking information' logic when users change their account
* to avoid throwing this error
> fix: modified fetching 'My staking information' logic when users change their account

- src/hooks/helper/claim.ts
- src/hooks/useClaimAll.ts
Because of weights V2 are introduced to Shibuya and Shiden claim feature stopped working.
**Check list**
- Fix for Claim All error
> Claim issue fix

- src/components/common/Notification/NotificationStack.vue
- src/components/dapp-staking/StakingTop.vue
- src/components/dapp-staking/dapp/Dapp.vue
- src/components/dapp-staking/dapp/DappAvatar.vue
- src/components/dapp-staking/my-staking/MyRewards.vue
- src/components/dapp-staking/my-staking/components/CardList.vue
- src/components/dapp-staking/stake-manage/StakeManage.vue
- src/hooks/dapps-staking/useStakerInfo.ts
When connected to the portal with Metamask and open dapp staking pake three warnings pops showing that dapp staking supports Substrate wallets. After clicking on X (to close popup) another one shows. 
Before
After
**Check list**
- fix for displaying multiple warning on dapp staking page when connected with Metamask
> Multiple popups on dapp staking fix

- src/components/header/modals/ModalNetwork.vue
- src/components/header/styles/modal-network.scss
- src/i18n/en-US/index.ts
* fix: modified styling in the light client warning section for light theme
* fix: avoids selecting the Light client endpoint randomly
**Check list**
* fix: modified styling in the light client warning section for light theme
**Fixes**
* fix: modified styling in the light client warning section for light theme
* fixed a bug that some CSS classes didn't work properly on the component
=Before=
=After=
> fix: modified styling in the light client warning section for light theme

- src/components/common/Notification/NotificationBar.vue
Add support for [Shibuya Subscan](https://shibuya.subscan.io/) explorer link in success tx toast.
Currently, when clicking on "Check your transactions" in TX Success toast, it opens up `astar.subscan.io` instead of `shibuya.subscan.io` 
PS: not able to test due to captcha fails in localhost
**Check list**
- feat: add support for shibuya subscan links in tx success toast
**Adds**
- Add support for shibuya subcan in success tx toast.
> feat: add support for shibuya subscan link in tx toast

- src/components/dapp-staking/stake-manage/StakeForm.vue
- src/components/dapp-staking/stake-manage/StakeManage.vue
- src/components/dapp-staking/stake-manage/styles/stake-form.scss
- src/hooks/dapps-staking/useStake.ts
- src/hooks/useClaimAll.ts
- src/i18n/en-US/index.ts
Improve “claim and restake”
- Add message on the warning notification to clarify when transferable balance doesn’t have enough balance to make claims. Invalid balance to make a claim. Please add ASTR tokens in to the account.
- When users select “Max” leave `10ASTR` in the account so it will keep the balance for longer period.
- Add message before the confirm button on Staking page `Account must hold greater than 10ASTR in transferrable when you stake.`
**Check list**
fix: claim and restake issues
> Improve “claim and restake”

- src/components/dapp-staking/register/RegisterDapp.vue
- src/components/dapp-staking/register/components/Builders.vue
- src/components/dapp-staking/register/components/Community.vue
- src/components/dapp-staking/register/components/DappImages.vue
- src/components/dapp-staking/register/components/ModalAddDeveloper.vue
- src/i18n/en-US/index.ts
* fix: avoid browsers be crashed when users update the images
* feat: added maximum file size text
**Check list**
* fix: avoid browsers be crashed when users update the images
**Fixes**
* fix: avoid browsers be crashed when users update the images
* demo: https://www.loom.com/share/18766218a15e40b2a965eb3b622219b9  
* feat: added maximum file size text
> fix: avoid browsers be crashed when users update the images

- src/components/assets/transfer/Transfer.vue
- src/hooks/xcm/useTransferRouter.ts
- src/links/index.ts
* feat: disabled XCM transafer with Kusama parachains
* disables the XCM transfer with Kusama parachains as Kusama is going to upgrade to XCM V3 on 4-Apr
* disables the XCM transfer at production URL (https://portal.astar.network/shiden) only. Anyone still can test it at the staging URL 
**To-dos**
* Merge this PR and update the production page on 3-Apr
**Check list**
* feat: disables XCM transafer with Kusama parachains
**Changes**
> feat: disabled XCM transfer with Kusama parachains

- src/hooks/useAppRouter.ts
* fix: avoid loading the portal twice on the first visit
**Check list**
* fix: avoid loading the portal twice on the first visit
**Fixes**
=Before=
https://i.gyazo.com/adce398cda4191f9ff655c9d0e73ea6c.mp4
=After=
https://www.loom.com/share/881347f0e2a74cd89fd8ee8a7109aef2
> fix: avoid loading the portal twice on the first visit

- src/hooks/xcm/useTransferRouter.ts
- src/v2/repositories/implementations/xcm/PhalaXcmRepository.ts
Phala and Khala cross-chain transfer update
**Check list**
**Changes**
- Update `PhalaXcmRepository`
- Re-enable Phala and Khala cross-chain transfer
> feat: phala xcm update

- src/hooks/useClaimAll.ts
- src/hooks/useConnectWallet.ts
This PR is to fix issue with using dApps staking with lockdrop accounts.
The root cause of the issue is that `currentAddress` is incorrectly set. `currentAddress` should have the same value as `ss58` field (edited) 
I disabled setting 'Ethereum Extension' value to the `currentAddress` field. I am not sure why we are storing such invalid value to Vuex. Also, not sure if this change breaks something else, so serious testing is required.
**Check list**
- Fixed dApps staking not working with Lockdrop accounts issue.
> Don't set Ethereum Extension value to currentAddress field

- src/i18n/en-US/index.ts
Updated claim tooltip text to be less confusing. Please comment if you find it more confusing now :)
Actually, information about 50 eras claimed in one batch is incorrect. We are filling claim batch until some weight is reached. Number of transaction per batch depends on transactions weight and it varies.
Related to #742 
**Check list**
- Claim reward tooltip message update
> Fixed claim tooltip text

- src/components/dapp-staking/my-staking/TopMetric.vue
Fix for invalid number of dApps displayed on the portal. The problem was that unregistered dApps were also counted.
BEFORE
AFTER
**Check list**
- Fix: invalid total number of dApps shown on dApps staking page
> Fix total dApps count

- src/v2/repositories/implementations/xcm/InterlayXcmRepository.ts
> Use XcmV2WeightLimit format for Interlay xcm transfers.
**Check list**
- fix: use XcmV2WeightLimit in for Interlay XCM transfers 
**Fixes**
- Fixes the XCM error users see when they try to submit an `xTokens.transfer` extrinsic
> Fix: Use XcmV2WeightLimit in InterlayXcmRepository.ts

- src/components/dapp-staking/my-staking/MyStaking.vue
* fix: reset the staking tab to 'My Rewards' after changing accounts 
**Check list**
**Fixes**
fix: reset the staking tab to 'My Rewards' after changing accounts 
=Before=
https://gyazo.com/1fa36591449cfe8771b840f9b4293625
=After=
https://gyazo.com/0318d83049a8a712145ca876a11c7efa
> fix: reset the staking tab to 'My Rewards' after changing accounts 

- src/hooks/dapps-staking/useUnbond.ts
- src/hooks/dapps-staking/useUnbonding.ts
The portal doesn’t show Unbonding tab after sending unbond transactions.
**Check list**
https://github.com/AstarNetwork/astar-apps/assets/1606820/1252357d-8267-4a3d-81c6-b509b66432de
> Fix unbonding tab shown after unbonded transactions

- src/modules/dapp-staking/utils/index.ts
* fix: resolved “Rate limit reached” error on blast
*  'Rate limit reached' error occurs when users select 'Blast' on the dApp staking page.
**Check list**
**Fixes**
=Before=
=After=
> fix: resolved “Rate limit reached” error when users select 'Blast' on the dApp staking page

- src/data/dynamic_links.json
Remove the subtitle “portal is now on IPFS” from a banner on Asset page
| BEFORE | AFTER |
|---------|---------|
|<img width="310" alt="Screenshot 2023-07-13 at 9 27 18 AM" src="https://github.com/AstarNetwork/astar-apps/assets/33358068/a968fff5-206e-41f2-ba87-c2d753d5c6c2">|<img width="313" alt="Screenshot 2023-07-13 at 9 26 52 AM" src="https://github.com/AstarNetwork/astar-apps/assets/33358068/56d2c3e7-17fa-41d0-990e-adbd0dad1316">|
**Check list**
**Changes**
- Only changed src/data/dynamic_links.json file
> Remove the subtitle from IPFS banner

- .github/workflows/pull-request-preview.yml
Because PRs created with Dependabot doesn't have access to GH secrets
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/ 
**Check list**
> PR Action trigger changed

- src/v2/repositories/implementations/XcmRepository.ts
- src/v2/repositories/implementations/xcm/AstarXcmRepository.ts
* feat: uses 'xtokens' module for XCM transfer on Shiden
* Existing `polkadotXcm` pallet will be deprecated 
*  Astar runtime will come later 
* Transaction results (all good): https://docs.google.com/spreadsheets/d/1jmTF4VUVSeELAAMGdOrx72Rmc27jlVPxdGpdvCSXy2E/edit#gid=1903892362 
**Check list**
> feat: uses 'xtokens' for XCM transfer on Shiden

- src/components/header/modals/ModalAccount.vue
- src/components/header/modals/ModalConnectWallet.vue
* fix: display select-able account on ‘Account Drawer’ after granting authorisation on wallet extensions(for first time visitors)
* removed duplicated `requestExtensionsIfFirstAccess` function which is the same function called in another hooks prior to open`ModalAccount.ts`   
**Check list**
**Fixes**
=Before=
=After=
> fix: display select-able account on ‘Account Drawer’ after granting authorisation on wallet extensions

- src/modules/playwright/index.ts
- tests/test_specs/dappstaking-register.spec.ts
- tests/test_specs/dappstaking-transactions.spec.ts
- tests/test_specs/dappstaking.spec.ts
…odal (#897)
* test: updated clickDisclaimerButton function
* fix dappstaking register (#898)
* Fix/test disclaimer (#899)
* fix dappstaking register
* more disclaimers
---------
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
> bring branch up-to-date

- README.md
- src/boot/api.ts
- src/components/dapp-staking/my-staking/components/modals/ModalUnbondDapp.vue
- src/config/localStorage.ts
- src/i18n/en-US/index.ts
- tests/common-api.ts
- tests/test_specs/dappstaking-transactions.spec.ts
* fix: updated withdrawal UI 
* fix: removed IS_APPLIED_RANDOM_ENDPOINT from local storage
**Check list**
**Changes**
* fix: updated withdrawal UI  
* if the resulting staking amount is lower than minimum staking amount: 
* display a warning message
* unstake all of staked balance
> fix: updated withdrawal UI

- src/components/dapp-staking/my-staking/MyStaking.vue
* hotfix: open My Rewards tab as default for EVM wallets on dApp staking page
**Check list**
**Fixes**
=Before=
=After=
> hotfix: open My Rewards tab as default for EVM wallets on dApp staking page

- src/hooks/custom-signature/message.ts
- src/i18n/en-US/index.ts
- src/i18n/fr/index.ts
- src/i18n/it/index.ts
- src/i18n/ja/index.ts
- src/i18n/kr/index.ts
- src/i18n/pt/index.ts
- tests/common.ts
- tests/test_specs/assets-evm.spec.ts
* fix: updated words in toast after sending withdrawal transaction
**Check list**
=After=
> fix: updated words in toast after sending withdrawal transaction

- src/components/dapp-staking/dapp/Dapp.vue
- src/hooks/dapps-staking/useDispatchGetDapps.ts
- src/store/dapp-staking/actions.ts
- src/store/dapp-staking/mutations.ts
Modified portal use new dapps endpoints. Now portal loading time should be much faster.
BEFORE
- load all dapps with all details from Token API on portal start
- when users clicks a dApp get data from app storage (Vuex)
AFTER
- on portal start load only dApps data required for dapps staking homepage (name, contract address, logo url and main category)
- when user clicks a dApp load complete dapp details from Token API and store details to Vuex
**Check list**
> Dapps loading optimizations

- src/components/assets/Assets.vue
- src/hooks/transfer/useTokenTransfer.ts
- src/hooks/useAccount.ts
- src/store/general/getters.ts
- src/store/general/mutations.ts
- src/store/general/state.ts
- src/v2/app.container.ts
- src/v2/repositories/IIdentityRepository.ts
- src/v2/repositories/INftRepository.ts
- src/v2/repositories/implementations/AccountsRepository.ts
- src/v2/repositories/implementations/IdentityRepository.ts
- src/v2/repositories/implementations/NftRepository.ts
- src/v2/repositories/implementations/index.ts
- src/v2/symbols.ts
- Updated asset transfer logic to send assets to valid EVM account pair (unified SS58 address if account is unified)
- Fix fo getIdentity method in IndetityRepository
- Updated NftRepository to use Token API endpoint
**Check list**
> Native asset transfer support for unified accounts

- src/boot/api.ts
- src/components/header/modals/ModalConnectWallet.vue
- src/config/wallets.ts
- src/hooks/helper/snapUtils.ts
- src/hooks/useAccount.ts
- src/hooks/useConnectWallet.ts
- src/modules/snap/index.ts
- src/v2/services/implementations/PolkadotWalletService.ts
* feat: connect to metamask snap smoothly
* fix: enable metamask snap option only when the users connect to Shibuya 
* fix: moved snap utils to 'snap' module
* fix: updated loading animation condition
**Check list**
> feat: updated UI logic for the MetaMask snap

- src/components/dapp-staking/my-staking/components/banners/Algem.vue
- src/components/dapp-staking/my-staking/components/banners/DeveloperIncentive.vue
- src/components/dapp-staking/my-staking/styles/dynamic-ads-area.scss
The Issue: 
The Fix:
And when there is room, it's just like the old days:
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
> fix: let space wrap and height grow for cards in banner

- src/components/assets/Account.vue
- src/components/header/modals/ModalConnectWallet.vue
- src/components/header/modals/account-unification/AuStep5.vue
- src/hooks/useAccount.ts
- src/hooks/wallet/useAccountUnification.ts
- src/i18n/en-US/index.ts
- src/v2/repositories/implementations/AccountUnificationRepository.ts
* fix: account unification modals
* fix: updated words
* fix: display the 'unify accounts' button only on Shibuya
* fix: updated connecting metamask logic
* feat: added a check input for sending submit transaction
ref: https://github.com/AstarNetwork/astar-apps/pull/925#issuecomment-1744877278  
**Check list**
**Adds**
* feat: added a check input for sending submit transaction
> fix: account unification modals

- src/components/header/modals/ModalConnectWallet.vue
* fix: enables MetaMask snap only in dev mode
*  enables it in production after we published the snapId on npm  
**Check list**
**Changes**
* fix: enables MetaMask snap only in dev mode
↓ in production or staging
> fix: enables MetaMask snap only in dev mode

- src/components/dapp-staking/my-staking/components/NewsArea.vue
- src/hooks/dapps-staking/useDispatchGetDapps.ts
- src/hooks/dapps-staking/useStake.ts
- src/hooks/dapps-staking/useStakingList.ts
* fix: fetch dApps staking data after changing accounts
* fix: page column position
**Check list**
**Fixes**
* fix: fetch dApps staking data after changing accounts
* User's staking data was not updated after changing accounts.
=Before=
`Yyaq...vBMF` has staked on 6 dApps but it can't be found on the 'select' modal (for nomination transfer) 
=After=
* fix: page column position
=Before=
=After=
> fix: fetch dApps staking data after changing accounts

- src/components/assets/transfer/LocalTransfer.vue
- src/config/web3/index.ts
- src/config/web3/utils/index.ts
- src/hooks/transfer/useTokenTransfer.ts
- src/hooks/useGasPrice.ts
- src/v2/repositories/implementations/AssetsRepository.ts
- src/v2/services/IAssetsService.ts
- src/v2/services/implementations/MetamaskWalletService.ts
* fix: disabled transaction speed UI for Shibuya EVM as users can select the speed on their wallet
* we can remove it for Astar and Shinde once rutime apply the dynamic gas price for EVM
* fix: stop fetching gas price if users connect to Shibuya EVM
* fix: removed duplicated fetch gas price logic
* fix: refactored fetching gas price logic by checking the provider's connecting chain ID 
* fix: avoid displaying `insufficient ${token} balance` message at the very first moment when the app render the transfer page 
**Check list**
**Changes**
* fix: disabled transaction speed UI for Shibuya EVM 
=Before=
=After=
* fix: avoid displaying insufficient ${token} balance message at the very first moment when the app displays …
> fix: disabled transaction speed UI for Shibuya EVM

- src/components/assets/transfer/LocalTransfer.vue
- src/config/web3/index.ts
- src/config/web3/utils/index.ts
- src/hooks/transfer/useTokenTransfer.ts
- src/hooks/useGasPrice.ts
- src/v2/app.container.ts
- src/v2/repositories/implementations/AssetsRepository.ts
- src/v2/services/IAssetsService.ts
- src/v2/services/implementations/MetamaskWalletService.ts
Error fix
Also aded a change to use gas price from RPC on Shibuya. JSON-RPC errors shouldn't happen anymore
**Check list**
> Fix for provider not set or invalid error

- src/components/assets/styles/assets.scss
- src/components/bridge/styles/bridge-selection.scss
- src/pages/AssetsPage.vue
> Bridge and assets page styling fixes

- src/hooks/useBalance.ts
We didn't calculated reserved tokens into total balance.
BEFORE
Poladot portal shows 16.67 SBY total balance, while the portal shows 15.67 SBY
NOW
**Check list**
> Fix for invalid total account balance value

- src/components/assets/Account.vue
- src/components/assets/XcmCurrency.vue
- src/components/header/modals/account-unification/AuIcon.vue
- src/hooks/transfer/useTokenTransfer.ts
- src/hooks/useAccount.ts
- src/hooks/wallet/useAccountUnification.ts
- src/hooks/xcm/useXcmBridge.ts
- src/i18n/en-US/index.ts
- src/store/dapp-staking/actions.ts
- src/v2/repositories/IAccountUnificationRepository.ts
- src/v2/repositories/implementations/AccountUnificationRepository.ts
- src/v2/repositories/implementations/AssetsRepository.ts
- src/v2/services/IAccountUnificationService.ts
- src/v2/services/implementations/AccountUnificationService.ts
* fix: displaying account icon
* fix: use unified account
* map to proper SS58 address for EVM dApp staking
* map to proper H160 address for sending assets from EVM to Native(unified)
**Check list**
**Fixes**
* fix: displaying account icon
=Before=
* Not unified account but `isUnifiedAccount` was true
* This is unified account but `AuIcon` component was not imported
=After=
**Changes**
* removed `getSS58Address` function from `useAccount` hooks and use `getMappedNativeAddress` from `AccountUnificationService`
> fix: Account Unification errors

- src/components/dapp-staking/my-staking/components/NewsArea.vue
fix: modified rendering news list
**Check list**
**Fixes**
=Before=
=After=
> fix: modified rendering news list

- src/components/assets/Assets.vue
- src/components/assets/NativeAssetList.vue
- src/components/assets/transfer/LocalTransfer.vue
- src/components/assets/transfer/styles/local-transfer.scss
- src/components/header/modals/ModalConnectWallet.vue
- src/hooks/transfer/useTokenTransfer.ts
- src/hooks/useNetworkInfo.ts
- src/i18n/en-US/index.ts
- yarn.lock
* fix: warning messages in ERC20 token transfer](fix: added warning messages in ERC20 token transfer UI
* fix: wrong validation result
* before: (gif)  https://gyazo.com/d3f8dfad40fa3789687c2c4f69ac0139
* fix: renamed constant name from `isSupportXvmTransfer` to `isSupportAuTransfer` 
**Check list**
**Fixes**
* fix: added warning messages in ERC20 token transfer UI
> fix: added warning messages in ERC20 token transfer UI

- src/components/header/modals/ModalAccount.vue
- src/hooks/transfer/useTokenTransfer.ts
- src/hooks/useAccount.ts
- src/hooks/wallet/useAccountUnification.ts
- src/hooks/xcm/useXcmBridge.ts
- src/v2/repositories/IAccountUnificationRepository.ts
- src/v2/repositories/implementations/AccountUnificationRepository.ts
- src/v2/services/IAccountUnificationService.ts
- src/v2/services/implementations/AccountUnificationService.ts
* fix: modify the way query the mapped address
* reverted both `getMappedEvmAddress` and `getMappedNativeAddress` function
* use `getConvertedNativeAddress` and  `getConvertedEvmAddress` for fetch & calculate the maped address
* fix: modified ModalAcount.vue to update 'currentWallet' state correctly after selecting account   
**Check list**
> fix: modify the way query the mapped address

- src/hooks/dapps-staking/useDispatchGetDapps.ts
- src/store/dapp-staking/actions.ts
* fix: display the staking list for EVM accounts
**Check list**
**Fixes**
* fix: display the staking list for EVM accounts
=Before=
=After=
> fix: display the staking list for EVM accounts

- src/i18n/en-US/index.ts
- src/staking-v3/components/Vote.vue
- src/staking-v3/hooks/useDappStaking.ts
- Fix dictionary of possible pallet errors
- refactor `canConfirm` for voting
**Check list**
> vote and dictionary changes

- src/components/dapp-staking/my-staking/MyRewards.vue
- src/components/header/modals/ModalConnectWallet.vue
- src/hooks/dapps-staking/useDispatchGetDapps.ts
- src/i18n/en-US/index.ts
- src/modules/snap/index.ts
- src/store/dapp-staking/actions.ts
* merge the `release-hotfix` to `main` branch
* https://github.com/AstarNetwork/astar-apps/pull/1024
* https://github.com/AstarNetwork/astar-apps/pull/1027
* https://github.com/AstarNetwork/astar-apps/pull/1028
* https://github.com/AstarNetwork/astar-apps/pull/1030
**Check list**
> merge the `release-hotfix` to `main` branch

- src/components/assets/NativeAssetList.vue
* fix: include vesting amount in locked tokens
**Check list**
> fix: include vesting amount in locked tokens

- src/hooks/wallet/useAccountUnification.ts
- src/v2/services/implementations/MetamaskWalletService.ts
- src/v2/services/implementations/XcmEvmService.ts
A quick and dirty fix to ignpre gas results from gas station since they are too low for Astar.
**Check list**
> Ignore gas station

- package.json
- yarn.lock
* fix: display the amount of estimated rewards for Shibuya
**Check list**
**Fixes**
* fix: display the amount of estimated rewards for Shibuya
=Before=
It was 0
=After=
> fix: display the amount of estimated rewards for Shibuya

- src/hooks/wallet/useAccountUnification.ts
- src/modules/evm/index.ts
- src/v2/services/implementations/MetamaskWalletService.ts
- src/v2/services/implementations/XcmEvmService.ts
While investigating a lot of weird issues related to EVM transactions on Shibuya (`StakingWithNoValue`, `BalanceLow`...) I figured out that there is no need to provide `gasPrice` when calling `eth.estimateGas` which solved all errors.
Also refactored the code a bit to have single place to build EVM transaction (before we have very similar code on 3 different places).
**Changes affect all EVM transactions on all networks so please test carefully the following EVM transaction: token transfer, XCM transfer, dApp staking, account unification XC20 transfer).**
**Check list**
> EVM gas estimation fix

- .eslintignore
- src/staking-v3/components/Vote.vue
- src/staking-v3/components/my-staking/MyDapps.vue
- src/staking-v3/hooks/useDappStaking.ts
- src/staking-v3/hooks/useDappStakingNavigation.ts
- src/staking-v3/logic/services/DappStakingService.ts
- src/staking-v3/logic/services/DappStakingServiceEvm.ts
- tsconfig.json
* feat: updated V3 via EVM logic 
**Check list**
**Adds**
* feat: updated V3 via EVM logic 
**Fixes**
* fix: link to the dapp staking page from the asset page
> feat: updated V3 via EVM logic

- src/components/header/ClaimWarningBanner.vue
- src/components/header/Header.vue
- src/components/header/HeaderComp.vue
- src/i18n/en-US/index.ts
- src/layouts/DashboardLayout.vue
Add the warning banner to make users claim rewards before dApp staking V3 ([ticket](https://www.notion.so/astarnetwork/Kaizen-asset-page-top-banner-9f0b9ed69d95423da726e798a24200a8?pvs=4))
**Check list**
**Adds**
> add claim warning banner

- src/v2/services/implementations/MetamaskWalletService.ts
* hotfix: removed `estimatedGas` variable from `sendEvmTransaction` function
* resolves an error while sending withdrawal transactions 
**Check list**
**Fixes**
=Before=
> hotfix: removed estimatedGas variable from sendEvmTransaction function

- src/i18n/en-US/index.ts
- src/staking-v3/components/my-staking/MigrationSupport.vue
- src/staking-v3/components/my-staking/Staking.vue
Added the migrate support section without logic
**Check list**
**Adds**
> feat: add migrate support style

- src/v2/repositories/implementations/xcm/UniqueXcmRepository.ts
Fix transfer of UNQ from Unique Network to Astar.
**Check list**
**Fixes**
Fixed `xtokens.transfer` currency ID argument.
Here is the link to `astar-apps` with the fix already applied: https://poc-apps.aku.uniquenetwork.dev/astar/assets.
20 UNQ was transferred using the `astar-apps` version from the link above. [Subscan XCM Transfer Info](https://astar.subscan.io/xcm_message/astar-863f1b37b61aa23921ff3b3d2298efc461af352f).
The fix is required following the [v10030070](https://github.com/UniqueNetwork/unique-chain/releases/tag/v10030070) Unique Network upgrade, which uses the collection ID type directly as `CurrencyId`.
The collection ID for the native asset (UNQ) is `0`.
> fix: UNQ transfers from Unique Network to Astar

- src/i18n/en-US/index.ts
- src/staking-v3/components/Dapps.vue
- src/staking-v3/components/ErrorPanel.vue
- src/staking-v3/components/Owner.vue
- src/staking-v3/components/Vote.vue
- src/staking-v3/components/YourRewards.vue
- src/staking-v3/components/dapp/DappBackground.vue
- src/staking-v3/components/dapp/DappV3.vue
- src/staking-v3/components/my-staking/ModalUnbondDapp.vue
- src/staking-v3/components/styles/dapps.scss
- src/staking-v3/components/styles/vote.scss
- src/staking-v3/hooks/useDappStaking.ts
- src/staking-v3/hooks/useDappStakingNavigation.ts
- tests/test_specs/dappstaking-transactions.spec.ts
- Updated canStake and canUnstake methods logic and Vote/Unstake components to display errors to an user.
- Enable opening a dApp page in a new tab
- Show number of unclaimed eras on dApp owner page
**Check list**
> Display stake/unstake errors

- src/components/assets/styles/account.scss
- src/components/dapp-staking/StakingTop.vue
- src/components/header/ClaimWarningBanner.vue
- src/components/header/Header.vue
- src/layouts/DashboardLayout.vue
Fixed the claim warning banner covering the account area on the mobile screen size.
**Check list**
**Changes**
|Before|After|
|-|-|
|<img width="407" alt="Screenshot 2024-01-16 at 11 39 16 AM" src="https://github.com/AstarNetwork/astar-apps/assets/33358068/6239a84e-653e-4b12-a4ce-eb89ad0aecfb">|<img width="414" alt="Screenshot 2024-01-16 at 11 38 08 AM" src="https://github.com/AstarNetwork/astar-apps/assets/33358068/e4fb6665-773b-46e3-9507-e5c5353b4a3e">|
> hotfix: adjust claim warning banner style

- src/staking-v3/components/dapp-selector/ModalSelectDapp.vue
- Added max height to the vote/stake modal
- The search form will stick to the top
- The button will stick to the bottom
**Check list**
**Changes**
> fix vote/stake modal height

- src/staking-v3/hooks/useLeaderboard.ts
- src/staking-v3/logic/interfaces/DappStakingV3.ts
- src/staking-v3/logic/models/DappStaking.ts
- src/staking-v3/logic/repositories/DappStakingRepository.ts
- src/staking-v3/logic/services/DappStakingService.ts
**Deploy after next Shibuya runtime upgrade**
This PR is to support breaking changes in runtime https://github.com/AstarNetwork/Astar/pull/1153
Unregistered dApps are removed from `integratedDApps` storage item and UI lost info about unregistered dApps. Also `state` field is removed from `DAppInfo ` structure.
I decided to use dApp data from indexer to fetch unregistered dApps info. 
**Check list**
> Handle removal of unregistered dApps from a node storage

- src/staking-v3/components/leaderboard/styles/leaderboard.scss
- src/staking-v3/components/styles/feature-dapp.scss
- Fixed the background image scroll animation
It worked in the local env but didn't work after deployment to the server. Still, I don't know why this happened, but adding `!important` to CSS fixed it.
I'm using a new CSS property [animation-timeline](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline), and it works only on Chrome.
https://www.loom.com/share/b3738834bb18412e92270d831f748140?sid=446c5940-f801-43fe-b17b-7a11279e2b60
**Check list**
> Fix scroll animation

- src/i18n/en-US/index.ts
- src/staking-v3/components/data/DataList.vue
Staking v3 data wording fix
**Check list**
> Wording fix

- src/staking-v3/components/DynamicAdsArea.vue
- src/staking-v3/components/dapp/DappAvatar.vue
- src/staking-v3/components/dapp/styles/builders.scss
- src/staking-v3/components/dapp/styles/dapp-avatar.scss
- src/staking-v3/components/styles/dapps.scss
- Added text ellipsis to the dApp cards:
- dApp title -> 1 line
- dApp description -> 3 lines
- Fixed the arrow style of the ads section
- Fixed the unwanted space of the dApp builders.
**Check list**
> Add text ellipsis to the dApp cards

- src/staking-v3/hooks/useDappStaking.ts
Users are unable to stake amounts less than `minStakingAmount`on WASM dApps they already already staked to.
**Check list**
> Min staking amount fix

- src/i18n/en-US/index.ts
- src/staking-v3/components/data/DataList.vue
- src/staking-v3/hooks/useDapps.ts
- src/staking-v3/hooks/useDataCalculations.ts
- src/staking-v3/logic/models/DappStaking.ts
- src/staking-v3/logic/repositories/IDataProviderRepository.ts
- src/staking-v3/logic/repositories/TokenApiProviderRepository.ts
- src/staking-v3/store/getters.ts
- src/staking-v3/store/mutations.ts
- src/staking-v3/store/state.ts
- Add lockers to the staker and lockers account numbers
**Check list**
> feat: From stakers to stakers and lockers

- src/App.vue
- src/components/assets/AnchorLinks.vue
- src/components/assets/YourProject.vue
- src/components/assets/styles/your-project.scss
- src/components/header/modals/ModalNetworkWallet.vue
- src/css/quasar.variables.scss
- src/i18n/en-US/index.ts
- src/links/index.ts
- src/staking-v3/components/ErrorPanel.vue
- src/staking-v3/components/Vote.vue
- src/staking-v3/components/my-staking/MyStakingCard.vue
- src/staking-v3/hooks/useDappStaking.ts
* fix: added docs link to the 'There are too many contract stake entries for the account' error message
* fix: displaying 'days' or 'day' on the MyStakingCard UI
* feat: added notification mark for claiming rewards
**Check list**
**Adds**
* feat: added notification mark for claiming rewards
=Staking=
=Project=
**Changes**
* fix: added docs link to the 'There are too many contract stake entries for the account' error message
=Before=
=After=
* fix: displaying 'days' or 'day' on the MyStakingCard UI
(more than 1) days
> fix: dApp staking kaizen

- src/components/bridge/ethereum/L1.vue
- src/hooks/bridge/useL1History.ts
- src/hooks/useGasPrice.ts
- src/i18n/en-US/index.ts
- src/modules/zk-evm-bridge/l1-bridge/utils.ts
* fix: disable sending bridge transactions when Gelato API is down
**Check list**
**Changes**
* fix: disable sending bridge transactions when Gelato API is down
Display the error toast
Disable the button
> fix: disable sending bridge transactions when Gelato API is down

- src/components/bridge/ethereum/styles/l1-bridge.scss
- src/hooks/bridge/useL1Bridge.ts
- src/i18n/en-US/index.ts
- src/v2/services/IZkBridgeService.ts
- src/v2/services/implementations/ZkBridgeService.ts
* feat: include transaction fee into calculation of ETH balance 
**Check list**
**Adds**
* feat: include transaction fee into calculation of ETH balance 
=Before=
Some users seem to think the gas fee is too expensive (which appears to be a bug), but it’s just because users don’t have enough ETH, and that’s why MetaMask fails to calculate the gas fee correctly.
=After=
Calculate the gas fee and display error if user doesn't have ETH to pay the fee, so that MetaMask won't pop up with wrong transaction fee.
> feat: include transaction fee into calculation of ETH balance

- src/components/header/YokiBanner.vue
Fix the header banner colour for zkEVM
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
> Fix header banner colour for zkEVM

- src/staking-v3/components/my-staking/MyStaking.vue
- src/staking-v3/components/my-staking/MyStakingCard.vue
* feat: display the amount of bonus rewards for Astar and Shiden
**Check list**
**Adds**
> feat: display the amount of bonus rewards for Astar and Shiden

- src/components/bridge/ethereum/L1Bridge.vue
> Enable Bridge red box again for noticing high traffic
**Check list**
**Adds**
- Enable Bridge Redbox for noticing high traffic
> enable bridge withdrawal redbox

- src/layouts/DashboardLayout.vue
Removed zk maintenance banner and put back Yoki banner
**Check list**
> Put back Yoki Origins banner

- src/components/header/UnderMaintenanceBanner.vue
- src/i18n/en-US/index.ts
- src/layouts/DashboardLayout.vue
- src/modules/zk-evm-bridge/l1-bridge/utils.ts
- src/modules/zk-evm-bridge/tokens.ts
- hotfix: merge the hotfix to main
- https://github.com/AstarNetwork/astar-apps/pull/1260
- https://github.com/AstarNetwork/astar-apps/pull/1262
- https://github.com/AstarNetwork/astar-apps/pull/1264
**Check list**
> hotfix: merge the hotfix to main

- src/staking-v3/hooks/useDataCalculations.ts
Fixed bug in tokens to be burned calculation. The calculation is still not 100% correct, because of an assumption that dApp tier allocation will be the same through all build and earn sub period eras. Fixing this requires a bit more time and it will be done next week.
Before
After
**Check list**
> Tokens to be burned calculation fix

- src/staking-v3/components/data/DataList.vue
- src/staking-v3/hooks/useDataCalculations.ts
Fixed existing 'tokens to be burned' calculation to use real dApp tiers allocation.
The code goes from the first `era` in the current period 'till `current_era - 1` and calculates how much reward are allocated for empty tiers slots (those are burned rewards). Those calculation is based on real data.
Second part of the calculations calculates the same from `current_era` until last `era` of the current period under assumption that we will have the same dApp tier allocations as in previous `era`. Since we are looking for total tokens to be burned this is the best we can.
The more we are progressing till the end of the current period the more precise calculation will be.
**Check list**
> Burned rewards calculation

- src/components/assets/Account.vue
* fix: total USD amount for lockdrop account
* fix: hide the lockdrop toggle on Astar zkEVM
**Check list**
**Fixes**
* fix: total USD amount for lockdrop account
=Before=
=After=
> fix: total USD amount for lockdrop account

- src/components/bridge/ethereum/L1Bridge.vue
- src/i18n/en-US/index.ts
> Enable deposit warning banner on portal
**Check list**
**Changes**
- Enable deposit warning banner on portal
I re-used the codes we was added for withdrawal banner, there's something need to changed (like variable naming). but I think it's not a big issue atm.
> add native bridge deposit warning banner

- src/i18n/en-US/index.ts
> Update withdrawal warning texts on bridge
**Check list**
**Changes**
- update `bridge.warningHighTraffic` text
> update withdrawal warning 20h -> 5h

- src/components/assets/transfer/LocalTransfer.vue
- src/components/assets/transfer/XcmBridge.vue
- src/components/bridge/ethereum/L1Bridge.vue
- src/components/dapp-staking/my-staking/components/modals/ModalUnbondDapp.vue
- src/components/dapp-staking/stake-manage/StakeForm.vue
- src/staking-v3/components/Amount.vue
- src/staking-v3/components/my-staking/ModalUnbondDapp.vue
- src/staking-v3/components/my-staking/ModalUnlockTokens.vue
* fix: disabled scrolling on input
**Check list**
**Fixes**
* fix: disabled scrolling on input
* before: the app allows to change the number of inputted amount if users scroll on the input accidentally.
* demo: https://gyazo.com/21603ecd8430c2dcd0d85f5471ed5abc
> fix: disabled scrolling on input

- package.json
- src/hooks/helper/wallet.ts
- yarn.lock
* feat: updated WC version
* feat: modified WC ID (using the same organization as Yoki's)
* feat: allow using laptop wallet options for staging URL (https://staging.portal.astar.network/) 
* WC won't work at staging URL created by firebase 
**Check list**
> feat: updates WC version

- src/components/common/styles/chart-panel.scss
- src/components/dashboard/Inflation.vue
- src/data/dapp_promotions.json
- src/hooks/useInflation.ts
- src/i18n/en-US/index.ts
Initially I used Blockscout API to determine starting block of inflation period 1. Since Subscan started to give us "too many requests" error I decided to hardcode block number for each network since this will never change. I should do that intially.
Also reordered latest promotion card to be visible on dApp staking page
**Check list**
> Hardcode inflation period start blocks

- src/components/assets/transfer/Information.vue
- src/modules/information/recent-history/transfer/index.ts
> in the transaction page, link of recent history using Astar zkEVM is linked to subscan, I separate the logic of aggregate transaction history
**Check list**
**Adds**
- castZkEVMTransferHistory function in `modules/information/recent-history/index.ts`
- getZkEVMTxHistories function in `modules/information/recent-history/index.ts`
**Fixes**
- separate aggregate tx histories logic for zkEVM in setTxHistories function at `components/assets/transfer/Information.vue`
> fix recent history link for zkevm

- src/i18n/en-US/index.ts
- src/staking-v3/components/PeriodStats.vue
- src/staking-v3/components/vote/choose-dapps/DappsList.vue
- src/staking-v3/hooks/usePeriodStats.ts
- src/v2/repositories/implementations/TokenApiRepository.ts
Fix for misconfigured swiper in voting component's dApps list 
Fix for sorting dApps by claimed rewards
Fix for TVL ratio in period stats component
**Check list**
> Fix dApp swiper configuration

- src/i18n/en-US/index.ts
- src/staking-v3/components/PeriodInfoVote.vue
- src/staking-v3/logic/services/DappStakingService.ts
Display sum of estimated APRs instead of the fixed value
**Check list**
> Show estimated staker + bonus rewards on vote info banner

- src/hooks/xcm/useTransferRouter.ts
* Hotfix: disabled polkadot xcm temporally 
* if you want to check on your end ([ref](https://github.com/AstarNetwork/astar-apps/pull/1313#issuecomment-2162687148)) 
**Check list**
> hotfix: disabled polkadot xcm temporally

- src/hooks/useInflation.ts
Token burning on Astar happened today and realized inflation chart went wrong. This happened because actual token issuance after burning is lower than at the beginning of staking period 1.
As a quick fix I deduced burned amount from token issuance at the beginning of period 1.
**Check list**
> Inflation chart

- src/components/bridge/BridgeSelection.vue
- src/i18n/en-US/index.ts
> disable celer bridge, https://x.com/CelerNetwork/status/1811368611828953312
**Check list**
**Fixes**
- Disable cbridge
> disable celer bridge

- src/hooks/usePrice.ts
> To avoid big number error, enable immediate only for H160 address in usePrice hooks
**Check list**
**Changes**
- only enable immediate for h160 address
> Fix use price

- src/v2/repositories/implementations/IdentityRepository.ts
After Shibuya upgrade identity started to fail because of result type change from `Option<PalletIdentityRegistration>` to 
`Option<(PalletIdentityRegistration,Option<Bytes>)>`
**Check list**
> Fetch account identity fix

- src/components/dashboard/Inflation.vue
- src/components/dashboard/InflationRateChart.vue
- src/hooks/useInflation.ts
- src/v2/repositories/ITokenApiRepository.ts
- src/v2/repositories/implementations/SubscanRepository.ts
- src/v2/repositories/implementations/TokenApiRepository.ts
Take burn events into account when calulating and drawing inflation charts
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
> User burn events in inflation charts

- src/components/assets/Erc20Currency.vue
- src/components/assets/EvmAssetList.vue
- src/components/assets/EvmCbridgeToken.vue
- src/components/assets/EvmNativeToken.vue
- src/components/assets/ZkAstr.vue
- src/components/bridge/BridgeSelection.vue
- src/components/bridge/layerzero/LzBridge.vue
- src/components/bridge/styles/bridge-selection.scss
- src/components/common/CustomRouterLink.vue
- src/constants.ts
- src/consts.ts
- src/features.ts
- src/hooks/bridge/useL1Bridge.ts
- src/hooks/useInflation.ts
- src/hooks/useNetworkInfo.ts
- src/staking-v3/hooks/usePeriodStats.ts
- src/util-general.ts
This is the first PR to centralize the portal configuration and simply enable/disable certain features, like bridges or XCM
Configuration is stored in `fetures.ts` and settings looks like
```
// Bridges
export const nativeBridgeEnabled = true;
export const layerZeroBridgeEnabled = true;
export const layerSwapBridgeEnabled = true;
export const celerBridgeEnabled = true;
export const omniBridgeEnabled = true;
export const stargateBridgeEnabled = true;
export const stakeStoneBridgeEnabled = true;
export const arthSwapBridgeEnabled = true;
```
The portal code is updated to take those settings into consideration. 
I found that disabling `router-link`, so I created replacement component in `CustomRouterLink.vue`
**Check list**
> Centralized configuration - part 1

- src/staking-v3/hooks/useDapps.ts
- src/staking-v3/logic/services/DappStakingService.ts
- src/staking-v3/logic/services/IDappStakingService.ts
Users stared to report below
https://files.slack.com/files-pri/T01GK90RW2G-F07GT9ASQ79/image.png
Main reason for this state is that dapp are not loaded into the local storage because network is not provided. This started to happen because of https://github.com/AstarNetwork/astar-apps/pull/1372 where `rawMetadata` loading takes a bit longer.
I will work on optimizing metadata loading in the next PR
**Check list**
> Fix for getting dApps

- src/staking-v3/components/leaderboard/Tier.vue
- src/staking-v3/logic/interfaces/DappStakingV3.ts
- src/staking-v3/logic/models/DappStaking.ts
- src/staking-v3/logic/repositories/DappStakingRepository.ts
Support for dApp staking pallet changes explained in #1367
Runtime changes are not deployed on any network yet, but the code can be tested with local node after pulling the latest `main` branch. The code should work without errors on local node, Shibuya, Shiden, Astar.
Tier threshold value should be visible on UI
Closes #1367 
**Check list**
> Tier thresholds derivation support

- src/staking-v3/components/data/DataList.vue
Realized estimated inflation was not showing on dApp staking data panel
BEFORE
AFTER
**Check list**
> Fix: estimated realized inflation not showing

- src/v2/repositories/implementations/EvmAssetsRepository.ts
This is PR is to re-try fetching data from cbridge API. I noticed that recently first request to their API started to fail, but 2nd one works fine. 
Because of that issue assets page spins forever when user is connected with EVM wallet
**Check list**
> Re-try fetch from cbridge

- src/App.vue
- src/hooks/index.ts
- src/hooks/useBlockTime.ts
- src/staking-v3/hooks/useAprV3.ts
- src/staking-v3/hooks/useVotingCountdown.ts
- src/staking-v3/logic/services/DappStakingService.ts
- src/staking-v3/logic/services/DappStakingServiceEvm.ts
- src/store/general/getters.ts
- src/store/general/mutations.ts
- src/store/general/state.ts
- src/v2/repositories/ISystemRepository.ts
- src/v2/repositories/implementations/SystemRepository.ts
- fetch block time from a chain
- remove hardcoded block time values in code
**Check list**
> Fetch block time from chain

- src/constants.ts
- src/staking-v3/logic/services/DappStakingService.ts
- src/v2/repositories/ISystemRepository.ts
- src/v2/repositories/implementations/SystemRepository.ts
I made an oversight in #1384 when I forgot to provide block number when fetching block time in APR calculations
**Check list**
> APR calculation fix to use block time for a given block

- src/staking-v3/components/ClaimAndRestakeButton.vue
- src/staking-v3/components/my-staking/MyStaking.vue
- src/staking-v3/hooks/useDappStaking.ts
- src/staking-v3/hooks/useVote.ts
There was a bug when the system was re-staking rewards to an unregistered dApp. This was happening If user has stakes on a dApp which was unregistered after staking and tries to re-stake rewards. In that case the  below error will occur
Also found and fixed a bug where the whole bonus rewards object was stored to state instead amount.
**Check list**
> Fix for re-staking on unregistered dApps

- src/components/sidenav/SidebarDesktop.vue
- src/components/sidenav/styles/sidebar-desktop.scss
> Fix Menu indicator, it has wrong margin top because of the governance item
**AS_IS**
**TO_BE**
**Check list**
**Fixes**
- FIx desktop indicator
> fix indicator margin for governance item

- src/components/dashboard/InflationRateChart.vue
- src/hooks/useInflation.ts
- src/staking-v3/components/data/DataList.vue
- src/v2/repositories/ITokenApiRepository.ts
- src/v2/repositories/implementations/AccountUnificationRepository.ts
- src/v2/repositories/implementations/TokenApiRepository.ts
Inflation chart fixed to use actual token issuance instead of trying to calculate it.
**Check list**
> Inflation chart fix

- src/v2/services/implementations/AssetsService.ts
* fix: modified logic for checking the native token's remaining balance  
**Check list**
> fix: modified logic for checking the native token's remaining balance  

- src/hooks/useAccount.ts
When we are implemented account unification on Shibuya we tried to load an account owned NFT from Token API as avatar. If error happens while fetching from the API accounts were not shown.
This PR fixes the above behaviour
UPDATE
Just found out that Bluez is deprecating all their services. Since we are using their API for NFT fetching I commented out the code until find out other provider
**Check list**
> Account NFT loading fix

- .gitignore
- src/components/bridge/ethereum/L1Bridge.vue
- src/components/bridge/layerzero/LzBridge.vue
- src/features.ts
- src/hooks/bridge/useL1Bridge.ts
- src/hooks/bridge/useLayerZeroBridge.ts
- src/i18n/en-US/index.ts
- src/router/utils/index.ts
Disable deposit to zkEVM and disabled LayerSwap link
**Check list**
> Disable deposit to zkEVM

- src/components/bridge/ccip/CcipBridge.vue
- src/i18n/en-US/index.ts
* hotfix: merge to the main branch
**Check list**
> hotfix: merge to the main branch

- src/staking-v3/logic/interfaces/DappStakingV3.ts
- src/staking-v3/logic/repositories/DappStakingRepository.ts
New runtime with move stake introduced a breaking change, because of what Shibuya dApp staking is currently broken.
**Check list**
> Fix for breaking change in runtime

- .github/workflows/deploy-to-staging.yml
- .github/workflows/pull-request-preview.yml
> Fix Firebase Hosted Preview URL workflow with downgrading firebase-tools version
**Check list**
**Fixes**
- Fix Firebase Hosted Preview URL workflow with downgrading firebase-tools version
> pin firebase-tools version to 13.35.1 in PR preview workflow

- src/components/bridge/BridgeSelection.vue
- src/components/header/modals/SelectNetwork.vue
- src/features.ts
Disabled zkEVM bridges and network selection. I didn't completely remove all zk related components and logic just in case we will need to re-enable the network access for a short period of time.
I will remove all zk related code later.
**Check list**
> Disable zk bridges and network selection

- src/staking-v3/hooks/useVote.ts
Fix for available staking balance when user has tokens locked in governance
**Check list**
> Fix for available staking balance when user has tokens locked in gov.

- src/components/assets/Account.vue
* fix: removed zkEVM switch
**Check list**
**Fixes**
=Before=
=After=
> fix: removed zkEVM switch

- src/components/assets/SideAds.vue
The bridge to Soneium was partially hidden by ads
BEFORE
NOW
**Check list**
> Fix for a bridge tooltip being partially hidden

- src/v2/repositories/implementations/xcm/UniqueXcmRepository.ts
Fixes cross-chain transfers from Unique Network.
**Check list**
**Fixes**
Fixed the `xtokens.transfer` extrinsic `destination` argument. It now uses XCM v5 instead of v2.
Here is the link to `astar-apps` with the applied fix: https://poc-apps.andy.uniquenetwork.dev/
> fix: unq transfer, use xcm v5
