src/components/balance/BalancePlasm.vue
src/components/balance/modals/MetamaskOption.vue
src/components/balance/modals/ModalSelectAccount.vue
src/components/balance/modals/ModalTransferAmount.vue
src/config/chainEndpoints.ts

Found and issue when submitting extrinsic call with same amount to the same account multiple times. First transaction passes, others not. I need to restart the app if I want to submit second transaction
https://user-images.githubusercontent.com/8452361/131121425-ea43ee63-cc9f-4dc5-9f36-53a5ea22e51f.mp4

Extrinsic call

---

.github/workflows/pr-checks.yml
.github/workflows/publish-gh-pages.yml
package.json

- adds project script
- adds PR check action
- adds GH pages deploy action

Add repo deploy action

---

.github/workflows/publish-gh-pages.yml

change the deploy folder directory

added spa subdir

---

src/components/store/modals/StakeModal.vue

Temporarily remove max available amount check, so users can stake to contracts, until I found a proper solution.
**Check list**

Temporarily remove max available amount check

---

src/components/store/Dapp.vue
src/store/dapps-store/actions.ts

Optimize a way to get latest stake point
**Check list**
**Fixes**
- performance issue while loading dapp info.
**To-dos**
> additional store optimizations (reward calculation, prefetch commonly used values....)

Dapp info loading optimization

---

src/hooks/firebase/index.ts

>Added anonymous authentication to firebase so I can change security rules to allow Firebase access to authenticated users only. This is temporary measure until we setup the admin service
**Check list**
**Adds**
- Firebase anonymous authentication
**To-dos**
> Update firebase security rules to allow authenticated users only.

Firebase anonymous authentication

---

src/hooks/firebase/index.ts

> Added authentication domain to firebase config in order to fix authentication error on mobile
**Check list**
**Adds**
- Authentication domain to Firebase config
**Fixes**
- Authentication error on mobile platforms

Added authentication domain

---

src/components/store/DiscoverDappsTab.vue
src/components/store/statistics/Requirement.vue
src/i18n/en-US/index.ts
src/i18n/ja/index.ts
src/i18n/zh-TW/index.ts
src/i18n/zh/index.ts

* added 'REQUIREMENT' component in store section
**Check list**
**Changes**
=Before=
=After=

feat: added 'REQUIREMENT' component in store section

---

src/components/store/StakePanel.vue

* Removed duplicated "Your stake" row
**Check list**
**Changes**
=Before=
=After=

fix: remove duplicated 'Your stake' row

---

src/components/balance/Address.vue
src/components/balance/BalancePlasm.vue
src/components/balance/PlmBalance.vue
src/components/balance/ToggleMetaMask.vue
src/components/balance/modals/ModalWithdrawalEvmDeposit.vue
src/hooks/useBalance.ts

* withdraw EVM deposit from Ethereum extension account
* fixed a bug that displays Kusama format SS58 address after turning off the toggle
Issue: https://github.com/PlasmNetwork/astar-apps/issues/163
**Check list**
**Changes**
Ethereum Extention

feat: withdraw EVM Deposit from Ethereum Extension

---

src/components/store/modals/StakeModal.vue

* Fixed amount validation for unstaking
**Check list**

fix: Amount validation for unstaking

---

src/App.vue
src/components/balance/modals/ModalNetwork.vue
src/components/common/Balance.vue
src/components/common/Header.vue
src/components/store/modals/ClaimRewardModal.vue
src/config/chainEndpoints.ts
src/config/localStorage.ts
src/hooks/helper/plasmUtils.ts
src/hooks/helper/units.ts
src/hooks/useApr.ts
src/hooks/useChainMetadata.ts
src/hooks/useTvl.ts
src/store/dapps-store/actions.ts

* Display globally recognized units
* Remove unnecessary '0' 
issue, proposal:
https://github.com/PlasmNetwork/astar-apps/issues/152
https://forum.astar.network/t/changing-units-used-in-portal/2377?u=royal
**Check list**
**Changes**
=Before=
=After=

fix: Display globally recognized units

---

src/components/dapp-staking/modals/ClaimRewardModal.vue

> Pending rewards calculation formatting issue fix
closes #191 
**Check list**
**Fixes**
- Pending rewards formatting

Fixed pending rewards formatting

---

src/components/dapp-staking/modals/ModalDappDetails.vue

* Added close button in `ModalDappDetails`
**Check list**
**Adds**

fix: close ModalDappDetails

---

src/components/balance/ConnectWallet.vue
src/components/balance/modals/ModalConnectWallet.vue
src/components/balance/modals/wallet/WalletOption.vue
src/components/dapp-staking/modals/ModalDappDetails.vue
src/store/general/state.ts

> Fixed dapp info styling issue related to shared css file 
**Check list**
**Adds**
- Shidden as default network
**Fixes**
- dapp info styling issue

dapp info styling fix

---

src/components/balance/modals/ModalAccount.vue

Pre-select first account in Account select modal
Gif:
https://gyazo.com/d99a34702fb8521efedb051029841abc
**Check list**

fix: pre-select first account in ModalAccount

---

src/config/chainEndpoints.ts

Changed the Astar node endpoint
**Check list**
**Adds**
**Fixes**
**Changes**
- Astar node endpoint from BLD node to Stake node
**To-dos**

changed astar endpoint

---

.github/workflows/publish-gh-pages.yml
src/components/balance/PlmBalance.vue
src/hooks/helper/vested.ts
src/hooks/useBalance.ts
src/i18n/en-US/index.ts

> Adds option to unlock vested tokens
**Check list**
**Adds**
- Unlock vested tokens feature

Add unvest button to balance page

---

src/config/chainEndpoints.ts

* Modified EVM RPC for Astar network
**Check list**

fix: EVM RPC for Astar network

---

src/config/chainEndpoints.ts

Changed astar endpoint from Stake to OnFinality for better stability.
Note that the EVM endpoint is the same.
**Check list**
**Adds**
**Fixes**
**Changes**
- Astar network endpoint
**To-dos**

changed astar endpoint to onfinality

---

src/components/balance/Address.vue
src/components/balance/Wallet.vue
src/i18n/en-US/index.ts

* Added address format tooltip
* `SS58` -> `Native`, `H160` -> `EVM`
**Check list**
=Before=
=After=

feat: added address format tooltip

---

src/config/chainEndpoints.ts

> Enables dApp store link on Astar network
**Check list**
**Adds**
- dApps store link

Enable dApp staking on Astar

---

src/components/dapp-staking/DiscoverDappsTab.vue
src/hooks/useApr.ts
src/hooks/useTvl.ts
src/i18n/en-US/index.ts

* Added APR for Astar dApps Staking
* Use APR instead of APY because the difference is too wide at this moment
**Check list**

fix: added APR for astar dapps staking

---

src/config/chainEndpoints.ts
src/hooks/useFaucet.ts

* Activated faucet button for Astar network
Backend: https://github.com/AstarNetwork/astar-faucet-bot/pull/21
**Check list**
**Changes**
**To-dos**
Top up ASTR to faucet [hotwallet](https://astar.subscan.io/account/bWGhcGXEovmH5TjLEq2zQGyLJPFAA6wRYQkyWppncCFjhyD)
bWGhcGXEovmH5TjLEq2zQGyLJPFAA6wRYQkyWppncCFjhyD
(I have added 1 ASTR)

feat: activated ASTR faucet

---

src/store/general/state.ts

* Change the default network to Astar instead of Shiden
**Check list**

fix: change the default network to Astar

---

src/components/balance/modals/ModalSelectAccount.vue

> Leave empty to address when transfer dialog opens
Should be tested on staging env before merge
**Check list**

Blank to address by default in transfer dialog

---

src/components/balance/WalletH160.vue
src/config/chainEndpoints.ts
src/hooks/useConnectWallet.ts
src/i18n/en-US/index.ts
src/web3/index.ts

* Changed EVM explorer from Subscan to Blockscout
* Fixed bug where the app remembers the selected wallet
**Check list**
**Changes**

fix: Changed EVM explorer to Blockscout

---

src/components/balance/PlmBalance.vue
src/components/balance/modals/ModalSelectAccount.vue
src/components/balance/modals/ModalVestingInfo.vue
src/hooks/useBalance.ts
src/i18n/en-US/index.ts

**Check list**
**Adds**
- Lock info
**Changes**
- Vesting info to display remaining vests

Remaining vests and lock info

---

src/components/dapp-staking/DiscoverDappsTab.vue
src/components/dapp-staking/statistics/ChunksModal.vue
src/components/dapp-staking/statistics/Withdraw.vue

> Fixed some un-bonding period calculation issue which happened due backend code changes
**Check list**
**Fixes**
- Un bonding period calculation issues
**Changes**

Unbonding period fixes

---

src/components/balance/PlmBalance.vue
src/hooks/useEvmDeposit.ts
src/hooks/useFaucet.ts

* Added faucet feature to EVM address
**To-dos**
* Top-up EVM ASTR/SDN/SBY to 0x91986602d9c0d8a4f5bfb5f39a7aa2cd73db73b7
* Test on Shibuya (when Shibuya EVM has been fixed)
Backend: https://github.com/AstarNetwork/astar-faucet-bot/pull/22
**Check list**

feat: added EVM faucet

---

src/components/balance/modals/ModalTransferAmount.vue
src/i18n/en-US/index.ts

**Check list**
**Adds**
- Warning on transfer dialog if user is connected with ETH wallet

EVM mode warning

---

src/components/balance/modals/ModalSelectAccount.vue
src/components/balance/modals/ModalTransferAmount.vue
src/i18n/en-US/index.ts

* Show target account balance
* Add transaction confirmation check before sending (whenever sending from EVM address)
**Check list**
**Adds**

fix: Added tarnget account balance and tx confirmation check

---

src/hooks/useTransfer.ts

* stop the loading animation whenever user cancels signing on the transaction 
(FYI @sirius651)
**Check list**
**Fixes**
Before:
https://gyazo.com/ac8518e3d97f1b928cf344399d6eeddc
After:
https://gyazo.com/482277c5cf8a10e17428c380790ce54d

fix: stop the loading animation whenever user cancels signing on the transaction

---

src/components/dapp-staking/StakePanel.vue

* Fixed unbonding transaction for ethereum wallet 
**Check list**

fix: unbonding transaction for ethereum wallet

---

src/config/chainEndpoints.ts

* Updated Shiden EVM endpoint
**Check list**

fix: update shiden RPC endpoint

---

src/components/balance/modals/ModalTransferAmount.vue
src/i18n/en-US/index.ts

* Added confirmation checkbox to transfer modal for ECDSA signature
**Check list**
**Changes**

fix: added confirmation checkbox to transfer modal for ECDSA signature

---

quasar.conf.js
src/index.template.html

> Google Tag Manager support
**Check list**
**Adds**
- Google Tag Manager

Google tag manager set up

---

src/hooks/helper/claim.ts
src/store/dapp-staking/actions.ts
src/store/dapp-staking/calculation.ts

Renamed `stakerInfo` query to `generalStakerInfo`
Ref: https://github.com/AstarNetwork/astar-frame/pull/6#discussion_r822127358
**Check list**

feat: Renamed stakerInfo query to generalStakerInfo

---

src/components/dapp-staking/StakePanel.vue
src/hooks/helper/claim.ts
src/hooks/useCustomSignature.ts

* modify the color of the unbond button
* rename query name from `stakersInfo` to `generalStakerInfo` (individual claim)
**Check list**
**Changes**
=Before=
=After=

fix: modify the color of the unbond button

---

src/boot/api.ts
src/components/dapp-staking/ClaimAll.vue
src/hooks/helper/claim.ts
src/hooks/helper/plasmUtils.ts
src/hooks/useClaimAll.ts
src/store/dapp-staking/actions.ts
src/store/dapp-staking/calculation.ts

Fixed issues reported in https://github.com/AstarNetwork/astar-apps/issues/285 and https://github.com/AstarNetwork/astar-apps/issues/286
Staging URL: https://deploy-preview-pr-287.herokuapp.com/#/balance/wallet
**Check list**

fix: condition of invoking claimDapp function

---

src/components/assets/modals/ModalVesting.vue
src/components/header/modals/ModalAccount.vue
src/components/header/modals/SelectWallet.vue
src/config/wallets.ts

* display wallet name and logo correctly
* Ref: https://github.com/AstarNetwork/astar-apps/pull/297#issuecomment-1082705662
=Before=
https://gyazo.com/5771c90497ea436a504ae9d15fca0980
=After=
https://gyazo.com/867e4e201e888fbe03724392b99c4402
**Check list**

fix: display wallet name and logo correctly

---

package.json
src/boot/uiLib.ts
src/components/header/modals/SelectWallet.vue
yarn.lock

* Close the wallet dropdown whenever users click outside
* Ref: https://github.com/AstarNetwork/astar-apps/pull/297#issuecomment-1082115916 
=Before=
https://gyazo.com/95f6ad9d408ef7a3e37be5694330ab5c
=After=
https://gyazo.com/a48cecfbb963ab6f136ec6c7fb8ea64a
**Check list**

fix: close the wallet dropdown whenever users click outside

---

src/components/header/modals/ModalNetwork.vue

* Fixed hovering and not hovering effect 
* Adjusted align items (y direction) 
* Adjusted padding (y direction)
=Before=
https://gyazo.com/9236c0a83a93b26e50ae6a34d4884e14
=After=
https://gyazo.com/4e91cf0d42fe3f654437b829e6f27133
**Check list**

fix: network modal

---

src/components/header/modals/ModalNetwork.vue

* Fixed connect button in network modal
* Ref: https://github.com/AstarNetwork/astar-apps/pull/297#issuecomment-1084373412
=Before=
=After=
**Check list**

fix: Connect button in Network modal

---

src/components/assets/modals/ModalFaucet.vue
src/hooks/useFaucet.ts
src/router/routes.ts

* Redirect from /balance to /assets
* Call the faucet API whenever users open Faucet Modal
**Check list**

fix: redirect from /balance to /assets

---

src/components/header/Header.vue
src/components/header/modals/ModalAccount.vue
src/components/header/modals/ModalConnectWallet.vue
src/hooks/helper/wallet.ts
src/hooks/useConnectWallet.ts

* Fixed connect wallet behaviour
* Ref: https://github.com/AstarNetwork/astar-apps/pull/295#discussion_r839689477
* Adjusted styling for the `Math Wallet` warning messages
**Check list**
=Before=
=After=

fix: connect wallet behaviour

---

src/components/assets/Account.vue
src/components/assets/EvmAssetList.vue
src/components/assets/styles/asset-list.scss
src/components/balance/Address.vue
src/components/balance/WalletH160.vue
src/components/contracts/CodeItem.vue
src/components/contracts/ContractItem.vue
src/components/header/modals/ModalAccount.vue
src/hooks/c-bridge/useCbridgeV2.ts

* Fixed the copy function and the explorer link in the wallet modal
* display ERC20 tokens alphabetically
Before: https://gyazo.com/f231cd1168eec4ee9774369eef9d00a3
After: https://gyazo.com/cba4ac03767f9a657797c5839a29e1cd
Before: https://gyazo.com/7102d6deb92c32176f2d460634a1750e
After: https://gyazo.com/b94c27bed65cbbb3e1c795271266d2fc
Before: https://gyazo.com/f2aa5b3799275eb5f8e4274737af0a3a
After: https://gyazo.com/f0764a86c39a039ef3320f32f0fdf9a8
**Check list**

fix: fixed the copy function and the explorer link in the wallet modal

---

src/components/header/ConnectButton.vue
src/components/header/ConnectionIndicator.vue
src/components/header/NetworkButton.vue
tailwind.config.js

**Check list**
fixes below:
- [connectionIndicator](https://github.com/AstarNetwork/astar-apps/pull/295#discussion_r839673137)
- remove tailwindconfig
- [resolve version issue](https://github.com/AstarNetwork/astar-apps/pull/295#issuecomment-1084984399)

fix issues on feedback - v2

---

src/components/header/modals/ModalNetwork.vue
src/hooks/helper/wallet.ts

* change the network for Math wallet (Android)
**Check list**

fix: change the network for Math wallet (Android)

---

src/components/header/AccountButton.vue
src/components/header/ConnectButton.vue
src/components/header/NetworkButton.vue
src/components/sidenav/SidebarDesktop.vue
src/components/sidenav/SidebarMobile.vue
src/components/sidenav/styles/sidebar.scss
src/css/quasar.variables.scss

* added animated navigation bar
**Check list**
https://user-images.githubusercontent.com/92044428/161371438-27a89377-391c-40e7-911f-5acfe0a870c7.MP4

feat: added animated navigation

---

src/components/assets/Account.vue
src/components/assets/Assets.vue
src/components/assets/EvmAssetList.vue
src/components/assets/NativeAssetList.vue
src/components/balance/modals/ModalInstallWallet.vue
src/components/header/NetworkButton.vue
src/components/header/modals/ModalConnectWallet.vue
src/css/app.scss
src/css/astar-ui.scss
src/css/skeleton.scss
src/hooks/c-bridge/useCbridgeV2.ts
src/hooks/helper/common.ts

* Added skeleton whenever the app is loading
* Moved MetaMask on top of the list
* Refactored ModalInstallWallet.vue
**Check list**

feat: added skeleton whenever the app is loading

---

src/components/assets/EvmToken.vue
src/components/assets/styles/asset-list.scss
src/i18n/en-US/index.ts

* Added 'add' icon
**Check list**
**Changes**
=Before=
=After=

fix: 'add to wallet' icon 

---

package.json
src/components/assets/Account.vue
src/components/assets/modals/ModalVesting.vue
src/components/assets/styles/modal-vesting.scss
src/components/balance/Address.vue
src/components/balance/WalletH160.vue
src/components/header/modals/ModalAccount.vue
src/css/astar-ui.scss
src/css/modal.scss
src/hooks/useVesting.ts
yarn.lock

* display all the vesting information
* adjusted padding size in the modal (mobile)
* fixed copy function for Android devices (installed `copy-to-clipboard` library (1.3kb) )
**Check list**
**Fixes**
=Before=
=After=

fix: display all the vesting information

---

src/config/web3/index.ts
src/hooks/useBalance.ts

Fixed some console errors in Firefox
**Check list**
**Fixes**
- Console errors in Firefox.

Firefox errors fix

---

src/components/header/modals/ModalAccount.vue
src/components/header/modals/SelectWallet.vue
src/components/header/modals/SelectWalletOption.vue
src/components/header/styles/modal-select-account.scss

**Check list**
**Fixes**
Fix position of select wallet option & set separate css for this component including refactors which got rids of tailwind stuff

fix: position of select wallet option 

---

src/config/chainEndpoints.ts

Changing the Shiden endpoint to use OnFinality nodes due to a scaling issue with our public endpoint
**Check list**
**Changes**
- shiden endpoint

using onfinality endpoint for Shiden

---

src/components/header/modals/ModalNetwork.vue
src/css/astar-ui.scss

=Before=
=After=
**Check list**

fix: position of the custom network input

---

src/components/assets/Assets.vue
src/components/assets/EvmToken.vue
src/hooks/c-bridge/useCbridgeV2.ts
src/hooks/useConnectWallet.ts

*  Load H160 mode scene more smoothly
**Check list**
**Fixes**
=Before=
https://user-images.githubusercontent.com/92044428/161604449-d4eb47e5-005e-404f-b152-5735d7acebcc.mov
=After=
https://user-images.githubusercontent.com/92044428/161604183-0d3a4195-84a0-4f70-868c-671093bdb7b1.mov

fix: Load H160 mode scene more smoothly

---

quasar.conf.js
src/components/assets/modals/ModalTransfer.vue
src/components/assets/styles/modal-select-account.scss
src/components/assets/styles/modal-transfer.scss
src/css/astar-ui.scss
src/css/box.scss
src/css/button.scss
src/css/quasar.variables.scss
src/css/text.scss

* Adjusted modal styling for small devices
* Adjusted transfer modal styling
**Check list**
**Fixes**
=Before=
=After=

fix: transfer modal

---

src/components/header/AccountButton.vue
src/components/header/ConnectButton.vue
src/components/header/MetaUpdateButton.vue
src/components/header/NetworkButton.vue
src/components/header/modals/ModalAccount.vue
src/components/header/modals/ModalNetwork.vue

v2:: get rids of tailwind stuff & fix minor ui issue

---

src/components/assets/styles/assets.scss
src/components/dashboard/ChartPanel.vue
src/components/dashboard/Dashboard.vue
src/components/dashboard/TokenPriceChart.vue
src/components/dashboard/TotalTransactionsChart.vue
src/components/dashboard/TvlChart.vue
src/components/dashboard/ValuePanel.vue
src/components/dashboard/styles/chart-panel.scss
src/css/skeleton.scss

* Added skeleton
* Adjusted styling
* Added gradient color to the chart 
**Check list**
**Fixes**
=Before=
GIF
https://gyazo.com/90b0fa2aec6baeef0e4434b3c693db84
=After=
GIF
https://gyazo.com/de65fb336692aae3fd0e7fe938940cb2

styling: added skeleton and adjusted styling on dashboard page

---

package.json
yarn.lock

**Check list**
I'll keep updating & publishing to astar-ui library. but before that, currently the portal brings the latest version of ui lib, so we should fix as specific version(v0.0.15) for the possibility of crashes or bugs.

Set fix version of ui library : v0.0.15

---

src/components/assets/Assets.vue
src/components/assets/EvmAssetList.vue
src/components/assets/modals/ModalTransfer.vue
src/config/wallets.ts
src/hooks/c-bridge/useCbridgeV2.ts

* styling: put MetaMask on top of the wallet list
* feat: update ERC20 token balance after sending transaction
* fix: avoid fetching ERC20 tokens in Shibuya
* refactor: `useCbridgeV2.ts`
**Check list**
**Changes**
=Before=
=After=

feat: update ERC20 token balance, put MetaMask on top of the wallet list

---

src/components/dapp-staking/modals/RegisterDappSupport.vue

As Maarten asked changed 'Astar forum post link' to 'Twitte link'
**Check list**
**Fixes**
- Label caption

Register dapp label change

---

src/hooks/useCurrentEra.ts

* calculate blocks until next era by `nextEraStartingBlock` query
**Check list**
**Fixes**

fix: blocks until next era

---

src/hooks/useApr.ts

* Updated `getApr` function due to `individual claim`
**Check list**
=Before=
=After=

fix: display APR

---

src/components/dapp-staking/modals/RegisterDappSupport.vue
src/hooks/firebase/index.ts
src/store/dapp-staking/actions.ts

Fixes dapp registration bug. Bug was caused by making video url optional field.
**Check list**
**Adds**
- new license type GNU (requested by Starlay)
**Fixes**
- dapp registration bug when user tries to register dapp without video
**Changes**
- show message box in case of dapp registration error, so user has a time to make screen shot which can be send to us

Dapp registration bug fix

---

package.json
src/components/assets/modals/ModalEvmWithdraw.vue
src/components/assets/modals/ModalFaucet.vue
src/components/assets/modals/ModalTransfer.vue
src/components/assets/modals/ModalVesting.vue
yarn.lock

* Fade out modal whenever users click the button inside the modal
Demo: https://www.loom.com/share/a0230283ef424d4bb64f979304d652f9
**Check list**

feat: fade out modal whenever users click the button inside the modal

---

src/config/chainEndpoints.ts

* changed wss endpoint for astar network temporary

fix: wss endpoint for astar network

---

src/components/header/styles/modal-network.scss
src/config/api/polkadot/connectApi.ts

* feat: adjusted fallback timeout condition to 8 secs since 3 seconds is too strict.
* styling: minor update (`cursor` in network menu) ([Before](https://gyazo.com/f7409c317a907bee1034b1c02c42447c) / [After](https://gyazo.com/1aea5eff4dc40907bc3e839f8cb0ebf0))
**Check list**

fix: adjusted timeout condition

---

src/boot/api.ts
src/config/chainEndpoints.ts
src/config/web3/utils/index.ts
src/hooks/helper/price.ts

* added fallback endpoint for EVM RPC
* The portal will connect to the OnFinality endpoint whenever the public node is down
* added fallback function for fetching token price
*  The portal will fetch token prices via DIA API whenever the coingecko API is down  
**Check list**
=Before=

feat: added fallback configuration for EVM network

---

src/App.vue
src/components/common/ModalLoading.vue
src/components/common/SpinnerV2.vue
src/components/dashboard/ChartPanel.vue
src/components/dashboard/styles/chart-panel.scss
src/components/header/modals/ModalNetwork.vue
src/components/header/styles/modal-network.scss
src/css/app.scss
yarn.lock

* feat: Added route transition
* https://gyazo.com/ca1d36dda42dcdbe8b68b53c70b322ac   
* feat: Updated loading animation
*  https://gyazo.com/903905c96b7033baf7496d923a1c4733 
* fix: Modified scrolling on the network drawer
* Before: https://gyazo.com/1346353f3fde23c65be91affc43bd2b7
* After: https://gyazo.com/9854e3eace1c222291b3370ce69803fe 
**Check list**

styling: updated animations

---

src/hooks/custom-signature/utils.ts
src/hooks/helper/addressUtils.ts
src/hooks/useConnectWallet.ts

* Convert H160 address to checksum address
* issue: https://github.com/AstarNetwork/astar-apps/issues/170  
**Check list**
**Changes**
=Before=
=After=

fix: convert H160 address to checksum address

---

src/components/dapp-staking/statistics/Withdraw.vue
src/i18n/en-US/index.ts

Adds unbonding period info to dashboard widget
**Check list**
**Adds**
- unbonding period info

Display unbonding period info

---

src/hooks/dapps-staking/useCompoundRewards.ts
src/hooks/useClaimAll.ts
src/hooks/useEvmDeposit.ts
src/hooks/useTransfer.ts
src/hooks/useVesting.ts
src/store/dapp-staking/actions.ts

Add tip for native transactions. The tips are set as a constant non-zero for now, but we will want to add dynamic tips and tip options later
**Check list**
**Adds**
- transaction tip
**Fixes**
**Changes**
**To-dos**

add tip value for all native transfers

---

src/components/dapp-staking/DiscoverDappsTab.vue
src/components/dapp-staking/UserRewards.vue
src/components/dapp-staking/styles/user-rewards-widget.scss
src/components/dapp-staking/styles/user-rewards.scss
src/hooks/dapps-staking/useCompoundRewards.ts
src/i18n/en-US/index.ts

Updates as per latest conversation in https://github.com/AstarNetwork/astar-apps/pull/341#issuecomment-1117007575
**Check list**
**Adds**
- Components reordering and text updates

Compounding rewards layout and text updates

---

src/hooks/helper/claim.ts
src/hooks/useClaimAll.ts

Fix for the following error 
**Check list**
**Fixes**
- Transaction would exhaust the block limits

Claim all batch weight check

---

src/components/common/InputAmount.vue
src/components/dapp-staking/modals/StakeModal.vue
src/hooks/dapps-staking/useStakingList.ts
src/modules/dapp-staking/index.ts
src/modules/dapp-staking/utils/index.ts

* Resolved a proxy error due to `.toString` method in nomination transfer feature
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

fix: balance type for nomination transfer

---

src/hooks/c-bridge/useCbridge.ts

* fix: wallet address in useCbridge.ts
**Check list**

fix: useCbridge.ts

---

src/components/dapp-staking/modals/ModalRegisterDapp.vue

This issue is reported by community member. Malicious attacker was able to enter malicious javascript code in description field during the dapp registration.
**Check list**
**Fixes**
- XSS vulnerability fix

XSS vulnerability fix

---

src/components/assets/Assets.vue
src/components/assets/EvmAssetList.vue
src/components/assets/XcmNativeAssetList.vue
src/components/assets/modals/ModalXcmBridge.vue
src/components/assets/styles/modal-xcm-bridge.scss
src/components/common/ModalLoading.vue
src/css/box.scss
src/hooks/xcm/SubstrateApi.ts
src/hooks/xcm/useXcmBridge.ts
src/i18n/en-US/index.ts
src/modules/xcm/index.ts
src/modules/xcm/tokens/index.ts
src/modules/xcm/utils/index.ts

* updated the XCM bridge modal styling
* improved the connection to the relaychain API
**Check list**
**Fixes**
* feat: update the XCM asset balances after sending bridge transaction
* feat: improved the connection to the relaychain API
* resolved errors that came from SubstrateApi.ts
* improved fetching speed for the account balances in relaychain
* before: around 10secs
* after: around 5 secs
* styling: updated the modal styling 
* styling: display loader modal while loading the account balances and existential deposit amount 
* styling: close XCM bridge modal after sending bridge transaction
=Before=
errors that came from SubstrateApi.ts
=After=

feat: updated XCM bridge modal

---

src/components/assets/modals/ModalXcmTransfer.vue
src/hooks/xcm/useXcmBridge.ts

Added asset transfer logic:
- from native to native account
- from native to EVM account
**Check list**
**Adds**
- asset transfer

Asset transfer

---

src/hooks/useCustomSignature.ts

useCustomSignature wasn't checking extrinsic call events which caused false positive portal notifications on failed transactions.
After fix, in case of failed extrinsics the portal will show an error message 
**Check list**
**Fixes**
- extrinsic events check in useCustomSignature call

Check extrinsic events in useCustomSignature

---

src/hooks/xcm/useXcmBridge.ts
src/i18n/en-US/index.ts

Check if the non-zero balance of the account when transfer

---

src/components/assets/EvmAssetList.vue
src/components/assets/NativeAssetList.vue
src/components/assets/modals/ModalXcmTransfer.vue
src/hooks/xcm/useXcmBridge.ts
src/i18n/en-US/index.ts

This PR is related to [#402](https://github.com/AstarNetwork/astar-apps/pull/402)
**Check list**
**Adds**
feat: added the max button on the XCM token transfer modal (native)
**Fixes**
fix: decimals calculation in transferAsset function
　* ref:  https://github.com/AstarNetwork/astar-apps/pull/401#discussion_r875445698
**Changes**
fix: removed faucet button

fix: XCM UI update

---

src/components/assets/XcmCurrency.vue
src/components/assets/styles/asset-list-xcm.scss
src/i18n/en-US/index.ts

* feat: added an external link for XCM asset balances 
**Check list**
**Adds**
* feat: added an external link for XCM asset balances
* demo: https://www.loom.com/share/dbfbbd16607b4d51bc33e1668675103c
**Todos**
* change the external link to Subscan once Subscan integrate XCM assets

feat: added an external link for XCM asset balances

---

src/hooks/helper/claim.ts

Fixed issue where developer rewards wasn't claimed because of bug.
After the fix we can see that staker and developer rewards where claimed
**Check list**
**Fixes**
- claim developer bug

Claim developer bug fix

---

src/components/assets/Erc20Currency.vue
src/components/assets/EvmAssetList.vue
src/components/assets/EvmCbridgeToken.vue
src/components/assets/NativeAssetList.vue
src/components/assets/XcmCurrency.vue
src/components/assets/modals/ModalEvmWithdraw.vue
src/components/assets/modals/ModalTransfer.vue
src/components/assets/modals/ModalVesting.vue
src/components/assets/modals/ModalXcmBridge.vue
src/components/assets/modals/ModalXcmTransfer.vue
src/hooks/helper/common.spec.ts
src/hooks/helper/common.ts

* fix: truncate token balances (instead of round numbers)
**Check list**
**Changes**
=Before=
=After=

fix: truncate token balances (instead of round numbers)

---

src/hooks/useClaimAll.ts

Manually added fast transactions for claim all. This is a temporary fix until we have a speed config modal for dApps Staking
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

claim all speed override

---

src/hooks/useExtensions.ts

**Check list**
the remaining issue with DApp connection (reproduced if user connected previously via MetaMask from mobile, and then tried to switch to Native connection (Nova/Math), results in Astar DApp wouldn't be able to connect to the mobile device via Polkadot JS protocol). New devices seems to connect, but as soon as you try to switch to EVM, you cannot go back to native option.

Fix nova wallet issue

---

src/modules/gas-api/index.ts
src/modules/gas-api/utils/index.ts

* config: update the 'gas station API' endpoint as per request from @niklabh 
**Check list**

fix: update the 'gas station API' endpoint

---

quasar.conf.js
src/boot/api.ts
src/index.template.html

SEO adding tags (twitter and tag manager)
**Check list**

Add seo twitter tag

---

src/components/assets/Account.vue
src/components/dapp-staking/StakePanel.vue
src/config/chainEndpoints.ts
src/hooks/custom-signature/message.ts
src/hooks/helper/claim.ts
src/hooks/useApr.ts
src/hooks/useClaimAll.ts
src/hooks/useGasPrice.ts
src/hooks/usePrice.ts
src/i18n/en-US/index.ts
src/modules/dapp-staking/utils/index.ts
src/store/dapp-staking/actions.ts

* feat: added 'Withdraw from unregistered dApps' UI
* demo: https://www.loom.com/share/8c139097c4044a24800a96be993fd6ff 
**Check list**
**Adds**
* feat: supports `withdraw_from_unregistered` transaction
**Fixes**
* fix (minor): type definition for local node network

feat: added 'Withdraw from unregistered dApps' UI

---

src/hooks/dapps-staking/useStakerInfo.ts
src/hooks/firebase/index.ts
src/store/dapp-staking/actions.ts

Fetches dapps from token-api instead of Firebase
**Check list**
**Changes**
- dapps source

Fetch dapps from token-api

---

src/components/assets/Account.vue
src/components/assets/XcmCurrency.vue
src/components/assets/modals/ModalTransfer.vue
src/components/assets/modals/ModalXcmTransfer.vue
src/components/dapp-staking/statistics/Withdraw.vue
src/components/header/modals/ModalAccount.vue
src/hooks/custom-signature/message.ts
src/hooks/custom-signature/useExtrinsicCall.ts
src/hooks/dapps-staking/useCompoundRewards.ts
src/hooks/useCustomSignature.ts
src/hooks/useEvmDeposit.ts
src/hooks/xcm/useXcmTokenDetails.ts
src/hooks/xcm/useXcmTokenTransfer.ts
src/i18n/en-US/index.ts

* refactor: localize the 'error' and 'toast' messages
* related: https://www.notion.so/astarnetwork/Portal-multi-language-ea533350a1be491cb7943f44914d2076 
* refactor: useXcmTokenDetails hooks
**Check list**

refactor: localize the error/toast messages

---

src/components/assets/NativeAssetList.vue
src/components/assets/modals/ModalTransfer.vue
src/components/assets/modals/ModalXcmBridge.vue
src/components/assets/modals/ModalXcmTransfer.vue
src/components/assets/styles/modal-transfer.scss
src/components/assets/styles/modal-xcm-bridge.scss
src/components/header/Header.vue
src/css/box.scss
src/css/color.scss
src/css/quasar.variables.scss
src/hooks/custom-signature/useExtrinsicCall.ts
src/hooks/useCustomSignature.ts
src/hooks/useEvmDeposit.ts
src/hooks/xcm/useXcmAssets.ts
src/hooks/xcm/useXcmBridge.ts
src/hooks/xcm/useXcmTokenTransfer.ts
src/i18n/en-US/index.ts

* feat update the `isDisabledBridge` logic for XCM EVM withdrawal
* feat: UI updates for error and warning messages
* related: https://www.notion.so/astarnetwork/Error-warning-message-update-cd4b355264664790a73eface770610a5 
* issue: https://github.com/AstarNetwork/astar-apps/issues/428
**Check list**
**Fixes**
* fix: update the requirement for the faucet request
* fix: timing for closing modals after sending transactions
* refactor: resolve vue warns (in console)
**Changes**

feat: UI updates for error and warning messages

---

src/boot/api.ts
src/components/header/modals/ModalAccount.vue
src/components/header/styles/modal-account.scss
src/css/app.scss
src/css/quasar.variables.scss
src/css/text.scss
src/hooks/helper/wallet.ts
src/hooks/transfer/useTransfer.ts
src/hooks/useBalance.ts
src/i18n/en-US/index.ts
src/modules/account/index.ts
src/modules/account/utils/index.ts
src/store/general/state.ts

* feat: updated the account drawer
* ticket: https://www.notion.so/astarnetwork/Wallet-drawer-improvement-sort-by-balance-6667df67247a42b5b3a61f374fd31b9e 
**Check list**
**Changes**
* added `Show balance` toggle
* sorted the account order by balance
=before=
=after=

feat: updated the account drawer

---

src/components/dapp-staking/DiscoverDappsTab.vue

Temporarily removed Register dapp button, because of security issue an added small info banner
**Check list**

Registration disabled info

---

package.json
src/App.vue
src/components/common/CookiePolicy.vue
src/config/localStorage.ts
src/i18n/en-US/index.ts
yarn.lock

> Add cookie policy component
**Check list**

add cookie policy component

---

src/components/assets/modals/ModalXcmBridge.vue
src/hooks/xcm/useXcmAssets.ts
src/hooks/xcm/useXcmBridge.ts
src/hooks/xcm/useXcmEvm.ts
src/i18n/en-US/index.ts
src/modules/xcm/tokens/index.ts

* feat: added `minimum transfer amount` for XCM bridge
* feat: disable withdrawal DOT temporary
* fix: error in `useXcmEvm.vue`
**Check list**
**Fixes**
* fix: error in `useXcmEvm.vue`
**Changes**

feat: added minimum transfer amount for XCM bridge

---

src/config/web3/contracts/xcm.ts
src/hooks/transfer/useTransfer.ts
src/hooks/xcm/useXcmEvm.ts
src/i18n/en-US/index.ts

* fix: remove the loading animation after H160 transaction has been completed
* demo:  https://www.loom.com/share/1ebc2cff544f47b3ab6c5d7e8605fa7d
**Check list**

fix: remove the loading animation after `H160 transaction` has been completed

---

src/components/assets/modals/ModalXcmBridge.vue
src/components/assets/styles/modal-xcm-bridge.scss
src/config/xcmChainEndpoints.ts
src/hooks/xcm/SubstrateApi.ts
src/hooks/xcm/useXcmBridge.ts
src/hooks/xcm/useXcmEvm.ts
src/i18n/en-US/index.ts

* feat: enabled DOT XCM withdrawal from both native and EVM Astar networks.
**Progress**
**Check list**
**Adds**
* feat: added a link to address format doc FAQ
* ticket: https://www.notion.so/astarnetwork/Adding-a-link-to-doc-FAQ-on-EVM-withdrawal-modal-2b84252475684bc3896682a381c13d34 
**Changes**
* fix: set the gas price for EVM withdrawal
* applied the gas price from gas-station API 
* fix: added tips into native withdrawal transaction 
* fix: updated tooltip
* ticket: https://www.notion.so/astarnetwork/Bug-fix-and-replace-a-warning-message-tooptip-0cc4767a3f6a4de18f19aee607d64bf3

feat: enabled DOT XCM withdrawal from both native and EVM Astar networks

---

src/components/assets/Erc20Currency.vue
src/hooks/xcm/useXcmEvm.ts
src/modules/xcm/index.ts

* feat: enabled HRMP EVM withdrawal function
Ref:
https://shiden.subscan.io/tx/0x2d1b32c183429b5d9f8798474d037bc56ea536711cfc81120ab992330d190ee9
**Check list**

feat: enabled HRMP EVM withdrawal function

---

src/v2/models/Asset.ts

* fix: applied `minBridgeAmount` to instantiate Asset instance 
* ref: https://stakesg.slack.com/archives/C03BN19LBQ8/p1658915776133239?thread_ts=1658908438.998829&cid=C03BN19LBQ8 
**Check list**
**Fixes**
=Before=
=After=

fix: applied `minBridgeAmount` to instantiate Asset instance

---

src/config/chainEndpoints.ts
src/hooks/useFaucet.ts

Fix broken link for faucet bot.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Faucet bot link

---

src/components/assets/Assets.vue
src/components/assets/EvmAssetList.vue
src/components/assets/EvmAssetOptions.vue
src/components/assets/NativeAssetList.vue
src/components/assets/modals/ModalEvmWithdraw.vue
src/components/assets/modals/ModalFaucet.vue
src/components/assets/modals/ModalImportTokens.vue
src/components/assets/modals/ModalTransfer.vue
src/components/assets/modals/ModalVesting.vue
src/components/assets/modals/ModalXcmBridge.vue
src/components/assets/modals/ModalXcmTransfer.vue
src/components/assets/styles/asset-list.scss
src/components/common/AlertBox.vue
src/components/common/AstarModal.vue
src/components/dapp-staking/DiscoverDappsTab.vue
src/components/sidenav/SidebarMobile.vue
src/components/sidenav/styles/sidebar-mobile.scss
src/css/app.scss
src/hooks/xcm/useXcmBridge.ts
src/i18n/en-US/index.ts

* fix: modified modal's z-index order
* related: https://github.com/AstarNetwork/astar-apps/pull/476
* fix: modified styling in 'Transferable balance' for mobile devices
* fix: existential deposit check in XCM transaction
**Check list**
**Fixes**
* fix: modified modal's z-index order
=Before=
=After=
* fix: modified styling in 'Transferable balance' for mobile devices
=Before=
=After=
* fix: existential deposit check in XCM transaction
=Before=
=After=

fix: modified z-index order in modals

---

src/components/assets/modals/ModalFaucet.vue
src/hooks/useEvmDeposit.ts

* refactor (EVM withdrawal): fetch the native token balance in the EVM network by Web3 instead of Polkadot.js API
* ref: https://stakesg.slack.com/archives/C02FLL6GQMD/p1659423492719319?thread_ts=1659419573.437429&cid=C02FLL6GQMD 
* fix (faucet modal): optimize the rendering effect of the faucet modal
* before: https://gyazo.com/d5f77b3f111e23398d38178e40057af0
* after: https://gyazo.com/27639a7aea73e8319000019637f7c9c6 
**Check list**

fix: fetch the native token balance in the EVM network by Web3 instead of Polkadot.js

---

src/components/assets/modals/ModalXcmBridge.vue

* fix: updated docs URL
**Check list**
**Fixes**

fix: updated docs URL

---

src/components/assets/Erc20Currency.vue
src/components/assets/NativeAssetList.vue
src/components/assets/XcmCurrency.vue
src/css/button.scss

* temp: disabled XCM transfer between Astar and Acala
**Check list**
**Changes**

temp: disabled XCM transfer between Astar and Acala

---

src/components/common/Modal.vue
src/components/common/ModalLoading.vue
src/modules/dapp-staking/utils/index.ts

* fix: remove the 'undefined' data return from 'formatStakingList' function properly
* related: https://github.com/AstarNetwork/astar-apps/pull/484 
**Check list**
**Fixes**
=Before=
=After=

fix: displaying dropdown menu for the nomination transfer UI properly

---

src/components/assets/modals/ModalFaucet.vue
src/i18n/en-US/index.ts

* fix: updated text on the faucet modal
**Check list**
**Fixes**
=Before=
=After=

fix: words on the Faucet modal

---

src/components/dapp-staking/modals/ModalRegisterDapp.vue
src/hooks/dapps-staking/useSignPayload.ts
src/hooks/index.ts
src/store/dapp-staking/actions.ts
src/store/dapp-staking/mutations.ts

Dapp registration workflow updated to follow changes on the backend side where register dapp call will approve developer and register the dapp to a node at once.
**Check list**
**Changes**
- dapp registration workflow

Dapp registration workflow update

---

src/c-bridge/index.ts
src/c-bridge/utils/token-detail/index.ts
src/components/assets/Account.vue
src/components/assets/Assets.vue
src/components/assets/EvmAssetList.vue
src/components/assets/EvmCbridgeToken.vue
src/components/assets/NativeAssetList.vue
src/components/assets/transfer/Transfer.vue
src/config/web3/abi/xcm-moonbeam-withdrawal-abi.json
src/hooks/useBalance.ts
src/hooks/xcm/useTransferRouter.ts
src/hooks/xcm/useXcmEvm.ts
src/modules/token/index.ts
src/modules/token/utils/index.ts
src/modules/xcm/tokens/index.ts
src/store/assets/actions.ts
src/store/assets/state.ts
src/v2/repositories/IEvmAssetsRepository.ts
src/v2/repositories/implementations/EvmAssetsRepository.ts

* feat: Enabled EVM XCM withdrawal for MOVR 
**Check list**
**Adds**

feat: enabled EVM XCM withdrawal for MOVR

---

src/components/header/HeaderComp.vue

Remove unnecessary css for Firefox

Remove css for FF

---

src/components/dapp-staking/modals/ModalRegisterDapp.vue

Added new dapp registration workflow support for Shiden.
**Check list**
**Adds**
- new dapp registration workflow for Shiden

Enable new dapp registration workflow on Shiden

---

package.json
yarn.lock

feat: updated the version of Astar-UI
**Check list**

feat: updated the version of Astar-UI

---

src/modules/transfer/faq/index.ts

* fix: updated FAQ urls
**Check list**

fix: modified link urls

---

src/components/dapp-staking/modals/ModalRegisterDapp.vue

The PR enables a new dapp registration workflow on Astar which is supported by today's runtime upgrade.
**Check list**
**Changes**
- dapp registration workflow for Astar

Enable new dapps registration workflow on Astar

---

src/v2/messaging/ExtrisniscStatusMessage.ts
src/v2/services/IWalletService.ts
src/v2/services/implementations/MetamaskWalletService.ts
src/v2/services/implementations/PolkadotWalletService.ts
src/v2/services/implementations/XcmEvmService.ts
src/v2/test/mocks/services/WalletServiceMock.ts

Wallet services to return transaction hash

Wallet services to return transaction hash

---

src/v2/models/XcmModels.ts
src/v2/models/index.ts
src/v2/services/IXcmService.ts
src/v2/services/implementations/XcmService.ts

Changed XcmService logic to be @polkadot/api independent

Refacotring to make tests pass

---

src/hooks/xcm/useXcmBridgeV3.ts
src/v2/config/types/TypeMapping.ts
src/v2/config/xcm/XcmRepositoryConfiguration.ts
src/v2/repositories/IXcmRepository.ts
src/v2/repositories/implementations/XcmRepository.ts
src/v2/repositories/implementations/index.ts
src/v2/repositories/implementations/xcm/AcalaXcmRepository.ts
src/v2/repositories/implementations/xcm/MoonbeamXcmRepository.ts
src/v2/repositories/implementations/xcm/PolkadotXcmRepository.ts
src/v2/repositories/implementations/xcm/StatemintXcmRepository.ts
src/v2/services/IXcmService.ts
src/v2/services/implementations/XcmService.ts
src/v2/test/mocks/repositories/XcmRepositoryMock.ts

Implemented above mentioned methods in
- XcmService
- existing XCM repositories
changed useXcmBridgeV3 to use those methods

getTokenBalance and getNativeBalance refactoring

---

src/c-bridge/index.ts
src/c-bridge/utils/cbridgeAPI/index.ts
src/c-bridge/utils/index.ts
src/c-bridge/utils/token-detail/index.ts
src/components/assets/EvmCbridgeToken.vue
src/components/dashboard/BlockPanel.vue
src/modules/token/utils/index.ts
src/v2/repositories/implementations/EvmAssetsRepository.ts

* fix: renamed Celer `USDT` to `ceUSDT`
* ref: [docs](https://docs.astar.network/docs/integrations/bridges/cbridge/#the-difference-betweeen-usdt-vs-bridgedusdt)
* fix: renamed Celer `USDC` to `ceUSDC`
**Check list**
**Changes**
=Before=
=After=

fix: renamed celer USDT to ceUSDT

---

src/components/assets/Assets.vue
src/modules/token/index.ts
src/modules/token/utils/index.ts
src/v2/repositories/implementations/EvmAssetsRepository.ts

*  refactor: removed hard-coded XC20 metadatas
* this change makes developers skip the registering XC20 tokens step when they create a PR for XCM integration  
**Check list**

refactor: removed hard-coded XC20 metadatas

---

src/components/dashboard/CirculatingPanel.vue
src/components/dashboard/Dashboard.vue

Fix for invalid circulating supply display on the portal dashboard
BEFORE
AFTER
**Check list**
**Fixes**
- circulating supply display

Circulating supply display fix

---

src/modules/xcm/index.ts

Changed Acala wss endpoint.
Karura endpoint is ok.

Acala endpoint change

---

src/components/assets/transfer/Transfer.vue
src/hooks/xcm/useTransferRouter.ts

* fix enabled xcm transfer for Acala tokens
Memo: fix depositing ASTR from Acala to Astar 
**Check list**

fix enabled xcm transfer for Acala tokens

---

package.json
yarn.lock

> fixed svg of icon-copy component

upgrade specific version of ui lib

---

src/components/common/TokenBalance.vue
src/components/dapp-staking-v2/my-staking/MyRewards.vue
src/hooks/dapps-staking/useStakerInfo.ts

* feat: updated total staked panel
**Check list**
**Adds**

feat: updated total staked panel

---

src/hooks/dapps-staking/useStakerInfo.ts

* fix: removed an error notification on the top page
**Check list**
**Fixes**
=Before=
=After=

fix: removed an error notification on the top page

---

src/components/dapp-staking-v2/my-staking/MyRewards.vue
src/components/dapp-staking-v2/my-staking/components/CardList.vue
src/components/dapp-staking/dapp/DappAvatar.vue
src/components/dapp-staking/dapp/styles/dapp-avatar.scss
src/components/dapp-staking/dapp/styles/project-details.scss
src/components/dapp-staking/dapp/styles/project-overview.scss
src/hooks/dapps-staking/useStakerInfo.ts
src/i18n/en-US/index.ts
src/pages/DappPage.vue
src/router/routes.ts

* feat: link to the dApp page
* fix: updated styles on the dApp page
* feat: link to edit page from the dApp page
**Check list**
**Adds**
* feat: link to the dApp page
Demo:
https://gyazo.com/9e7cd476cad532fd4159b7ae7d50758d
* feat: link to edit page from the dApp page
Demo:
https://gyazo.com/da7827da7f0b40443671c8b0c45b220b

feat: link to the dApp page

---

src/components/dapp-staking-v2/my-staking/MyDapps.vue
src/components/dapp-staking-v2/my-staking/components/modals/ModalUnbondDapp.vue
src/hooks/dapps-staking/useStakerInfo.ts
src/hooks/dapps-staking/useUnbond.ts
src/hooks/index.ts
src/i18n/en-US/index.ts
src/store/dapp-staking/getters.ts
src/v2/repositories/IDappStakingRepository.ts
src/v2/repositories/implementations/DappStakingRepository.ts
src/v2/repositories/implementations/MetadataRepository.ts
src/v2/services/IDappStakingService.ts
src/v2/services/implementations/DappStakingService.ts
src/v2/test/mocks/repositories/DappStakingRepositoryMock.ts

Unbond dialog
**Check list**
**Adds**
- Unbonding dialog
- Navigation to stake page from myDapps Add button

Add unbond modal

---

src/hooks/xcm/useXcmBridgeV3.ts

* fix: use `watch` instead of `watchEffect` for `setErrMsg` function
* small refactoring
**Check list**

fix: use `watch` instead of `watchEffect` for setErrMsg function

---

src/components/dapp-staking-v2/StakingTop.vue
src/components/dapp-staking-v2/my-staking/components/CardList.vue
src/css/quasar.variables.scss

* fix: modified styles on dApp cards
* Related: https://github.com/AstarNetwork/astar-apps/pull/547#discussion_r1005158495
**Check list**
**Fixes**
=Before=
=After=

fix: modified styles on the dAppList component

---

src/components/dapp-staking-v2/my-staking/components/modals/ModalUnbondDapp.vue
src/components/dapp-staking/RegisterDapp.vue
src/components/dapp-staking/dapp/DappAvatar.vue
src/hooks/useClaimAll.ts
src/modules/dapp-staking/utils/index.ts

Fixed errors on staging env I noticed in debug console
Removed dapp edit button if user is not dapp owne
Unbonding modal - fixed components order, alignment and button text size
**Check list**
**Adds**
**Fixes**
- errors
**Changes**
- removed dapp edit button if user is not dapp owne
**To-dos**

V2 errors fix

---

src/components/dapp-staking-v2/my-staking/TopMetric.vue
src/components/dapp-staking-v2/my-staking/styles/top-metric.scss

* fix: TopPanel styling
**Check list**
**Fixes**
=Before=
=After=

fix: TopPanel styling

---

src/components/dapp-staking/dapp/Dapp.vue
src/components/dapp-staking/dapp/styles/dapp-images.scss
src/hooks/index.ts
src/hooks/ui/usePageReady.ts
src/pages/DappPage.vue
src/pages/Dashboard.vue

* fix: improved styling in dapp images
**Check list**
**Fixes**
=Before=
=After=

fix: improved styling in dapp images

---

package.json
src/components/dapp-staking/dapp/Builders.vue
src/components/dapp-staking/dapp/ProjectDetails.vue
src/components/dapp-staking/dapp/styles/builders.scss
src/components/dapp-staking/dapp/styles/project-details.scss
src/i18n/en-US/index.ts
yarn.lock

* feat: fetch the data for Teams UI
* feat: fetch the data for ProjectDetails UI
**Check list**
**Adds**
* feat: fetch the data for Teams UI
* feat: fetch the data for ProjectDetails UI

feat: fetch the data for Teams and ProjectDetails UI

---

src/components/dapp-staking-v2/my-staking/DappList.vue
src/components/dapp-staking-v2/my-staking/MyDapps.vue
src/components/dapp-staking-v2/my-staking/components/modals/ModalUnbondDapp.vue
src/components/dapp-staking/register/ModalAddDeveloper.vue
src/i18n/en-US/index.ts

Fixed z-order of unbonding dialog during unbonding operation
Added image uplaod info
Hide category if no dapps
BEFORE
AFTER
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Unbonding dialog and other fixes

---

src/components/common/Logo.vue
src/components/dapp-staking-v2/my-staking/components/CardList.vue
src/hooks/useNetworkInfo.ts

> Fixed :  https://www.notion.so/astarnetwork/Shibuya-logo-appeared-first-before-Astar-logo-a37ecc46dc02474f879b54a29690d63e
**Check list**

Fix - Shibuya logo appeared first before Astar logo

---

src/components/dapp-staking-v2/StakingTop.vue
src/components/dapp-staking-v2/my-staking/DappList.vue
src/components/dapp-staking/dapp/Dapp.vue
src/components/dapp-staking/stake-manage/StakeManage.vue
src/components/dapp-staking/statistics/DappsCount.vue
src/hooks/dapps-staking/useCompoundRewards.ts
src/hooks/dapps-staking/useDappRedirect.ts
src/hooks/dapps-staking/useStakingList.ts
src/hooks/useApr.ts
src/hooks/useBalance.ts
src/hooks/useClaimAll.ts

* fix: avoid displaying `dapp: undefined` dapps on the dApp staking top page
* fix: added type annotation to `dapps` state
**Check list**
**Fixes**
=Before=
=After=

fix: avoid displaying `dapp: undefined` dapps on the dApp staking top page

---

src/components/dapp-staking-v2/my-staking/components/CardList.vue

* styles: added hover animation on the DappCard
* before: https://gyazo.com/8a0356dd03d34f33c174ae21fb95e742
* after: https://gyazo.com/3b9bf300f89e5b5c3205a0a7cc456b20
**Check list**

styles: added a hover animation on the DappCard

---

src/components/dapp-staking-v2/StakingTop.vue
src/components/dapp-staking-v2/my-staking/OnChainData.vue
src/components/dapp-staking-v2/my-staking/styles/on-chain-data.scss
src/hooks/helper/common.ts
src/i18n/en-US/index.ts

* feat: added On Chain Data panel
**Check list**
**Adds**
* feat: added On-Chain Data panel

feat: added `On-Chain Data` panel

---

.github/workflows/firebase-hosting-merge.yml
.github/workflows/firebase-hosting-pull-request.yml

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Using Node version 18 for build

---

.github/workflows/create-release.yml
.github/workflows/deploy-to-production.yml

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Placeholder scripts to create workflow actions

---

src/components/assets/transfer/styles/local-transfer.scss
src/components/assets/transfer/styles/xcm-bridge.scss
src/components/dapp-staking/dapp/Dapp.vue
src/components/dapp-staking/dapp/styles/dapp.scss
src/pages/Transfer.vue

* fix: modified styling of buttons
**Check list**
**Fixes**
=Before=
=After=
=Before=
=After=

fix: modified styling of buttons

---

src/v2/repositories/implementations/xcm/CrustShadowXcmRepository.ts

https://github.com/AstarNetwork/astar-apps/pull/554#issuecomment-1328586004

Fix asset type query

---

src/modules/xcm/index.ts
src/modules/xcm/tokens/index.ts
src/v2/config/xcm/XcmRepositoryConfiguration.ts
src/v2/models/XcmModels.ts
src/v2/repositories/implementations/xcm/PhalaXcmRepository.ts

> Integrate Phala chain, allow transferring PHA and ASTR between Phala and Astar
**Check list**
Changes refer to https://github.com/AstarNetwork/astar-apps/pull/552, tested in local environment.

feat: phala integration

---

src/components/common/PieChart.vue
src/components/dapp-staking-v2/my-staking/TopMetric.vue
src/components/dapp-staking-v2/my-staking/styles/top-metric.scss
src/i18n/en-US/index.ts

* feat: updated `Top Metric` panel
* feat: added ETA for the next era on the `Current Era` panel
* feat added progress pie chart on the `Current Era` panel 
* feat: displays APY on the `Stakers Rewards` panel 
**Check list**
**Adds**
=Before=
=After=

feat: updated `Top Metric` panel

---

src/config/api/polkadot/connectApi.ts

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

check if isSubstrateConnectInstalled

---

src/components/assets/EvmAssetList.vue
src/components/assets/NativeAssetList.vue
src/components/assets/modals/ModalFaucet.vue
src/components/assets/styles/modal-evm-withdraw.scss
src/components/assets/styles/modal-faucet.scss
src/components/assets/styles/modal-vesting.scss
src/components/assets/transfer/styles/information.scss
src/components/assets/transfer/styles/input-select-chain.scss
src/components/assets/transfer/styles/local-transfer.scss
src/components/assets/transfer/styles/xcm-bridge.scss
src/components/common/styles/speed-configuration.scss
src/components/dapp-staking-v2/dapp/styles/dapp-images.scss
src/components/dapp-staking-v2/stake-manage/styles/stake-form.scss
src/components/dapp-staking-v2/stake-manage/styles/stake-information.scss
src/components/dapp-staking/stake-manage/StakeForm.vue
src/components/dapp-staking/stake-manage/styles/stake-form.scss
src/components/dapp-staking/stake-manage/styles/stake-information.scss
src/config/wallets.ts
src/css/astar-ui.scss
src/css/modal.scss
src/hooks/useFaucet.ts
src/i18n/en-US/index.ts

* feat: display the remaining funds of the faucet account
* refactor: refactored features around the faucet UI
* fix: updated styling of all the modals
**Check list**
**Adds**
* feat: display the remaining funds of the faucet account

feat: display the remaining funds of the faucet account

---

src/config/api/polkadot/connectApi.ts

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Lightclient

---

src/hooks/useClaimAll.ts

Disable reward destination change for developers on claim all action. If current user is developer `NotActiveStaker` error is raised when claim all operation tires to change reward destination.
UPDATE. The whole concept of changing reward destination before claiming was wrong because it confuses users as their rewards goes to balance instead they are re-staked. In this PR I disabled the feature and I will do different approach. In the next PR I will just warn users to turn off auto restaking if they can't claim because of too many unclaimed eras 
**Check list**

Don't change reward destination for developers on claim all

---

src/hooks/xvm/useXvmTokenTransfer.ts

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Gas estimate

---

src/components/dapp-staking/my-staking/BannerArea.vue
src/components/dapp-staking/my-staking/components/banners/DeveloperIncentive.vue
src/components/dapp-staking/my-staking/styles/my-rewards.scss
src/components/dapp-staking/my-staking/styles/my-staking.scss
src/components/dapp-staking/my-staking/styles/on-chain-data.scss
src/components/dapp-staking/my-staking/styles/top-metric.scss

[> Fix padding on dapp top page](https://www.notion.so/astarnetwork/Fix-paddings-on-dApp-Top-page-d12366a4a3c44376b4c1fc96c11d9a4c)
**Check list**

Fix padding on dapp top page

---

.github/PULL_REQUEST_TEMPLATE.md

* added `Nodes for release notes` section in the pull request template file
**Check list**

config: added 'nodes for release notes' section in the PR template file

---

.eslintrc.js
src/components/assets/Assets.vue
src/components/assets/Erc20Currency.vue
src/components/assets/EvmAssetOptions.vue
src/components/assets/EvmCbridgeToken.vue
src/components/assets/XcmCurrency.vue
src/components/assets/XcmNativeAssetList.vue
src/components/assets/transfer/InputSelectChain.vue
src/components/assets/transfer/LocalTransfer.vue
src/components/assets/transfer/ModalSelectToken.vue
src/components/assets/transfer/Transfer.vue
src/components/assets/transfer/XcmBridge.vue
src/components/dapp-staking/dapp/DappStatistics.vue
src/components/dapp-staking/my-staking/BannerArea.vue
src/components/dapp-staking/my-staking/OnChainData.vue
src/components/dapp-staking/my-staking/TopMetric.vue
src/components/dapp-staking/stake-manage/SelectFunds.vue
src/components/header/Header.vue
src/components/header/NetworkButton.vue
src/components/header/modals/ModalAccount.vue
src/components/header/modals/SelectWallet.vue
src/components/sidenav/SidebarDesktop.vue
src/components/sidenav/SidebarMobile.vue
src/components/sidenav/SidebarOption.vue
src/layouts/DashboardLayout.vue

* refactor: added eslint casing format check for component names
* issue: https://github.com/AstarNetwork/astar-apps/pull/533#discussion_r991759326 
* ref: https://eslint.vuejs.org/rules/component-name-in-template-casing.html
**Check list**
configuration: added eslint casing format check for component names
**Adds**
* feat: added eslint casing format check for component names
* format to kebab-case by `yarn lint`
* casing format check on code edditor

refactor: added eslint casing format check for component names

---

src/config/api/polkadot/connectApi.ts

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

remove if substrate_connect because it works with and without

---

src/components/dapp-staking/my-staking/OnChainData.vue

* fix: removed 'Unregistered' dApps from the on-chain-data panel
**Check list**
* fix: removed 'Unregistered' dApps from the on-chain-data panel
**Fixes**
=Before=
=After=

fix: removed unregistered dapps from onchain-data panel

---

src/components/dapp-staking/my-staking/TopMetric.vue
src/components/dapp-staking/my-staking/styles/top-metric.scss

- Remove snowpack
- Put space on tvl text
**Check list**
-  fix: snowpack & put space on tvl text

Fade away snow & put space on tvl text

---

src/hooks/dapps-staking/useStakerInfo.ts
src/modules/dapp-staking/utils/index.ts
src/v2/repositories/IDappStakingRepository.ts
src/v2/repositories/implementations/DappStakingRepository.ts
src/v2/services/IDappStakingService.ts
src/v2/services/implementations/DappStakingService.ts
src/v2/test/mocks/repositories/DappStakingRepositoryMock.ts
src/v2/test/services/DappStakingService.spec.ts

refactor useStakerInfo hook with v2 architecture .
related #662 
**Check list**

refactor useStakerInfo hook

---

src/components/common/Logo.vue

> Go back logo from winter logo
**Check list**

Go back logo

---

src/components/common/ChartPanel.vue
src/components/dapp-staking/dapp/Dapp.vue
src/components/dapp-staking/dapp/DappStatsCharts.vue
src/components/dapp-staking/dapp/StatsChart.vue
src/modules/token-api/index.ts
src/modules/token-api/utils/index.ts

Changed endpoint used to fetch dapp stats to ones that provides DappRadar stats.
**Check list**
- Added dapp statistics

Display dapp stats

---

src/components/dapp-staking/dapp/DappAvatar.vue

* refactor: refactored the `stake` button on the dApp page
**Check list**

refactor: refactored the stake button on the dApp page

---

src/hooks/dapps-staking/useCompoundRewards.ts
src/hooks/dapps-staking/useUnbonding.ts
src/hooks/useCustomSignature.ts
src/hooks/useFaucet.ts
src/store/general/actions.ts

- Hide notification toast automatically 
- set txHash for success notification
**Check list**
- feat: hide notification automatically

Hide notification automatically

---

src/hooks/transfer/useTokenTransfer.ts

Reverted useTokenTransfer hook because of bug with EVM to native transfer
**Check list**
- EVM to native transfer bug fix

Reverted useTokenTransfer hook

---

src/components/dapp-staking/my-staking/OnChainData.vue
src/hooks/dapps-staking/useNominationTransfer.ts
src/hooks/dapps-staking/useStake.ts
src/hooks/useChainInfo.ts

* fix: displays the native token symbol on the toast
**Check list**
fix: displays the native token symbol on the toast
**Fixes**
fix: displays the native token symbol on the toast
=Before=
=After=

fix: displays the native token symbol on the toast

---

src/components/common/Logo.vue
src/components/sidenav/styles/sidebar-desktop.scss
src/layouts/DashboardLayout.vue

Remove lunar theme
**Check list**
- remove: lunar theme

Remove lunar theme

---

src/v2/repositories/implementations/xcm/AcalaXcmRepository.ts

* fix: updated parameters for sending XCM deposit (Acala) transaction 
**Check list**
* fix: updated parameters for sending XCM deposit (Acala) transaction
**Fixes**
* fix: updated parameters for sending XCM deposit (Acala) transaction
=Ref=
https://acala.subscan.io/extrinsic/2907928-3
=Before=

fix: updated parameters for sending XCM deposit (Acala) transaction

---

package.json

Changed package name to @astar-network/astar-portal.
**Check list**

Changed package name to @astar-network/astar-portal

---

LICENSE

Added GPL v3 LICENSE

---

src/i18n/fr/index.ts

- Review of the French version of the Astar portal
- Modification of some words for a more accurate and correct translation
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Update of the French version of the Astar portal

---

src/config/chainEndpoints.ts

* fix: removed pinknode endpoints
* feat: added Blast endpoints

fix: removed pinknode endpoints

---

src/config/chainEndpoints.ts

* fix: updated Astar endpoint 
* updated from  wss://wss.astar.network to wss://rpc.astar.network

fix: updated wss endpoint for astar node

---

src/components/dapp-staking/my-staking/DynamicAdsArea.vue
src/components/dapp-staking/my-staking/components/NewsArea.vue
src/modules/xcm/index.ts

* fix: importing function error
* build log (failed): https://github.com/AstarNetwork/astar-apps/actions/runs/4283084150/jobs/7458347233#step:4:94 
* fix: modified Moonbeam logo
**Check list**
* fix: modified Moonbeam logo
=Before=
=After=

fix: importing functions from astar-js

---

quasar.conf.js
src/components/dapp-staking/my-staking/DynamicAdsArea.vue
src/components/dapp-staking/my-staking/components/NewsArea.vue
src/components/header/modals/ModalNetwork.vue
src/data/news.json
src/router/utils/index.ts

* feat: removing `#` from the url address
**Check list**
**Changes**
The production URL will be changed from `https://portal.astar.network/#/astar/assets` to `https://portal.astar.network/astar/assets`

feat: removing `#` from the url address

---

package.json
src/components/assets/NativeAssetList.vue
src/pages/AssetsPage.vue
src/pages/DappStaking.vue
src/pages/RegisterDapp.vue
src/pages/StakeManage.vue
yarn.lock

* feat: improved loading speed for google icons 
* ref: https://github.com/AstarNetwork/astar-ui/pull/54  
**Check list**

feat: improved loading speed for google icons 

---

src/components/common/ChartPanel.vue
src/components/common/styles/chart-panel.scss
src/components/dashboard/Dashboard.vue
src/components/dashboard/TvlChart.vue
src/hooks/useTvlHistorical.ts

TVL value displayed in native token
**Check list**
- displayed TVL valued in native token on Dashboard page

Display TVL in native tokens on dashboard page

---

src/components/common/Notification/NotificationBar.vue
src/components/dapp-staking/stake-manage/StakeForm.vue
src/components/dapp-staking/stake-manage/styles/stake-form.scss
src/components/header/Header.vue
src/i18n/en-US/index.ts

- Can the ‘s’ not be separated from ‘wallets”?
- Need improvement on the appearing and disappearing sequence/effect of the wallet & network selection menus.
- Error styling for the light theme is not implemented.
**Check list**

Fix/release v0.0.22

---

src/components/dapp-staking/my-staking/components/NewsArea.vue

**Check list**
filter out hidden posts from the news feed

Update NewsArea.vue to filter out hidden posts from the news feed

---

src/config/web3/utils/index.ts
src/hooks/types/CustomSignature.ts

* fix: updated logic for the switching network by EVM wallets 
**Check list**
* fix: updated logic for the switching network by EVM wallets 
**Fixes**
* fix: updated logic for the switching network by EVM wallets

fix: updated logic for the switching network by EVM wallets 

---

src/components/assets/transfer/LocalTransfer.vue
src/components/assets/transfer/styles/local-transfer.scss
src/hooks/transfer/useTokenTransfer.ts
src/i18n/en-US/index.ts

* feat: added warning checkbox for transfer tokens to EVM wallet addresses
**Check list**
* feat: added a checkbox for transfer tokens to EVM wallet addresses
**Adds**
* feat: added a checkbox for transfer tokens to EVM wallet addresses

feat: added a checkbox for transfer tokens to EVM wallet addresses

---

src/c-bridge/index.ts

* fix: updated endpoint for cBridge API
**Check list**

fix: updated endpoint for cBridge API

---

src/config/chainEndpoints.ts

> Adding RadiumBlock  Astar Endpoint Accelerator
**Check list**
**Adds**
- RadiumBlock Astar Endpoint Accelerator
**Fixes**
**Changes**
**To-dos**

Adding RadiumBlock Astar Endpoint Accelerator

---

quasar.conf.js
src/boot/api.ts
src/components/header/modals/ModalAccount.vue
src/hooks/useConnectWallet.ts

* fix: modified condition for displaying wallet authorization popup
**Check list**
* fix: modified condition for displaying wallet authorization popup
**Changes**
* fix: modified condition for displaying wallet authorization popup
* before: Substrate wallets display authorization popup even through users select EVM wallets
* demo: https://gyazo.com/ea5edcf20ff31453a867acc9d4bc2bb5 
* after: the popup will be displayed only when users select substrate wallets
* demo: https://www.loom.com/share/51c2302561d045359628c1497353d357

fix: modified condition for displaying wallet authorization popup

---

src/components/common/ConnectionTrouble.vue
src/components/common/ModalConnectionTrouble.vue
src/components/common/ModalWrapper.vue
src/components/common/styles/modal-connection-trouble.scss
src/components/sidenav/SidebarDesktop.vue
src/components/sidenav/SidebarOption.vue
src/components/sidenav/styles/sidebar-desktop.scss
src/i18n/en-US/index.ts
src/links/index.ts
tsconfig.json

* feat: added connection troubles modal
**Check list**
* feat: added connection troubles modal
**Adds**
* feat: added connection troubles modal

feat: added `Connection troubles` modal

---

src/components/assets/transfer/LocalTransfer.vue
src/hooks/transfer/useTokenTransfer.ts

* fix: updated checkbox condition for the EVM transfer
**Check list**
**Fixes**
* fix: updated checkbox condition for the EVM transfer
* since GMO and GATE accept deposits on the EVM network, we don't need a checkbox for native token transfer on EVM mode.
=before= 
=after=

fix: updated checkbox condition for the EVM transfer

---

src/components/dapp-staking/my-staking/AdsArea.vue
src/components/dapp-staking/my-staking/DappList.vue
src/components/dapp-staking/my-staking/MyStaking.vue
src/components/dapp-staking/my-staking/components/CardList.vue
src/components/dapp-staking/my-staking/styles/dynamic-ads-area.scss
src/components/dapp-staking/my-staking/styles/my-staking.scss
src/components/dapp-staking/my-staking/styles/on-chain-data.scss
src/layouts/DashboardLayout.vue
src/pages/AssetsPage.vue
src/pages/DappPage.vue
src/pages/Dashboard.vue
src/pages/StakeManage.vue

- Fix shadow on dapp card
- remove right margin on dapp list in mobile view
- make a double column
(enhancement - update styling on dappstaking)
**Check list**

enhancement - update styling on dappstaking

---

src/modules/playwright/index.ts
tests/dappstaking.spec.ts
tests/dashboard.spec.ts
tests/sidebar.spec.ts

* feat: added UI test for 'sidebar'
**Check list**
* feat: added UI test for sidebar
**Adds**
* feat: added UI test for sidebar
**Changes**
* refactor: created 'playwright' module and moved reusable functions to it.

feat: added UI test for 'sidebar'

---

README.md
src/links/index.ts

Updated Discord invitation ling
**Check list**
- Discord invitation link update

Discord invitation link update

---

src/c-bridge/index.ts
src/c-bridge/utils/cbridgeAPI/index.ts
src/components/assets/Erc20Currency.vue
src/modules/token/index.ts
src/modules/token/utils/index.ts
tests/fixtures.ts
tests/polkadot_wallet/packageInfo.d.ts

* feat: added Injective assets (ATOM and INJ) on EVM assets page
**Check list**
* feat: added Injective assets (ATOM and INJ) on EVM assets page
**Adds**
* feat: added Injective assets (ATOM and INJ) on EVM assets page

hotfix: added Injective assets (ATOM and INJ) on EVM assets page

---

.github/workflows/broken-links.yml
.lycheeignore
README.md

This PR adds a github action which check for broken links in the repo. It will check all repository links once per day and create an issue in case of errors.
**Check list**
- broken links check
**Adds**
- broken links check

Added github action for broken links

---

.github/workflows/broken-links.yml

Run broken links report monthly
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Run broken links report monthly

---

.lycheeignore

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

removed quasar from broken link report

---

src/components/assets/DynamicLinks.vue
src/data/dynamic_links.json

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Using the last post of astar blog as the 4th card

---

src/components/assets/transfer/LocalTransfer.vue
src/components/assets/transfer/styles/local-transfer.scss
src/i18n/en-US/index.ts

Change warning on EVM local transfer
**Check list**

Change warning on EVM local transfer

---

src/components/assets/Assets.vue
src/components/assets/styles/assets.scss
src/components/header/ConnectButton.vue
src/components/header/Header.vue
src/components/sidenav/styles/sidebar-mobile.scss

* fix: modified header styling for mobile devices
**Check list**
=Before=
=After=

fix: modified header styling for mobile devices

---

.github/workflows/s3-hotfix.yml
.github/workflows/s3-production.yml

Automatically create PR on release and hotfix release actions to keep `main` and `release-hotfix` branches up to date.
**Check list**
- Automatically create PR on regular and hotfix portal release

Automatically create PR on regular and hotfix release

---

src/config/chainEndpoints.ts

Return Dwellir endpoint to the portal
**Check list**

Return Dwellir endpoint to the portal

---

.github/workflows/s3-hotfix.yml
.github/workflows/s3-production.yml

Fix for issue https://github.com/AstarNetwork/astar-apps/actions/runs/4979894814/jobs/8912076856
caused by #781 
**Check list**

Deployment scripts fix

---

src/index.template.html

* fix: fixed conflicts in https://github.com/AstarNetwork/astar-apps/pull/799

fix: fixed conflicts in release-hotfix branch

---

src/components/assets/NativeAssetList.vue
src/components/assets/styles/asset-list.scss

* fix: modified the position for EVM withdrawal
**Check list**
**Changes**
* fix: modified the position for EVM withdrawal
=Before=
=After=

fix: modified the position for EVM withdrawal

---

src/App.vue
src/components/assets/Assets.vue
src/components/assets/styles/assets.scss
src/components/assets/styles/dynamic-links.scss
src/components/common/Notification/NotificationStack.vue
src/components/common/decentralised-banner.vue
src/components/common/decentralized-banner.vue
src/components/dapp-staking/StakingTop.vue
src/components/header/HeaderComp.vue
src/components/sidenav/SidebarDesktop.vue
src/components/sidenav/styles/sidebar-desktop.scss
src/css/quasar.variables.scss
src/i18n/en-US/index.ts
src/links/index.ts

* feat: added decentralized banner
* staging for decentralized banner: astar-portal-melvif4ls-impelcrypto.vercel.app  @Kahonnohak 
* fix: modified styling bugs
**Check list**
**Adds**
* feat: added decentralized banner
**Fixes**
* fix: modified styling bugs
=Before=
=After=

feat: added decentralised banner

---

.github/workflows/broken-links.yml

Added md and json files to broken link check
**Check list**

Added md and json files to broken link check

---

src/config/api/polkadot/chain-specs/astar.json
src/config/api/polkadot/chain-specs/shibuya.json
src/config/api/polkadot/chain-specs/shiden.json

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

update bootnodes dns

---

src/components/assets/NativeAssetList.vue
src/components/assets/styles/asset-list.scss
src/components/assets/transfer/styles/local-transfer.scss
src/components/assets/transfer/styles/xcm-bridge.scss
src/components/common/LightDarkMode.vue
src/components/common/styles/speed-configuration.scss
src/components/dapp-staking/my-staking/OnChainData.vue
src/components/dapp-staking/stake-manage/styles/stake-form.scss
src/hooks/dapps-staking/useStakerInfo.ts
src/hooks/useClaimAll.ts

* fix: modified 'input' width size for small screen devices
* fix: align buttons on assets page for small screen devices
* fix: modified icon color (theme changer) when light theme
* fix: load user's stake data when the page was opened from other than dApp staking page (e.g.: Assets -> dApp Staking)
* fix: round up the number of total page on On-Chain Data panel
**Check list**
**Fixes**
=Before=
=After=

fix: modified stylings for small screen devices

---

src/components/dapp-staking/my-staking/MyRewards.vue
src/hooks/useClaimAll.ts
src/i18n/en-US/index.ts

* fix: modified "claim rewards box" for dApp developer
**Check list**
**Changes**
* fix: modified "claim rewards box" for dApp developer
If connected account is a 'dApp developer'
If connected account is a 'Staker' (the UI is the same as current)

fix: modified "claim rewards box" for dApp developer

---

src/components/assets/DynamicLinks.vue
src/data/dynamic_links.json

Remove decentralized banner
**Check list**

Remove decentralized banner

---

src/config/api/polkadot/chain-specs/astar.json

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

chore: add Astar OnFinality's dedicated bootnodes

---

src/hooks/xcm/useTransferRouter.ts

* hotfix: disabled XCM with Interlay and Kintsugi
* will update their XCM logic to V3 this month 
**Check list**

hotfix: disabled XCM with Interlay and Kintsugi

---

README.md
src/boot/portalV2.ts
src/v2/repositories/implementations/XcmRepository.ts

fix: filters xcm assets under "custom network" 
fix: updates "readme"
**Check list**
**Fixes**
=Before=
=After=

fix: filters xcm assets under "custom network"

---

src/hooks/xcm/useXcmBridge.ts
src/i18n/en-US/index.ts
src/v2/repositories/implementations/XcmRepository.ts
src/v2/repositories/implementations/xcm/StatemintXcmRepository.ts

Statemint
* fix: uses XCM V3 code for sending XCM transactions from Polkadot and Statemint
* fix: added an error message for users who don't have native token balance when depositting the tokens
**Check list**
**Fixes**
* fix: uses XCM V3 code for sending XCM transactions from Polkadot and Statemint
=Before=
=After=
* fix: added an error message for users who don't have native token balance when depositting the tokens

fix: uses XCM V3 code for sending XCM transactions from Polkadot and Statemint

---

tests/assets-transactions-evm.spec.ts
tests/chopsticks/start-playwright.js
tests/common.ts
tests/fixtures.ts

fix testing - not found metamask window in assets-transactions-evm.spec.ts
from time to time, it seems not detect metamask window. so I resolved this by browsing specific metamask url as force
**Check list**

fix testing - not found metamask window in assets-transactions-evm.spec.ts

---

src/components/dapp-staking/my-staking/OnChainData.vue
src/components/dapp-staking/my-staking/styles/on-chain-data.scss
tests/test_specs/dappstaking.spec.ts

Clickable each items on on-chain-data board
**Check list**

Clickable each items on on-chain-data board

---

src/hooks/xcm/useTransferRouter.ts

* hotfix: disabled sending XCM transactions on Astar network
* Todo: Updates Astar's XCM logic to V3 on 26-Jun 
**Check list**
**Changes**
* hotfix: disabled sending XCM transactions on Astar network

hotfix: disabled sending XCM transactions on Astar network

---

src/hooks/xcm/useTransferRouter.ts

Cleaned up GitHub logs & Sync release-hotfix with main.

Sync release-hotfix with main

---

src/config/api/polkadot/chain-specs/astar.json
src/hooks/xcm/useTransferRouter.ts

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Missing commits

---

src/modules/xcm/utils/index.ts

* fix: castXcmEndpoint function
* @gluneau I found a bug in the function and this PR fixes the issue
**Check list**

fix: castXcmEndpoint function

---

src/components/assets/transfer/XcmBridge.vue
src/components/assets/transfer/styles/xcm-bridge.scss
src/hooks/xcm/useXcmBridge.ts
src/i18n/en-US/index.ts
src/v2/repositories/implementations/xcm/InterlayXcmRepository.ts

* fix: getting a async query error in `getTokenBalance` in `InterlayXcmRepository`
* styles: modified icon location 
* fix: updated error message logic
**Check list**
**fixes**
=Before=
=After=

fix: `getTokenBalance` in InterlayXcmRepository.ts

---

src/components/assets/transfer/XcmBridge.vue
src/components/assets/transfer/styles/xcm-bridge.scss
src/hooks/xcm/useXcmBridge.ts
src/i18n/en-US/index.ts
src/v2/repositories/implementations/xcm/InterlayXcmRepository.ts

* fix: getTokenBalance in InterlayXcmRepository.ts
* refactor: comments
* fix: add an error message logic
* fix: Also includes a fix when destination address to the EVM is blank.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

fix: `getTokenBalance` in InterlayXcmRepository.ts (#850)

---

src/components/common/LocaleChanger.vue
src/components/sidenav/SidebarDesktop.vue
src/components/sidenav/SidebarMobile.vue
src/components/sidenav/SidebarOptionDesktop.vue
src/components/sidenav/styles/sidebar-desktop.scss

Language selector styling is not perfect, since this is Quasar component.
| BEFORE | AFTER |
|---------|---------|
|<img width="220" alt="image" src="https://github.com/AstarNetwork/astar-apps/assets/8452361/a562dcf9-b0d6-461b-bbba-8d274caebb5b">|<img width="213" alt="image" src="https://github.com/AstarNetwork/astar-apps/assets/8452361/0602e493-a86a-4873-8964-0b88ea31eb3d">|
**Check list**

Sidebar improvements

---

package.json
src/components/header/modals/ModalPolkasafe.vue
yarn.lock

* feat: updates PolkaSafe package
* fix: display an indicator in selected account on ModalPolkaSafe 
**Check list**
**Fixes**
* fix: display an indicator in selected account on ModalPolkaSafe 
=Before=
=After=

feat: updates PolkaSafe package

---

src/components/header/modals/ModalPolkasafe.vue
src/components/header/styles/modal-account.scss
src/i18n/en-US/index.ts
src/modules/multisig/index.ts
src/v2/repositories/IAssetsRepository.ts
src/v2/repositories/IPolkasafeRepository.ts
src/v2/repositories/implementations/AssetsRepository.ts
src/v2/repositories/implementations/PolkasafeRepository.ts
src/v2/services/IWalletService.ts
src/v2/services/implementations/PolkadotWalletService.ts
tests/common.ts
tests/test_specs/assets-transactions.spec.ts
tests/test_specs/assets.spec.ts

* feat: enables multisig proxy account
* docs PR: https://github.com/AstarNetwork/astar-docs/pull/383
* docs preview: https://astar-docs--pr383-feat-add-proxy-multi-th0yijps.web.app/docs/user-guides/using-a-multisig-account-on-astar-portal#optional-enabling-proxy-signatory-management-for-your-multisig-account-on-polkasafe
**Check list**
**Adds**
* feat: enables multisig proxy account

feat: enables multisig proxy account

---

.github/workflows/s3-hotfix.yml
.github/workflows/s3-production.yml

Pipeline deployment scripts had wrong parameters in PR creation section. 
**Check list**

Deployment scripts PR creation parameters fix

---

.github/workflows/s3-production.yml

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Added 4everland hook support

---

src/config/wallets.ts

**Check list**
Modified the supported evm wallets object.
**Changes**
- Only changed src/config/wallets.ts file 
Deployment links : 
- [astar-portal-iota.vercel.app](https://astar-portal-iota.vercel.app/)
- [astar-portal-n1kt5760a-rares-munteanu.vercel.app](https://astar-portal-n1kt5760a-rares-munteanu.vercel.app/)
Transactions videos link: https://drive.google.com/drive/folders/1oBS52mVKrvWdPazcLYLGL1OVCIeMi02n?usp=sharing
1. Native token transfer -> https://blockscout.com/astar/tx/0xc1252757f44a96b80b46e974bac8cc5c639706957627d5693f0027577c0afdea 
2. ERC20 token transfer ->  https://blockscout.com/astar/tx/0x039f541767bd362deecd098185fc136b7554d847 …

Add Gridlock wallet as evm option

---

src/hooks/xcm/useXcmBridge.ts
src/v2/repositories/implementations/AssetsRepository.ts
src/v2/repositories/implementations/SystemRepository.ts
src/v2/repositories/implementations/XcmRepository.ts

* fix: updated `miscFrozen` and `feeFrozen` values
* fix: updating 'token balance' in XCM transfer 
**Check list**
**Fixes**
* fix: updating 'token balance' in XCM transfer 
=Before=
=After=

fix: updated balance in XCM transfer and `miscFrozen`

---

package.json
src/components/assets/transfer/Transfer.vue
src/components/assets/transfer/TransferModeTab.vue
src/components/common/LocaleChanger.vue
src/components/common/ModalConnectionTrouble.vue
src/components/dashboard/Collators.vue
src/components/dashboard/Dashboard.vue
src/components/dashboard/NetworkStatus.vue
src/components/dashboard/styles/dashboard.scss
src/components/dashboard/styles/network-status.scss
src/components/header/NetworkButton.vue
src/css/box.scss
src/css/text.scss
src/hooks/useNetworkInfo.ts
src/hooks/xcm/useTransferRouter.ts
src/i18n/en-US/index.ts
src/links/index.ts
src/modules/xcm/index.ts
src/pages/Dashboard.vue
tests/common-api.ts
tests/common.ts
tests/test_specs/dashboard.spec.ts
yarn.lock

* wip: Network status
* styles: finished basing styling
* styles: finished basing styling (2)
* feat: added logic
* feat: updated logic
* feat: added tooltip on transfer page
* feat: added collator UI
* fix: clean up
* feat: added test
* feat: added test (2)
* fix: removed version information on the network button
* fix: removed version information on the network button (2)
* refactor: clean up
* fix: links
* fix: added comments
* fix: styling
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

feat: added 'network statuses' section on dashboard page (#886)

---

src/components/assets/Account.vue
src/components/assets/modals/ModalLockdropWarning.vue
src/components/assets/styles/modal-lockdrop-warning.scss
src/i18n/en-US/index.ts

Merge the release-hotfix to main branch

Merge the release-hotfix to main branch

---

tests/test_specs/dappstaking-register.spec.ts

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

fix dappstaking register

---

src/modules/playwright/index.ts
tests/test_specs/dappstaking-register.spec.ts
tests/test_specs/dappstaking-transactions.spec.ts
tests/test_specs/dappstaking.spec.ts

* test: updated `clickDisclaimerButton` function for the new disclaimer modal
**Check list**

test: updated clickDisclaimerButton function for the new disclaimer modal

---

.github/workflows/broken-links.yml

Seems like the documentation support this repeated option
https://lychee.cli.rs/#/usage/cli?id=repeating-options
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Update broken-links.yml to omit multiple paths

---

src/hooks/useBalance.ts
src/modules/account/index.ts
src/modules/xcm/utils/index.ts
src/v2/models/AccountInfoModel.ts
src/v2/repositories/implementations/AssetsRepository.ts
src/v2/repositories/implementations/SystemRepository.ts
tests/common-api.ts

* fix: remove old AccountData properties
* use `frozen` instead of `miscFrozen` 
*  use `flags` instead of `feeFrozen` 
**Check list**

fix: remove old AccountData properties

---

src/components/assets/styles/asset-list.scss
src/i18n/en-US/index.ts

* fix: updated words in Network Status
* fix: updated button's position for EVM native token
**Check list**
**Changes**
* fix: updated words in Network Status
=Before=
=After=
* fix: updated button's position for EVM native token
=Before=
=After=

fix: updated stylings

---

src/modules/information/index.ts
src/modules/information/recent-history/stake/index.ts

Adds user rewards to dapp staking history
**Check list**

Display rewards in user history for dapp staking

---

src/App.vue
src/components/dapp-staking/my-staking/MyStaking.vue
src/config/chainEndpoints.ts
src/v2/app.container.ts
src/v2/services/implementations/EvmDappStakingService.ts

* fix: enable sending transactions from lockdrop accounts
**Check list**
**Fixes**
=Before=
=After=

hotfix: enable sending transactions from lockdrop accounts

---

.github/workflows/s3-hotfix.yml
.github/workflows/s3-production.yml
src/App.vue
src/components/dapp-staking/my-staking/MyStaking.vue
src/config/chainEndpoints.ts
src/v2/app.container.ts

* hotfix: update the hotfix branch
**Check list**

hotfix: update the hotfix branch

---

.github/workflows/s3-hotfix.yml
.github/workflows/s3-production.yml
src/App.vue
src/components/dapp-staking/my-staking/MyStaking.vue
src/config/chainEndpoints.ts
src/v2/app.container.ts

hotfix: merge the hotfix to main branch 
* https://github.com/AstarNetwork/astar-apps/pull/919
* https://github.com/AstarNetwork/astar-apps/pull/918
**Check list**

merge the hotfix to main branch 

---

.github/workflows/s3-hotfix.yml
.github/workflows/s3-production.yml
src/App.vue
src/components/assets/Account.vue
src/components/dapp-staking/my-staking/MyStaking.vue
src/config/chainEndpoints.ts
src/hooks/useConnectWallet.ts
src/v2/app.container.ts

Removes ability to switch to a lockdrop account, since lockdrop will be removed from the network
**Check list**

Remove lockdrop switch

---

src/modules/information/faq/transfer/index.ts

fix broken links discovered by issue https://github.com/AstarNetwork/astar-apps/issues/924
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

fix: broken doc links

---

.github/workflows/firebase-backup.yml

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Update bucket name  in firebase-backup.yml

---

src/components/dapp-staking/my-staking/DynamicAdsArea.vue
src/data/featured_dapp.json

Added MoonFit banner to dApp staking page
**Check list**

Moonfit added

---

src/components/dapp-staking/my-staking/DynamicAdsArea.vue
src/data/featured_dapp.json

This is to merge hotfix updates to main. Merge before next release
**Check list**

Merge hotfix to main

---

src/components/assets/Assets.vue
src/components/header/modals/ModalAccountUnification.vue
src/components/header/modals/account-unification/Step5.vue
src/hooks/wallet/useAccountUnification.ts
src/v2/services/IAccountUnificationService.ts
src/v2/services/implementations/AccountUnificationService.ts
src/v2/services/implementations/PolkadotWalletService.ts

Integrated logic with account unification modal. Go to staging env, connect to Shibuya and select Astar account
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

UA logic integration

---

src/v2/repositories/implementations/xcm/EquilibriumXcmRepository.ts

* feat: updated equilibrium XCM to V3
*  Subscan: https://equilibrium.subscan.io/extrinsic/0x07a87b2d445de1ca91e7bb5bbf9bf59486bc7849b68c81518431f08f4244a0d3
**Check list**

feat: updated equilibrium XCM to V3

---

src/components/assets/Account.vue
src/components/header/Header.vue
src/hooks/useAccount.ts
src/store/general/state.ts
src/v2/messaging/UnifyAccountMessage.ts
src/v2/messaging/index.ts

Display unified account name on Accounts panel
Show account unification modal from Accounts panel
**Check list**

AU - show account name and dialog from

---

src/components/header/modals/ModalAccountUnification.vue
src/components/header/modals/account-unification/AuStep1Native.vue
src/components/header/modals/account-unification/AuStep3.vue
src/hooks/wallet/useAccountUnification.ts
src/i18n/en-US/index.ts
src/v2/models/Identity.ts
src/v2/repositories/IIdentityRepository.ts
src/v2/repositories/implementations/IdentityRepository.ts

Display unification costs

---

.github/workflows/pull-request-preview.yml

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Update firebase CI to be compatible with dependabot PR

---

src/components/bridge/BridgeSelection.vue
src/components/bridge/styles/bridge-selection.scss
src/i18n/en-US/index.ts

little fix for #960 to have link to docs available
**Check list**
**Changes**
- Moved the second texts out from the buttons
- Added learn more link
- Updated the description for Astar Bridge

update bridge select page style

---

.github/workflows/pull-request-preview.yml

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

fix dependabot ci

---

src/components/assets/transfer/Transfer.vue
src/components/header/Header.vue

Popup wallet select modal if user switches to a zk network with a native account
Fixed FAQ links on transfer page when connected to a zk network
**Check list**

Popup wallet select if user is connected with native account and selects zk network

---

package.json
yarn.lock

quasar/extras: 1.16.5 → 1.16.7
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

upgrade: quasar/extras: 1.16.5 → 1.16.7

---

src/components/dapp-staking/my-staking/DynamicAdsArea.vue
src/data/featured_dapp.json

- remove moonfit campaign
- add Algem logo
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

fix:remove moonfit campaign

---

src/config/chainEndpoints.ts

new rpc and explorer url for zKatana
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

fix:new rpc and explorer url for zKatana

---

src/components/header/modals/ModalConnectWallet.vue

Now that the snap audit is done, we re-enabling on prod for Shibuya
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

feat: enable snap on prod

---

src/modules/xcm/index.ts
src/v2/repositories/implementations/XcmRepository.ts
src/v2/repositories/implementations/xcm/AstarXcmRepository.ts

* feat: updated pallet name from 'xtokens' to 'xTokens'
* tested withdrawing to Acala, Phala, Polkadot, Kusama and Karura
**Check list**

feat: updated XCM withdrawal calling

---

src/components/assets/Account.vue

This is to fix https://github.com/AstarNetwork/astar-apps/actions/runs/6781859625/job/18441870142
Currently staging evn doesn't reflect latest main branch
I am not sure how this error passed pipeline checks
**Check list**

Double import fix

---

src/components/assets/transfer/XcmBridge.vue
src/modules/information/faq/transfer/index.ts

Fix links
Closes: https://github.com/AstarNetwork/astar-apps/issues/945 https://github.com/AstarNetwork/astar-apps/issues/996 https://github.com/AstarNetwork/astar-apps/issues/1002 https://github.com/AstarNetwork/astar-apps/issues/1014
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

fix: Link Checker Report

---

src/config/chainEndpoints.ts
src/config/web3/utils/index.ts
src/hooks/xcm/useTransferRouter.ts
src/hooks/xcm/useXcmBridge.ts
src/modules/xcm/index.ts

* fix: enables EVM withdrawal to Moonbeam and Moonriver
* config: added fallback RPC endpoint for zKatana
**Check list**
**Changes**
=Before=
=After=

fix: enables EVM withdrawal to Moonbeam and Moonriver

---

src/config/wallets.ts

New links for the Astar Wallet Snap
**Check list**

fix: Astar Wallet Snap URLs

---

src/components/header/modals/ModalConnectWallet.vue
src/modules/snap/index.ts

* fix: enables Astar Snap on the production page
*  ref: https://github.com/AstarNetwork/astar-apps/pull/1006/files 
**Check list**

fix: enables Astar Snap on the production page

---

src/components/dapp-staking/my-staking/MyRewards.vue

fix: add a link to the docs

---

src/i18n/en-US/index.ts

* hotfix: words
**Check list**

hotfix: words

---

src/router/routes.ts
src/staking-v3/components/Ad.vue
src/staking-v3/components/Dapps.vue
src/staking-v3/components/DiscoverV3.vue
src/staking-v3/components/FeatureDapp.vue
src/staking-v3/components/StakingHome.vue
src/staking-v3/components/styles/ad.scss
src/staking-v3/components/styles/dapps.scss
src/staking-v3/components/styles/discover-v3.scss
src/staking-v3/components/styles/feature-dapp.scss

* feat: added v3 top page (basic styling for the mobile devices only)
**Check list**
**Adds**

feat: added v3 top page

---

src/components/assets/Rewards.vue
src/hooks/useClaimAll.ts

* fix: updated rewards UI on the assets page
Demo: https://www.loom.com/share/686a2a250f244c97b5d41bb4e9c1b7a4
**Check list**

fix: updated rewards UI on the assets page

---

src/App.vue
src/components/common/Balance.vue
src/components/common/FormatBalance.vue
src/components/sidenav/SidebarDesktop.vue
src/css/quasar.variables.scss
src/i18n/en-US/index.ts
src/router/routes.ts
src/staking-v3/components/Amount.vue
src/staking-v3/components/Dapps.vue
src/staking-v3/components/FeatureDapp.vue
src/staking-v3/components/KpiCard.vue
src/staking-v3/components/StakingHome.vue
src/staking-v3/components/Vote.vue
src/staking-v3/components/dapp-selector/DappSelector.vue
src/staking-v3/components/dapp-selector/ModalSelectDapp.vue
src/staking-v3/components/dapp-selector/Model.ts
src/staking-v3/components/styles/dapps.scss
src/staking-v3/components/styles/feature-dapp.scss
src/staking-v3/hooks/index.ts
src/staking-v3/hooks/useCampaign.ts
src/staking-v3/hooks/useDappStaking.ts
src/staking-v3/logic/interfaces/DappStakingV3.ts
src/staking-v3/logic/models/DappStaking.ts
src/staking-v3/logic/repositories/DappStakingRepository.ts
src/staking-v3/logic/repositories/IDappStakingRepository.ts
src/staking-v3/logic/services/DappStakingService.ts
src/staking-v3/logic/services/IDappStakingService.ts
src/staking-v3/store/getters.ts
src/staking-v3/store/mutations.ts
src/staking-v3/store/state.ts

A lot of things happened here
- Vote page to support voting on multiple dApps
- Main page to detect sub periods and change display
- dApp rewards calculation per period (needed for dApp page)
- Bug fixes
**Check list**

Vote on multiple dApps 

---

src/components/dapp-staking/my-staking/Register.vue
src/components/dapp-staking/register/RegisterDapp.vue
src/v2/repositories/IDappStakingRepository.ts
src/v2/repositories/implementations/DappStakingRepository.ts
src/v2/services/IDappStakingService.ts
src/v2/services/implementations/DappStakingService.ts
src/v2/services/implementations/EvmDappStakingService.ts

This PR is to support data fetching optimizations implemented in https://github.com/AstarNetwork/astar-token-api/pull/120
Please review the PR above first. After the PR is merged this PR can be reviewed and tested
**Check list**

dApp fetching optimization

---

src/components/dapp-staking/register/RegisterDapp.vue
src/i18n/en-US/index.ts

fix-styling

---

src/components/dapp-staking/my-staking/MyRewards.vue
src/components/header/modals/ModalConnectWallet.vue
src/hooks/dapps-staking/useDispatchGetDapps.ts
src/hooks/wallet/useAccountUnification.ts
src/i18n/en-US/index.ts
src/modules/snap/index.ts
src/store/dapp-staking/actions.ts
src/v2/services/implementations/MetamaskWalletService.ts
src/v2/services/implementations/XcmEvmService.ts

* merge the 'release-hotfix' to 'main'
* https://github.com/AstarNetwork/astar-apps/pull/1050
* https://github.com/AstarNetwork/astar-apps/pull/1025
**Check list**

merge 'release-hotfix' to 'main'

---

src/components/dapp-staking/dapp/DappStatistics.vue
src/i18n/en-US/index.ts

* styles added `current tier` and `total earned`
**Check list**

styles: added 'current tier' and 'total earned'

---

src/components/assets/NativeAssetList.vue
src/components/assets/Rewards.vue
src/components/assets/modals/ModalEvmWithdraw.vue
src/components/assets/modals/ModalVesting.vue
src/components/dapp-staking/dapp/ProjectDetails.vue
src/components/sidenav/styles/sidebar-desktop.scss
src/hooks/useEvmDeposit.ts
src/i18n/en-US/index.ts

* fix: close the modal after claiming EVM withdrawal
* modified styling in sidebar while the app is loading 
* fix: link to subscan for WASM projects
* feat: added 'Reserved' row under the locked tokens
**Check list**
**Adds**
* feat: added 'Reserved' row under the locked tokens
**Fixes**
* fix: link to subscan for WASM projects

fix: resolved new assets page bugs

---

.github/workflows/s3-staging.yml

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

fixing s3-staging.yml

---

.github/workflows/s3-staging.yml

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

minor update s3-staging.yml

---

src/v2/services/implementations/PolkadotWalletService.ts

This PR is to better handle errors before extrinsic call is initiated. E.g. if caller balance is to low to pay gas spinner on UI will spin forever and error will be only visible in a browser console. 
Basically just added one more try/catch block.
BEFORE
AFTER
**Check list**

Improve polkadot.js errors handling

---

src/i18n/en-US/index.ts
src/staking-v3/components/Vote.vue
src/staking-v3/components/data/DataList.vue
src/staking-v3/components/my-staking/ModalUnbondDapp.vue
src/staking-v3/components/my-staking/MyDapps.vue
src/staking-v3/configureLocalNode.mjs
src/staking-v3/hooks/useDappStaking.ts
src/staking-v3/logic/interfaces/DappStakingV3.ts
src/staking-v3/logic/models/Node.ts
src/staking-v3/logic/repositories/DappStakingRepository.ts

Fixed compatibility issues with the latest runtime branch feat/dapp-staking-v3-phase6
+ small improvements
**Check list**

Compatibility issues fix

---

src/components/assets/EvmNativeToken.vue
src/components/assets/NativeAssetList.vue
src/config/wallets.ts
src/hooks/useFaucet.ts

Update amount below which user is able to call faucet.
**Check list**

faucetBalRequirement update

---

src/data/dapp_promotions.json

> This pull request updates the _dapp_promotion.json_ file to include the latest promotional details for the **Age of Chronos** dapp.
**Check list**
**Adds**
- Included **Age of Chronos** in the dapp promotion section, a game that utilizes NFT 2.0 technology to offer an interactive and engaging gameplay experience.

Age of Chronos - dapp promotion

---

src/components/header/modals/ModalConnectWallet.vue
src/hooks/useAccount.ts
src/hooks/useNetworkInfo.ts
src/modules/snap/index.ts

Allow Astar Wallet Snap on all networks
**Check list**

Allow Astar Wallet Snap on all networks

---

src/pages/DappPage.vue
src/staking-v3/components/dapp/Builders.vue
src/staking-v3/components/dapp/DappAvatar.vue
src/staking-v3/components/dapp/DappImages.vue
src/staking-v3/components/dapp/DappStatistics.vue
src/staking-v3/components/dapp/DappStatsCharts.vue
src/staking-v3/components/dapp/DappV3.vue
src/staking-v3/components/dapp/ProjectDetails.vue
src/staking-v3/components/dapp/ProjectOverview.vue
src/staking-v3/components/dapp/StatsChart.vue
src/staking-v3/components/dapp/styles/builders.scss
src/staking-v3/components/dapp/styles/dapp-avatar.scss
src/staking-v3/components/dapp/styles/dapp-images.scss
src/staking-v3/components/dapp/styles/dapp-statistics.scss
src/staking-v3/components/dapp/styles/dapp-stats-charts.scss
src/staking-v3/components/dapp/styles/dapp.scss
src/staking-v3/components/dapp/styles/project-details.scss
src/staking-v3/components/dapp/styles/project-overview.scss
tests/chopsticks/astar.yml

* fix: copy project page components to the staking-v3 folder
**Check list**

fix: copy the project page components to the staking-v3 folder

---

src/data/dapp_promotions.json

Neurolanche dApp Promotion Card

---

src/i18n/en-US/index.ts

Updated the claim warning banner text
**Check list**
**Changes**

hotfix: update claim warning banner text

---

src/components/header/ClaimWarningBanner.vue
src/components/header/Header.vue
src/components/header/HeaderComp.vue
src/i18n/en-US/index.ts
src/layouts/DashboardLayout.vue
src/v2/services/implementations/MetamaskWalletService.ts

* hotfix: merge the release-hotfix to main branch
* https://github.com/AstarNetwork/astar-apps/pull/1104
* https://github.com/AstarNetwork/astar-apps/pull/1107 
**Check list**

hotfix: merge the release-hotfix to main branch

---

src/hooks/useCurrentEra.ts

* fix: Era count down component for dApp staking V3
**Check list**
**Fixes**
=Before=
=After=

fix: Era count down component for dApp staking V3

---

src/i18n/en-US/index.ts
src/staking-v3/components/Dapps.vue
src/staking-v3/components/dapp/DappBackground.vue
src/staking-v3/components/dapp/DappStatistics.vue
src/staking-v3/hooks/useDappStaking.ts
src/staking-v3/hooks/useDapps.ts
src/staking-v3/hooks/useLeaderboard.ts
src/staking-v3/logic/models/DappStaking.ts
src/staking-v3/logic/repositories/IDataProviderRepository.ts
src/staking-v3/logic/repositories/TokenApiProviderRepository.ts
src/staking-v3/logic/repositories/index.ts
src/staking-v3/logic/services/DappStakingService.ts
src/staking-v3/logic/services/DappStakingServiceEvm.ts
src/staking-v3/store/mutations.ts
src/v2/app.container.ts
src/v2/symbols.ts

Fetch number of stakers from Token API and display on a dApp page and a dApp card
**Check list**

Display number of stakers

---

src/config/api/polkadot/connectApi.ts
src/css/app.scss
src/layouts/DashboardLayout.vue
src/pages/StakeManage.vue
src/v2/services/implementations/PolkadotWalletService.ts

* refactor: `PolkadotWalletService`
* fix: display loading animation for Enkrypt wallet
* fix: update `checkIsSubstrateConnectInstalled` function 
* fix: background color for bigger screen
* fix: position for `Back to dApp list` link
**Check list**
**Fixes**
* refactor: `PolkadotWalletService`
* fix: display loading animation for Enkrypt wallet
=After=
*  fix: background color for bigger screen
=Before=
=After=
* fix: position for `Back to dApp list` link
=Before=
=After=

fix: refactor PolkadotWalletService

---

src/staking-v3/components/leaderboard/LeaderboardVote.vue
src/staking-v3/components/leaderboard/styles/leaderboard.scss

Added the pagination to the ranking while the vote period
**Check list**

add vote period ranking pagination

---

src/i18n/en-US/index.ts

English grammar corrections
**Check list**

fix: English grammar corrections

---

src/components/assets/NativeAssetList.vue
src/components/assets/styles/asset-list.scss
src/i18n/en-US/index.ts
tests/test_specs/dappstaking-transactions.spec.ts

* hotfix: added a vesting note
**Check list**
**Adds**
* hotfix: added a vesting note

hotfix: added a vesting note

---

src/i18n/en-US/index.ts
src/staking-v3/components/FeatureDapp.vue
src/staking-v3/components/KpiCard.vue
src/staking-v3/components/data/DataCard.vue
src/staking-v3/components/data/DataList.vue
src/staking-v3/components/styles/feature-dapp.scss
src/staking-v3/hooks/usePeriod.ts

- Added the flip hover style for kpi cards
- Added the flip hover style for data catds
**Check list**
**Changes**
- KPI cards
- Data cards

add flip descriptions

---

src/components/header/ClaimWarningBanner.vue
src/i18n/en-US/index.ts

Updated the warning banner for ledger users
**Check list**
**Changes**
- All chains except Shibuya
- Shibuya

hotfix: add link banner for ledger users

---

src/components/header/ClaimWarningBanner.vue
src/i18n/en-US/index.ts

* hotfix: merge the hotfix to main branch 
*  https://github.com/AstarNetwork/astar-apps/pull/1144
**Check list**

hotfix: merge the hotfix to main branch 

---

src/App.vue
src/components/dapp-staking/ModalDecommission.vue
src/components/dapp-staking/dapp/DappAvatar.vue
src/components/dapp-staking/my-staking/components/CardList.vue
src/components/dapp-staking/stake-manage/StakeManage.vue
src/config/localStorage.ts
src/hooks/dapps-staking/useDecommission.ts
src/hooks/index.ts
src/store/dapp-staking/getters.ts
src/store/dapp-staking/mutations.ts
src/store/dapp-staking/state.ts

This PR is to support dApp staking v2 decommission mode. When pallet is put to decommission mode, UI will show modal to users.
The modal will be visible on Shibuya when v2 pallet is put to decommission mode (`dappsStaking.decommissionStarted = true`).
**Check list**

Decommission mode support

---

src/components/header/Header.vue
src/components/header/styles/modal-network-wallet.scss

* style: updated styling on the network modal
**Check list**
**Fixes**

style: updated styling on the network modal

---

src/hooks/xcm/useTransferRouter.ts

* hotfix: disabling xcm transfer in Shiden
**Check list**

hotfix: disabling xcm transfer in Shiden

---

src/hooks/xcm/useTransferRouter.ts

* hotfix: merge the latest hotfix to main branch
*  https://github.com/AstarNetwork/astar-apps/pull/1156 
**Check list**

hotfix: merge the latest hotfix to main branch

---

src/staking-v3/hooks/useLeaderboard.ts
src/staking-v3/logic/interfaces/DappStakingV3.ts
src/staking-v3/logic/models/DappStaking.ts
src/staking-v3/logic/repositories/DappStakingRepository.ts
src/staking-v3/logic/services/DappStakingService.ts

* Handle removal of unregistered dApps from a note storage
* Map dapp id

Handle removal of unregistered dApps from a node storage (#1155)

---

src/i18n/en-US/index.ts
src/links/index.ts
src/staking-v3/components/Vote.vue
src/staking-v3/components/styles/vote.scss

Added links to the voting page ([ref](https://astar-foundation.slack.com/archives/C028H2ZSGRK/p1707197971274099))
**Check list**

Add learn links

---

src/staking-v3/hooks/useAprV3.ts

* fix: get periodsPerCycle from onchain
*  https://github.com/AstarNetwork/astar-apps/pull/1136#issuecomment-1895640411 
**Check list**

fix: get periodsPerCycle from onchain

---

src/router/index.ts
src/router/routes.ts
src/staking-v3/components/my-staking/MyStaking.vue
src/staking-v3/hooks/useAprV3.ts
src/staking-v3/hooks/useDappStaking.ts

**To be merged and deployed after Shiden runtime upgrade**
- as title says
**Check list**

Enable dApp staking v3 on Shiden

---

src/hooks/useTokenDistribution.ts
src/hooks/useTvlHistorical.ts
src/staking-v3/logic/services/DappStakingServiceV2V3.ts
src/store/dapp-staking/actions.ts

This PR is to fix token circulation panel on Dashboard which got broken after Shiden runtime upgrade.
**Check list**

Fix for Shiden circulation panel

---

src/components/dapp-staking/StakingTop.vue
src/components/dapp-staking/my-staking/DappList.vue
src/components/dapp-staking/my-staking/components/CardList.vue

Display unstoppable grants category on dApp staking v2 UI
**Check list**

Display unstoppable grants category in staking v2

---

src/hooks/useCurrentEra.ts

* fix: displays the Era count down UI for V3
**Check list**
**Fixes**

fix: displays the Era count down UI for V3

---

src/components/header/modals/SelectWallet.vue

* fix: disabled WalletConnect temporarily
**Check list**
**Changes**

fix: disabled WalletConnect temporarily

---

src/router/index.ts
src/router/routes.ts

&#127881;
See the title
**Check list**

Enable dApp staking v3 on Astar

---

src/hooks/xcm/useTransferRouter.ts

* fix: enable XCM transactions on Shiden
**Check list**

fix: enable XCM transactions on Shiden

---

src/components/header/modals/SelectWallet.vue

* feat: enables Wallet Connect
**Check list**
**Changes**
* feat: enables Wallet Connect

fix: enables Wallet Connect

---

src/hooks/useGasPrice.ts

* fix: enable tips for the native transactions
**Check list**
**Changes**
* fix: enable tips for the native transactions
=Before=
=After=

fix: enable tips for the native transactions

---

src/components/assets/Assets.vue
src/components/assets/styles/assets.scss
src/components/assets/transfer/styles/mobile-navigator.scss
src/components/bridge/BridgeSelection.vue
src/components/bridge/ethereum/L1History.vue
src/components/bridge/styles/bridge-selection.scss
src/components/header/styles/modal-network-wallet.scss
src/i18n/en-US/index.ts
src/i18n/es/index.ts
src/i18n/fr/index.ts
src/i18n/ja/index.ts
src/layouts/DashboardLayout.vue
src/pages/AssetsPage.vue
src/pages/BridgePage.vue
src/pages/DappStaking.vue
src/pages/DappStakingV3.vue
src/pages/Dashboard.vue

* fix: updated bridge page styling
* fix: applied background to all the pages (except dApp staking page)
**Check list**
**Changes**
* fix: updated bridge page styling

fix: updated bridge page styling

---

src/modules/information/faq/dapp-staking/index.ts

Closes https://github.com/AstarNetwork/astar-apps/issues/1209
**Check list**

Broken links fix

---

src/components/bridge/ethereum/L1Bridge.vue
src/hooks/bridge/useL1Bridge.ts

* feat: enables withdrawal from L2
**Check list**

feat: enables withdrawal from L2

---

src/components/bridge/BridgeSelection.vue
src/components/common/TokenBalanceNative.vue
src/hooks/useNetworkInfo.ts
src/i18n/en-US/index.ts
src/staking-v3/components/DiscoverV3.vue
src/staking-v3/components/FeatureDapp.vue
src/staking-v3/components/dapp/DappStatistics.vue
src/staking-v3/hooks/useDappStaking.ts

* fix: caption for Ethereum bridge
* fix: modified dApp staking page for zkEVM
**Check list**
**Fixes**
* fix: caption for Ethereum bridge
=Before=
=After=
the caption won’t appear when the portal connects to Astar zkEVM
* fix: modified dApp staking page for zkEVM
* Disabled staking buttons
* Modified currency
=Before=
=After=
* Added toast

fix: modified dApp staking for zkEVM and caption for Ethereum bridge

---

src/components/bridge/BridgeSelection.vue

* hotfix: disabled relay bridge
**Check list**

hotfix: disabled releay bridge

---

src/modules/evm/index.ts
src/v2/services/implementations/MetamaskWalletService.ts
src/v2/services/implementations/ZkBridgeService.ts
yarn.lock

* fix: disable site suggested fee in MetaMask
**Check list**
**Changes**
=Before=
=After=

fix: disable site suggested fee in MetaMask

---

src/components/bridge/BridgeSelection.vue

- re-enable relay link bridge
**Check list**

re-enable relay link bridge

---

src/hooks/bridge/useL1History.ts
src/modules/zk-evm-bridge/l1-bridge/utils.ts

* fix: removed non Astar zkEVM bridge history
**Check list**
=Before=
These are bridge transaction between Ethereum and Polygon zkEVM

fix: removed non Astar zkEVM bridge history

---

src/hooks/useAppRouter.ts

* fix: disabled connecting Astar zkEVM with native wallets
**Check list**

fix: disabled connecting Astar zkEVM with native wallets

---

src/components/assets/Account.vue

* fix: USD asset value
**Check list**

fix: USD asset value

---

src/staking-v3/components/leaderboard/Tier.vue
src/staking-v3/components/leaderboard/noEntry.vue
src/staking-v3/components/leaderboard/styles/tier.scss
src/staking-v3/hooks/useDappStaking.ts

I am not sure how this happened that I hardcoded 2 pages per tier 😊 
Fix is here.
**Check list**

Fix for tier display to show more than 2 pages

---

src/components/dashboard/Dashboard.vue
src/hooks/useTvlHistorical.ts
src/staking-v3/hooks/useDappStaking.ts

fixes the number of stakers on the dashboard and pulls them from v3 indexer
**Check list**

fix: number of stakers from v3 indexer

---

src/components/header/YokiBanner.vue
src/i18n/en-US/index.ts

Added warning when user is connected to zKatana network
**Check list**

zKatana shutdown warning

---

src/hooks/xcm/useXcmBridge.ts

fix: XCM deposit ASTR token
**Check list**
**Fixes**
=Before=
=After=

fix: XCM deposit ASTR token

---

src/v2/repositories/implementations/TokenApiRepository.ts

* fix: return 0 if the app failed fetching USD price
**Check list**
**Fixes**
=Before=
=After=

fix: price fetching

---

src/components/bridge/ethereum/L1Bridge.vue
src/components/bridge/ethereum/styles/l1-bridge.scss
src/components/common/ModalBridgeHighTraffic.vue
src/components/common/styles/modal-bridge-high-traffic.scss
src/i18n/en-US/index.ts

**Check list**
**Changes**
- update testnetSwitchWarning content to `We have switched our zkEVM testnet to zKyoto from zKatana. zKatana will no longer available.`
**To-dos**

Update Testnet migration warning banner's text & Add bridge warning 

---

src/components/dashboard/Burn.vue
src/components/dashboard/Dashboard.vue
src/components/dashboard/NetworkStatus.vue
src/components/dashboard/ZkEvmDashboard.vue
src/components/dashboard/ZkEvmNetworkStatus.vue
src/components/dashboard/styles/burn.scss
src/components/dashboard/styles/dashboard.scss
src/components/dashboard/styles/network-status.scss
src/components/header/mobile/MobileNav.vue
src/components/sidenav/SidebarDesktop.vue
src/hooks/useNetworkInfo.ts
src/hooks/useTokenCirculation.ts
src/i18n/en-US/index.ts
src/pages/Dashboard.vue
src/staking-v3/components/data/DataList.vue

- add dashboard for zkEVM
- refactor hooks
- fix typo
**Check list**
**Adds**
- add dashboard for zkEVM
**Fixes**
- typo issue of currency (ASTAR -> ASTR)
- add condition of `staking and locking accounts` in staking-v3 DataList component that occurs error
**Changes**
- refactor useTokenCirculation to handle zkEVM
- refactor NetworkStatus component and add zkEVM

feat: add dashboard for zkEVM

---

src/components/assets/Assets.vue
src/components/assets/EvmNativeToken.vue
src/components/assets/ZkAstr.vue
src/components/assets/styles/asset-list.scss
src/components/assets/transfer/LocalTransfer.vue
src/i18n/en-US/index.ts
src/modules/zk-evm-bridge/index.ts
src/modules/zk-evm-bridge/tokens.ts

* feat: added vAstr
* fix: show the faucet button on Shibuya EVM
* fix: warning message on Transfer page
**Check list**
**Adds**
* feat: added vAstr
**Fixes**
* fix: show the faucet button on Shibuya EVM
=Before=
=After=
* fix: warning message on Transfer page
=Before=
=After=

feat: added vAstr

---

.github/workflows/broken-links.yml
src/links/index.ts

- fix docs link for troubleshooting the portal
- add it to the broken link workflow
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

fix: docs link for troubleshooting the portal and add it to the broken link workflow

---

src/components/assets/transfer/XcmBridge.vue
src/hooks/xcm/useXcmBridge.ts
src/i18n/en-US/index.ts
src/modules/xcm/tokens/index.ts
src/v2/repositories/implementations/XcmRepository.ts

* fix: updated XCM UI for Pink token
**Check list**
**Adds**
* Added a warning for withdrawing PINK token from Native
* Check the USDT balance  
* Disabled withdrawal via EVM wallets temporarily

fix: updated XCM UI for Pink token

---

src/components/header/UnderMaintenanceBanner.vue
src/i18n/en-US/index.ts
src/layouts/DashboardLayout.vue

- Added zkEVM under maintenance banner for all networks
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

hotfix: zkEVM under maintenance banner

---

src/modules/zk-evm-bridge/l1-bridge/utils.ts
src/modules/zk-evm-bridge/tokens.ts

* fix: removed weETH 
* feat: added DOT
**Check list**
**Adds**
* feat: added DOT
**Changes**
* fix: removed weETH
* weETH token will be added after it lists on Stargate

feat: removed weETH and added DOT on zkEVM

---

src/components/assets/Account.vue
src/hooks/useNetworkInfo.ts
src/v2/services/implementations/MetamaskWalletService.ts

* feat: enabled lockdrop dispatch feature for Astar and Shiden
**Check list**
**Adds**

feat: enabled lockdrop dispatch feature for Astar and Shiden

---

src/components/bridge/BridgeSelection.vue
src/i18n/en-US/index.ts
src/modules/zk-evm-bridge/index.ts

* fix: removed relay link
**Check list**
**Fixes**
=Before=
=After=

fix: removed relay link

---

.github/workflows/s3-hotfix.yml

> Enable the manual deployment (using github action) on `release-hotfix` branch to hotfix deployment too
**Check list**
**Changes**
- Add manual deployment on `Deploy to Release hotfix-S3` action

add manual deployment on hotfix too

---

src/components/bridge/BridgeSelection.vue
src/components/header/UnderMaintenanceBanner.vue
src/i18n/en-US/index.ts
src/layouts/DashboardLayout.vue
src/modules/zk-evm-bridge/index.ts
src/modules/zk-evm-bridge/l1-bridge/utils.ts
src/modules/zk-evm-bridge/tokens.ts

* merge the hotfix to main
* https://github.com/AstarNetwork/astar-apps/pull/1271 
**Check list**

hotfix: merge the hotfix to main 

---

src/components/bridge/ethereum/L1Bridge.vue
src/i18n/en-US/index.ts

This reverts commit fe186dcc2b9fbe01b8d5a771b280e67160d590ff.
Re-enable bridge deposit
**Check list**

Revert "add native bridge deposit warning banner (#1275)"

---

.github/workflows/s3-production.yml

> Sorry for the long commit message, It is for the create hotfix branch after Production deployment automatically
**Check list**
**Changes**
- Add few steps after production deployment in s3-production.yml github action

Re-create hotfix branch after deployment

---

src/v2/services/implementations/MetamaskWalletService.ts

* fix: updating lockdrop contract address for Shiden
**Check list**

fix: updating lockdrop contract address for Shiden

---

src/hooks/useInflation.ts

Fixed the hook because sometimes inflation data wasn't loaded.
Change log looks messy, but basically I removed singleton instance
`let inflationInstance: UseInflation | undefined = undefined;`
**Check list**

useInflation hook fix

---

src/hooks/xcm/useTransferRouter.ts
src/hooks/xcm/useXcmBridge.ts

* fix: modified token bug in XCM transfer UI
* fix: modified error message in XCM transfer UI
**Check list**
**Adds**
**Fixes**
* fix: modified token bug in XCM transfer UI
* ASTR token shouldn't support bridging between Astar and Polkadot
* demo for the bug: https://www.loom.com/share/469e4ed2666243b6bd35e20ebbe5e99b?sid=6d654eee-ee53-4ac2-8fc0-c1e2c69b7774  
=Before=
* fix: modified error message in XCM transfer UI
=Before=
=After=

fix: modified token bug in XCM transfer UI

---

src/components/header/DappStakingBanner.vue
src/i18n/en-US/index.ts
src/layouts/DashboardLayout.vue

Voting period start banner will show 15 eras before Vote sub period start
**Check list**

Voting period start banner

---

src/i18n/en-US/index.ts

Updated the banner text
**Check list**

dApp staking banner text update

---

src/constants.ts
src/staking-v3/logic/repositories/DappStakingRepository.ts
src/staking-v3/logic/repositories/IDappStakingRepository.ts

Fixed error 404 handling for `getDapp` method
**Check list**

Improve getDapp method error handling

---

src/hooks/xcm/useTransferRouter.ts

* hotfix: disabling xcm transfer for Shiden
**Check list**

hotfix: disabling xcm transfer for Shiden

---

src/staking-v3/components/vote/choose-dapps/DappsList.vue

Fixed missing dApps in others category
**Check list**

Fix for filtering dApps in other category

---

src/staking-v3/components/vote/choose-dapps/DappsList.vue

Additional fix for #1322 
**Check list**

Category filter fix, take 2

---

src/staking-v3/hooks/useDappStaking.ts

Fixed invalid tier display on dApp page
**Check list**

Tier display fix

---

src/data/dapp_promotions.json

> Update Ledger Promotion as first in dapp promotions file
**Check list**
**Changes**
- Update `dapp_promotions.json` to set Ledger Promotion as first

Update dapp promotions file to set Ledger as first

---

src/data/dapp_promotions.json

> Fix promotion file, file is little messy after resolve conflict.
**Check list**
**Fixes**
- fix dapp_promotions.json

Fix Promotion file

---

src/i18n/en-US/index.ts
src/staking-v3/components/VotingPeriodSideAdd.vue

> Fix stake today card, and remove v-html which is not recommanded
**Check list**
**Fixes**
- Fix stake today card, and remove v-html which is not recommanded

Fix stake today card

---

src/staking-v3/components/VotingPeriodSideAdd.vue

> fix stake today card 2, #1339 was not fixed
**Check list**
**Fixes**
- Fix stake today card style

fix stake today card 2

---

src/hooks/useNetworkInfo.ts
src/modules/zk-evm-bridge/l1-bridge/index.ts

* hotfix: enabled zkEVM bridge for zKyoto
**Check list**
**Changes**
* hotfix: enabled zkEVM bridge for zKyoto

hotfix: enabled zkEVM bridge for zKyoto

---

src/hooks/useNetworkInfo.ts

* hotfix: disable zkevm bridge
**Check list**

hotfix: disable zkevm bridge

---

src/components/bridge/BridgeSelection.vue
src/components/bridge/layerzero/LzBridge.vue
src/i18n/en-US/index.ts

> disable layerzero bridge for zkEVM Maintenance 
**Check list**
**Adds**
- add isOnMaintenance in layerzero bridge page

disable layerzero bridge for zkEVM Maintenance 

---

src/components/bridge/ethereum/L1Bridge.vue
src/hooks/useNetworkInfo.ts
src/modules/zk-evm-bridge/l1-bridge/index.ts

> Maintenance is done, re enable bridge
**Check list**
**Changes**
- set `isBridgeMaintenanceMode` as false

Re enable bridge

---

src/staking-v3/logic/services/DappStakingService.ts

Fixed a bug where staked amount was used instead of vote amount
**Check list**

Bonus APR calculation fix

---

src/hooks/xcm/useTransferRouter.ts

* hotfix: disabled polkadot xcm temporally 
*  if you want to check on your end (https://github.com/AstarNetwork/astar-apps/pull/1313#issuecomment-2162687148)
**Check list**

hotfix: disabled xcm on Astar temporally 

---

src/components/bridge/BridgeSelection.vue
src/components/bridge/ethereum/L1Bridge.vue
src/components/bridge/layerzero/LzBridge.vue
src/hooks/useInflation.ts
src/hooks/useNetworkInfo.ts
src/hooks/xcm/useTransferRouter.ts
src/i18n/en-US/index.ts
src/modules/zk-evm-bridge/l1-bridge/index.ts
src/staking-v3/components/VotingPeriodSideAdd.vue
src/staking-v3/logic/services/DappStakingService.ts

* merge release hotfix branch
**Check list**

merge release hotfix branch

---

src/hooks/usePrice.ts

> the usePrice hooks using watch function, so It is not trigger at first time. enabled immediate option on watch to call it on mounted
**Check list**
**Fixes**
- using immediate option on watch in usePrice hooks

Fix usePrice hooks

---

src/components/assets/Erc20Currency.vue
src/components/assets/EvmCbridgeToken.vue
src/components/assets/EvmNativeToken.vue
src/components/bridge/BridgeSelection.vue
src/hooks/usePrice.ts
src/i18n/en-US/index.ts
src/v2/repositories/implementations/IdentityRepository.ts

For details see commits list below
**Check list**

Merge release-hotfix to main

---

src/links/index.ts
src/modules/xcm/index.ts

* hotfix: enable xcm with Bifrost
* fix: modified variables for debugging environment 
**Check list**

hotfix: enable xcm with Bifrost

---

src/config/localStorage.ts
src/hooks/useChainInfo.ts
src/hooks/useMetaExtensions.ts

Added raw metadata to chain info which is used to update a wallet metadata. Raw metadata is needed for Ledger signing
**Check list**

Add raw metadata to chain info

---

src/data/dapp_promotions.json

**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

Added NEET dapp_promotions.json

---

src/hooks/useChainInfo.ts
src/staking-v3/logic/services/DappStakingService.ts

Fixed issue with loading dApps on Shibuya
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**

dApps loading error fix for Shibuya

---

src/components/header/mobile/MobileNav.vue

> Hiding the blog section in the mobile header
**Check list**
**Changes**
- Hide the blog section in the mobile header

hide blog section

---

src/components/header/mobile/AstarDomains.vue

as the PR title says
**Check list**

Startale link fix

---

src/components/header/mobile/MobileNav.vue

**Check list**
**Adds**
- Add Governance link to mobile nav

Governance url

---

src/components/assets/EvmNativeToken.vue
src/config/localStorage.ts

* fix: displays CCIP tooltip only once
**Check list**
**Fixes**

fix: displays CCIP tooltip only once

---

.gitignore
src/router/utils/index.ts

* fix: redirect to assets page after changing the network
**Check list**

fix: redirect to assets page after changing the network

---

src/components/header/modals/SelectAccount.vue
src/staking-v3/components/ClaimAndRestakeButton.vue
src/staking-v3/components/vote/re-stake/ModalRestake.vue
src/staking-v3/hooks/useVote.ts

Added check which was initially forgotten to test if staking is available (e.g. staking in the last era of a period is not possible)
**Check list**

Don't offer rewards re-staking if staking is not possible

---

src/components/bridge/ccip/CcipBridge.vue
src/i18n/en-US/index.ts

* fix: updated warning message for the CCIP bridge UI
**Check list**
**Fixes**
Modified warning message for users who open the page by the direct link.
https://portal.astar.network/astar/bridge/ccip
=Before=
=After=

fix: updated warning message for the CCIP bridge UI

---

src/components/assets/NativeAssetList.vue
src/hooks/useBalance.ts
src/staking-v3/hooks/useVote.ts

This is something we forgot to include when governance was released on our networks
**Check list**

Enable staking tokens locked in democracy

---

src/config/web3/index.ts

* fix: updated Ethereum RPC
**Check list**

fix: updated Ethereum RPC

---

src/staking-v3/components/my-staking/MyDapps.vue

Temporary disable unstake from unregistered call because of a bug in dApp staking
**Check list**

Temporary disable unstake from unregistered call

---

src/config/chainEndpoints.ts

As title states
**Check list**

Change zkEVM RPC endpoint

---

src/components/assets/EvmNativeToken.vue
src/components/bridge/BridgeSelection.vue
src/components/header/modals/ModalNetworkWallet.vue
src/components/header/modals/SelectNetwork.vue
src/components/header/modals/SelectWallet.vue
src/hooks/useAppRouter.ts
src/i18n/en-US/index.ts
src/modules/token/utils/index.ts

* hotfix: removed zkEVM links
**Check list**
**Changes**
=Before=
=After=

hotfix: removed zkEVM links

---

src/hooks/bridge/useCcipBridge.ts

* fix: removed unnecessary line
**Check list**

fix: removed unnecessary line

---

src/components/assets/Assets.vue
src/components/dapp-staking/register/RegisterDapp.vue
src/hooks/dapps-staking/useSignPayload.ts
src/staking-v3/hooks/useDapps.ts
src/staking-v3/hooks/useRegisterDapp.ts
src/staking-v3/logic/repositories/DappStakingRepository.ts
src/staking-v3/logic/repositories/IDappStakingRepository.ts
src/v2/services/IWalletService.ts
src/v2/services/implementations/MetamaskWalletService.ts
src/v2/services/implementations/PolkadotWalletService.ts

Enables dApp registration to dApp staking with EVM account
**Check list**

Register a dApp to dApp staking with EVM account

---

src/components/header/mobile/AstarDomains.vue

Removed astar 2.0 and tech stack link
**Check list**
**Changes**

Remove astar 2.0 and tech stack link
